#Copyright (c) KMG. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0


# HaloDB Storage Driver Configuration
storageDirectory=/tmp/halodb
maxFileSize=1073741824
maxTombstoneFileSize=67108864
buildIndexThreads=8
flushDataSizeBytes=10485760
compactionThresholdPerFile=0.7
compactionJobRate=52428800
numberOfRecords=100000000
cleanUpTombstonesDuringOpen=true
cleanUpInMemoryIndexOnClose=false
useMemoryPool=true
memoryPoolChunkSize=2097152
fixedKeySize=8
