{
 "title": "SBK Dashboard",
 "tags": [ "SBK" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "SBK Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Writers Connections",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Writing_Connections", "legendFormat": "Active" },
      { "expr": "SBK_Writing_Max_Connections", "legendFormat": "Max" }
     ]
    },
    {
     "title": "Readers Connections",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Reading_Connections", "legendFormat": "Active" },
      { "expr": "SBK_Reading_Max_Connections", "legendFormat": "Max" }
     ]
    },
    {
     "title": "Write-Readers Connections",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Write_Reading_Connections", "legendFormat": "Active" },
      {
       "expr": "SBK_Write_Reading_Max_Connections",
       "legendFormat": "Max"
      }
     ]
    }
   ]
  },
  {
   "title": "Write Performance Benchmarking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "SBK Write Throughput MB/s",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      { "expr": "SBK_Writing_MBPerSec" }
     ]
    },
    {
     "title": "SBK Write Records/Sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      { "expr": "SBK_Writing_RecordsPerSec" }
     ]
    },
    {
     "title": "SBK Write Avg and Max Latencies (Nanoseconds)",
     "type": "stat",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Writing_ns_AvgLatency", "legendFormat": "Average Latency" },
      { "expr": "SBK_Writing_ns_MaxLatency", "legendFormat": "Max Latency" }
     ]
    },
    {
     "title": "SBK Write Percentiles (Nanoseconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      { "expr": "SBK_Writing_ns_10" },
      { "expr": "SBK_Writing_ns_20" },
      { "expr": "SBK_Writing_ns_25" },
      { "expr": "SBK_Writing_ns_30" },
      { "expr": "SBK_Writing_ns_40" },
      { "expr": "SBK_Writing_ns_50" },
      { "expr": "SBK_Writing_ns_60" },
      { "expr": "SBK_Writing_ns_70" },
      { "expr": "SBK_Writing_ns_75" },
      { "expr": "SBK_Writing_ns_80" },
      { "expr": "SBK_Writing_ns_90" },
      { "expr": "SBK_Writing_ns_92_5" },
      { "expr": "SBK_Writing_ns_95" },
      { "expr": "SBK_Writing_ns_97_5" },
      { "expr": "SBK_Writing_ns_99" },
      { "expr": "SBK_Writing_ns_99_25" },
      { "expr": "SBK_Writing_ns_99_5" },
      { "expr": "SBK_Writing_ns_99_75" },
      { "expr": "SBK_Writing_ns_99_9" },
      { "expr": "SBK_Writing_ns_99_95" },
      { "expr": "SBK_Writing_ns_99_99" }
     ]
    },
    {
     "title": "SBK Writers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Writing_Writers", "legendFormat": "Active" },
      { "expr": "SBK_Writing_Max_Writers", "legendFormat": "Max" }
     ]
    },
    {
     "title": "SBK Write Throughput MB/s",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 11, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Writing_MBPerSec" }
     ]
    },
    {
     "title": "SBK Write  Sliding Latency Coverage (SLC)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Writing_SLC_1", "legendFormat": "SLC 1" },
      { "expr": "SBK_Writing_SLC_2", "legendFormat": "SLC 2" }
     ]
    },
    {
     "title": "SBK Write Bytes Total",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Writing_Records_total" }
     ]
    },
    {
     "title": "SBK Write Discarded Latencies",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 11, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Reading_LowerDiscardedLatencyRecords_total",
       "legendFormat": "Lower"
      },
      {
       "expr": "SBK_Reading_HigherDiscardLatencyRecords_total",
       "legendFormat": "Higher"
      },
      {
       "expr": "SBK_Reading_InvalidLatencyRecords_total",
       "legendFormat": "Invalid/Negative"
      }
     ]
    },
    {
     "title": "SBK Write Avg and Max Latencies (Microseconds)",
     "type": "stat",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Writing_mcs_AvgLatency", "legendFormat": "Average Latency" },
      { "expr": "SBK_Writing_mcs_MaxLatency", "legendFormat": "Max Latency" }
     ]
    },
    {
     "title": "SBK Write Percentiles (Microseconds)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      { "expr": "SBK_Writing_mcs_10" },
      { "expr": "SBK_Writing_mcs_25" },
      { "expr": "SBK_Writing_mcs_50" },
      { "expr": "SBK_Writing_mcs_75" },
      { "expr": "SBK_Writing_mcs_90" },
      { "expr": "SBK_Writing_mcs_95" },
      { "expr": "SBK_Writing_mcs_99" },
      { "expr": "SBK_Writing_mcs_99_9" },
      { "expr": "SBK_Writing_mcs_99_99" }
     ]
    },
    {
     "title": "SBK Write Percentiles (Milliseconds)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 27 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      { "expr": "SBK_Writing_ms_10" },
      { "expr": "SBK_Writing_ms_25" },
      { "expr": "SBK_Writing_ms_50" },
      { "expr": "SBK_Writing_ms_75" },
      { "expr": "SBK_Writing_ms_90" },
      { "expr": "SBK_Writing_ms_95" },
      { "expr": "SBK_Writing_ms_99" },
      { "expr": "SBK_Writing_ms_99_9" },
      { "expr": "SBK_Writing_ms_99_99" }
     ]
    },
    {
     "title": "SBK Write Avg and Max Latencies (Milliseconds)",
     "type": "stat",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Writing_ms_AvgLatency", "legendFormat": "Average Latency" },
      { "expr": "SBK_Writing_ms_MaxLatency", "legendFormat": "Max Latency" }
     ]
    }
   ]
  },
  {
   "title": "Read Performance Benchmarking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "SBK Read Throughput MB/s",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      { "expr": "SBK_Reading_MBPerSec" }
     ]
    },
    {
     "title": "SBK Read Records/Sec",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      { "expr": "SBK_Reading_RecordsPerSec" }
     ]
    },
    {
     "title": "SBK Read Avg and Max Latencies (Nanoseconds)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Reading_ns_AvgLatency", "legendFormat": "Average Latency" },
      { "expr": "SBK_Reading_ns_MaxLatency", "legendFormat": "Max Latency" }
     ]
    },
    {
     "title": "SBK Read Percentiles (Nanoseconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      { "expr": "SBK_Reading_ns_10" },
      { "expr": "SBK_Reading_ns_20" },
      { "expr": "SBK_Reading_ns_25" },
      { "expr": "SBK_Reading_ns_30" },
      { "expr": "SBK_Reading_ns_40" },
      { "expr": "SBK_Reading_ns_50" },
      { "expr": "SBK_Reading_ns_60" },
      { "expr": "SBK_Reading_ns_70" },
      { "expr": "SBK_Reading_ns_75" },
      { "expr": "SBK_Reading_ns_80" },
      { "expr": "SBK_Reading_ns_90" },
      { "expr": "SBK_Reading_ns_92_25" },
      { "expr": "SBK_Reading_ns_95" },
      { "expr": "SBK_Reading_ns_97_5" },
      { "expr": "SBK_Reading_ns_99" },
      { "expr": "SBK_Reading_ns_99_25" },
      { "expr": "SBK_Reading_ns_99_5" },
      { "expr": "SBK_Reading_ns_99_75" },
      { "expr": "SBK_Reading_ns_99_9" },
      { "expr": "SBK_Reading_ns_99_95" },
      { "expr": "SBK_Reading_ns_99_99" }
     ]
    },
    {
     "title": "SBK Readers",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Reading_Readers", "legendFormat": "Active" },
      { "expr": "SBK_Reading_Max_Readers", "legendFormat": "Max" }
     ]
    },
    {
     "title": "SBK Read Throughput MB/s",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 11, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Reading_MBPerSec" }
     ]
    },
    {
     "title": "SBK Read  Sliding Latency Coverage (SLC)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Reading_SLC_1", "legendFormat": "SLC 1" },
      { "expr": "SBK_Reading_SLC_2", "legendFormat": "SLC 2" }
     ]
    },
    {
     "title": "SBK Read Bytes Total",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Reading_Bytes_total" }
     ]
    },
    {
     "title": "SBK Read Discarded Latencies",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 11, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Reading_LowerDiscardedLatencyRecords_total",
       "legendFormat": "Lower"
      },
      {
       "expr": "SBK_Reading_HigherDiscardLatencyRecords_total",
       "legendFormat": "Higher"
      },
      {
       "expr": "SBK_Reading_InvalidLatencyRecords_total",
       "legendFormat": "Invalid/Negative"
      }
     ]
    },
    {
     "title": "SBK Read Avg and Max Latencies (Microseconds)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Reading_mcs_AvgLatency", "legendFormat": "Average Latency" },
      { "expr": "SBK_Reading_mcs_MaxLatency", "legendFormat": "Max Latency" }
     ]
    },
    {
     "title": "SBK Read Percentiles (Microseconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      { "expr": "SBK_Reading_mcs_10" },
      { "expr": "SBK_Reading_mcs_25" },
      { "expr": "SBK_Reading_mcs_50" },
      { "expr": "SBK_Reading_mcs_75" },
      { "expr": "SBK_Reading_mcs_90" },
      { "expr": "SBK_Reading_mcs_95" },
      { "expr": "SBK_Reading_mcs_99" },
      { "expr": "SBK_Reading_mcs_99_9" },
      { "expr": "SBK_Reading_mcs_99_99" }
     ]
    },
    {
     "title": "SBK Read Percentiles (Milli Seconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 31 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      { "expr": "SBK_Reading_ms_10" },
      { "expr": "SBK_Reading_ms_25" },
      { "expr": "SBK_Reading_ms_50" },
      { "expr": "SBK_Reading_ms_75" },
      { "expr": "SBK_Reading_ms_90" },
      { "expr": "SBK_Reading_ms_95" },
      { "expr": "SBK_Reading_ms_99" },
      { "expr": "SBK_Reading_ms_99_9" },
      { "expr": "SBK_Reading_ms_99_99" }
     ]
    },
    {
     "title": "SBK Read Avg and Max Latencies (Milliseconds)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Reading_ms_AvgLatency", "legendFormat": "Average Latency" },
      { "expr": "SBK_Reading_ms_MaxLatency", "legendFormat": "Max Latency" }
     ]
    }
   ]
  },
  {
   "title": "Write-Read Performance Benchmarking (End to End Latencies)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "SBK Write-Read Throughput MB/s ",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      { "expr": "SBK_Write_Reading_MBPerSec" }
     ]
    },
    {
     "title": "SBK Write-Read Records/Sec",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "SBK_Write_Reading_RecordsPerSec"
      }
     ]
    },
    {
     "title": "SBK Write-Read Avg and Max Latencies (Nanoseconds)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Write_Reading_ns_AvgLatency",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_Write_Reading_ns_MaxLatency",
       "legendFormat": "Max Latency"
      }
     ]
    },
    {
     "title": "SBK Write-Read Percentiles (Nanoseconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      { "expr": "SBK_Write_Reading_ns_10" },
      { "expr": "SBK_Write_Reading_ns_20" },
      { "expr": "SBK_Write_Reading_ns_25" },
      { "expr": "SBK_Write_Reading_ns_30" },
      { "expr": "SBK_Write_Reading_ns_40" },
      { "expr": "SBK_Write_Reading_ns_50" },
      { "expr": "SBK_Write_Reading_ns_60" },
      { "expr": "SBK_Write_Reading_ns_70" },
      { "expr": "SBK_Write_Reading_ns_75" },
      { "expr": "SBK_Write_Reading_ns_80" },
      { "expr": "SBK_Write_Reading_ns_90" },
      { "expr": "SBK_Write_Reading_ns_92_5" },
      { "expr": "SBK_Write_Reading_ns_95" },
      { "expr": "SBK_Write_Reading_ns_97_5" },
      { "expr": "SBK_Write_Reading_ns_99" },
      { "expr": "SBK_Write_Reading_ns_99_25" },
      { "expr": "SBK_Write_Reading_ns_99_5" },
      { "expr": "SBK_Write_Reading_ns_99_75" },
      { "expr": "SBK_Write_Reading_ns_99_9" },
      { "expr": "SBK_Write_Reading_ns_99_95" },
      { "expr": "SBK_Write_Reading_ns_99_99" }
     ]
    },
    {
     "title": "SBK Write-Read Bytes Total",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Write_Reading_Bytes_total" }
     ]
    },
    {
     "title": "SBK Write-Read Throughput MB/s",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 11, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Write_Reading_MBPerSec" }
     ]
    },
    {
     "title": "SBK Write-Read Sliding Latency Coverage (SLC)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Write_Reading_SLC_1", "legendFormat": "SLC 1" },
      { "expr": "SBK_Write_Reading_SLC_2", "legendFormat": "SLC 2" }
     ]
    },
    {
     "title": "SBK Write-Read  Writers and Readers",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Write_Reading_Readers", "legendFormat": "Active Readers" },
      { "expr": "SBK_Write_Reading_Max_Readers", "legendFormat": "Max Readers" },
      { "expr": "SBK_Write_Reading_Writers", "legendFormat": "Active Writers" },
      { "expr": "SBK_Write_Reading_Max_Writers", "legendFormat": "Max Writers" }
     ]
    },
    {
     "title": "SBK Write-Read  Discarded Latencies",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 11, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Write_Reading_LowerDiscardedLatencyRecords_total",
       "legendFormat": "Lower"
      },
      {
       "expr": "SBK_Write_Reading_HigherDiscardLatencyRecords_total",
       "legendFormat": "Higher"
      },
      {
       "expr": "SBK_Write_Reading_InvalidLatencyRecords_total",
       "legendFormat": "Invalid/Negative"
      }
     ]
    },
    {
     "title": "SBK Write-Read Avg and Max Latencies (Microseconds)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Write_Reading_mcs_AvgLatency",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_Write_Reading_mcs_MaxLatency",
       "legendFormat": "Max Latency"
      }
     ]
    },
    {
     "title": "SBK Write-Read Percentiles (Microseconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      { "expr": "SBK_Write_Reading_mcs_10" },
      { "expr": "SBK_Write_Reading_mcs_25" },
      { "expr": "SBK_Write_Reading_mcs_50" },
      { "expr": "SBK_Write_Reading_mcs_75" },
      { "expr": "SBK_Write_Reading_mcs_90" },
      { "expr": "SBK_Write_Reading_mcs_95" },
      { "expr": "SBK_Write_Reading_mcs_99" },
      { "expr": "SBK_Write_Reading_mcs_99_9" },
      { "expr": "SBK_Write_Reading_mcs_99_99" }
     ]
    },
    {
     "title": "SBK Write-Read Percentiles (Milliseconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 27 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      { "expr": "SBK_Write_Reading_ms_10" },
      { "expr": "SBK_Write_Reading_ms_25" },
      { "expr": "SBK_Write_Reading_ms_50" },
      { "expr": "SBK_Write_Reading_ms_75" },
      { "expr": "SBK_Write_Reading_ms_90" },
      { "expr": "SBK_Write_Reading_ms_95" },
      { "expr": "SBK_Write_Reading_ms_99" },
      { "expr": "SBK_Write_Reading_ms_99_9" },
      { "expr": "SBK_Write_Reading_ms_99_99" }
     ]
    },
    {
     "title": "SBK Write-Read Avg and Max Latencies (Milliseconds)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Write_Reading_ms_AvgLatency",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_Write_Reading_ms_MaxLatency",
       "legendFormat": "Max Latency"
      }
     ]
    }
   ]
  },
  { "title": "Write-Only Read Benchmarking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "SBK Write- Only Read Throughput MB/s ",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    { "expr": "SBK_Write_OnlyReading_MBPerSec" }
   ]
  },
  {
   "title": "SBK Write-Only Read Records/Sec",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_RecordsPerSec"
    }
   ]
  },
  {
   "title": "SBK Write-Only Read Avg and Max Latencies (Nanoseconds)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_ns_AvgLatency",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_Write_Reading_ns_MaxLatency",
     "legendFormat": "Max Latency"
    }
   ]
  },
  {
   "title": "SBK Write-Only Read Percentiles (Nanoseconds)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "SBK_Write_OnlyReading_ns_10" },
    { "expr": "SBK_Write_OnlyReading_ns_20" },
    { "expr": "SBK_Write_OnlyReading_ns_25" },
    { "expr": "SBK_Write_OnlyReading_ns_30" },
    { "expr": "SBK_Write_OnlyReading_ns_40" },
    { "expr": "SBK_Write_OnlyReading_ns_50" },
    { "expr": "SBK_Write_OnlyReading_ns_60" },
    { "expr": "SBK_Write_OnlyReading_ns_70" },
    { "expr": "SBK_Write_OnlyReading_ns_75" },
    { "expr": "SBK_Write_OnlyReading_ns_80" },
    { "expr": "SBK_Write_OnlyReading_ns_90" },
    { "expr": "SBK_Write_OnlyReading_ns_92_5" },
    { "expr": "SBK_Write_OnlyReading_ns_95" },
    { "expr": "SBK_Write_OnlyReading_ns_97_5" },
    { "expr": "SBK_Write_OnlyReading_ns_99" },
    { "expr": "SBK_Write_OnlyReading_ns_99_25" },
    { "expr": "SBK_Write_OnlyReading_ns_99_5" },
    { "expr": "SBK_Write_OnlyReading_ns_99_75" },
    { "expr": "SBK_Write_OnlyReading_ns_99_9" },
    { "expr": "SBK_Write_OnlyReading_ns_99_95" },
    { "expr": "SBK_Write_OnlyReading_ns_99_99" }
   ]
  },
  {
   "title": "SBK Write- Only Read Bytes Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_Bytes_total"
    }
   ]
  },
  {
   "title": "SBK Write-Only Read Throughput MB/s",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Write_OnlyReading_MBPerSec" }
   ]
  },
  {
   "title": "SBK Write-Only Read Sliding Latency Coverage (SLC)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Write_OnlyReading_SLC_1", "legendFormat": "SLC 1" },
    { "expr": "SBK_Write_OnlyReading_SLC_2", "legendFormat": "SLC 2" }
   ]
  },
  {
   "title": "SBK Write-Only Read  Writers and Readers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Write_OnlyReading_Readers", "legendFormat": "Active Readers" },
    {
     "expr": "SBK_Write_OnlyReading_Max_Readers",
     "legendFormat": "Max Readers"
    },
    { "expr": "SBK_Write_OnlyReading_Writers", "legendFormat": "Active Writers" },
    {
     "expr": "SBK_Write_OnlyReading_Max_Writers",
     "legendFormat": "Max Writers"
    }
   ]
  },
  {
   "title": "SBK Write-Only Read  Discarded Latencies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_LowerDiscardedLatencyRecords_total",
     "legendFormat": "Lower"
    },
    {
     "expr": "SBK_Write_OnlyReading_HigherDiscardLatencyRecords_total",
     "legendFormat": "Higher"
    },
    {
     "expr": "SBK_Write_OnlyReading_InvalidLatencyRecords_total",
     "legendFormat": "Invalid/Negative"
    }
   ]
  },
  {
   "title": "SBK Write-Only Read Avg and Max Latencies (Microseconds)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_mcs_AvgLatency",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_Write_OnlyReading_mcs_MaxLatency",
     "legendFormat": "Max Latency"
    }
   ]
  },
  {
   "title": "SBK Write - Only Read Percentiles (Microseconds)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    { "expr": "SBK_Write_OnlyReading_mcs_10" },
    { "expr": "SBK_Write_OnlyReading_mcs_25" },
    { "expr": "SBK_Write_OnlyReading_mcs_50" },
    { "expr": "SBK_Write_OnlyReading_mcs_75" },
    { "expr": "SBK_Write_OnlyReading_mcs_90" },
    { "expr": "SBK_Write_OnlyReading_mcs_95" },
    { "expr": "SBK_Write_OnlyReading_mcs_99" },
    { "expr": "SBK_Write_OnlyReading_mcs_99_9" },
    {
     "expr": "SBK_Write_OnlyReading_mcs_99_99"
    }
   ]
  },
  {
   "title": "SBK Write - Only Read Percentiles (Milliseconds)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "SBK_Write_OnlyReading_ms_10" },
    { "expr": "SBK_Write_OnlyReading_ms_25" },
    { "expr": "SBK_Write_OnlyReading_ms_50" },
    { "expr": "SBK_Write_OnlyReading_ms_75" },
    { "expr": "SBK_Write_OnlyReading_ms_90" },
    { "expr": "SBK_Write_OnlyReading_ms_95" },
    { "expr": "SBK_Write_OnlyReading_ms_99" },
    { "expr": "SBK_Write_OnlyReading_ms_99_9" },
    { "expr": "SBK_Write_OnlyReading_ms_99_99" }
   ]
  },
  {
   "title": "SBK Write- Only Read Avg and Max Latencies (Milliseconds)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_ms_AvgLatency",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_Write_OnlyReading_ms_MaxLatency",
     "legendFormat": "Max Latency"
    }
   ]
  }
 ]
}