{
 "title": "SBK SBK@2020 Benchmark",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "SBK@2020 Write Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_SBK@2020_Writing_MBPerSec" }
   ]
  },
  {
   "title": "SBK@2020 Writing Records/Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_SBK@2020_Writing_RecordsPerSec"
    }
   ]
  },
  {
   "title": "SBK@2020 Writing Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_SBK@2020_Writing_ms_10" },
    { "expr": "SBK_SBK@2020_Writing_ms_25" },
    { "expr": "SBK_SBK@2020_Writing_ms_50" },
    { "expr": "SBK_SBK@2020_Writing_ms_75" },
    { "expr": "SBK_SBK@2020_Writing_ms_90" },
    { "expr": "SBK_SBK@2020_Writing_ms_95" },
    { "expr": "SBK_SBK@2020_Writing_ms_99" },
    { "expr": "SBK_SBK@2020_Writing_ms_99_9" },
    { "expr": "SBK_SBK@2020_Writing_ms_99_99" }
   ]
  },
  {
   "title": "SBK@2020 Writing Avg and Max Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_SBK@2020_Writing_ms_AvgLatency"
    },
    {
     "expr": "SBK_SBK@2020_Writing_ms_MaxLatency"
    }
   ]
  },
  {
   "title": "SBK@2020 Writers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_SBK@2020_Writing_Writers" }
   ]
  },
  {
   "title": "SBK@2020 Write Bytes Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_SBK@2020_Writing_Records_total"
    }
   ]
  },
  {
   "title": "SBK@2020 Read Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_SBK@2020_Reading_MBPerSec" }
   ]
  },
  {
   "title": "SBK@2020 Read Records/Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_SBK@2020_Reading_RecordsPerSec"
    }
   ]
  },
  {
   "title": "SBK@2020 Reading Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_SBK@2020_Reading_ms_10" },
    { "expr": "SBK_SBK@2020_Reading_ms_25" },
    { "expr": "SBK_SBK@2020_Reading_ms_50" },
    { "expr": "SBK_SBK@2020_Reading_ms_75" },
    { "expr": "SBK_SBK@2020_Reading_ms_90" },
    { "expr": "SBK_SBK@2020_Reading_ms_95" },
    { "expr": "SBK_SBK@2020_Reading_ms_99" },
    { "expr": "SBK_SBK@2020_Reading_ms_99_9" },
    { "expr": "SBK_SBK@2020_Reading_ms_99_99" }
   ]
  },
  {
   "title": "SBK@2020 Reading  Avg and Max Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_SBK@2020_Reading_ms_AvgLatency"
    },
    {
     "expr": "SBK_SBK@2020_Reading_ms_MaxLatency"
    }
   ]
  },
  {
   "title": "SBK@2020 Readers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_SBK@2020_Reading_Readers" }
   ]
  },
  {
   "title": "SBK@2020 Read Bytes Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_SBK@2020_Reading_Bytes_total"
    }
   ]
  },
  {
   "title": "SBK@2020 Writing Discarded Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_SBK@2020_Writing_LowerDiscardedLatencyRecords_total"
    },
    {
     "expr": "SBK_SBK@2020_Writing_HigherDiscardLatencyRecords_total"
    }
   ]
  },
  {
   "title": "SBK@2020 Reading Discarded Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_SBK@2020_Reading_LowerDiscardedLatencyRecords_total"
    },
    {
     "expr": "SBK_SBK@2020_Reading_HigherDiscardLatencyRecords_total"
    }
   ]
  }
 ]
}