{
 "title": "SBK BOOKKEEPER Benchmark",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "BOOKKEEPER Write Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_BOOKKEEPER_Writing_MBPerSec"
    }
   ]
  },
  {
   "title": "BOOKKEEPER Writing Records/Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_BOOKKEEPER_Writing_RecordsPerSec"
    }
   ]
  },
  {
   "title": "BOOKKEEPER Writing Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_BOOKKEEPER_Writing_ms_10" },
    { "expr": "SBK_BOOKKEEPER_Writing_ms_25" },
    { "expr": "SBK_BOOKKEEPER_Writing_ms_50" },
    { "expr": "SBK_BOOKKEEPER_Writing_ms_75" },
    { "expr": "SBK_BOOKKEEPER_Writing_ms_90" },
    { "expr": "SBK_BOOKKEEPER_Writing_ms_95" },
    { "expr": "SBK_BOOKKEEPER_Writing_ms_99" },
    { "expr": "SBK_BOOKKEEPER_Writing_ms_99_9" },
    {
     "expr": "SBK_BOOKKEEPER_Writing_ms_99_99"
    }
   ]
  },
  {
   "title": "BOOKKEEPER Writing Avg and Max Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_BOOKKEEPER_Writing_ms_AvgLatency"
    },
    {
     "expr": "SBK_BOOKKEEPER_Writing_ms_MaxLatency"
    }
   ]
  },
  {
   "title": "BOOKKEEPER Writers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_BOOKKEEPER_Writing_Writers" }
   ]
  },
  {
   "title": "BOOKKEEPER Write Bytes Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_BOOKKEEPER_Writing_Records_total"
    }
   ]
  },
  {
   "title": "BOOKKEEPER Read Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_BOOKKEEPER_Reading_MBPerSec"
    }
   ]
  },
  {
   "title": "BOOKKEEPER Read Records/Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_BOOKKEEPER_Reading_RecordsPerSec"
    }
   ]
  },
  {
   "title": "BOOKKEEPER Reading Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_BOOKKEEPER_Reading_ms_10" },
    { "expr": "SBK_BOOKKEEPER_Reading_ms_25" },
    { "expr": "SBK_BOOKKEEPER_Reading_ms_50" },
    { "expr": "SBK_BOOKKEEPER_Reading_ms_75" },
    { "expr": "SBK_BOOKKEEPER_Reading_ms_90" },
    { "expr": "SBK_BOOKKEEPER_Reading_ms_95" },
    { "expr": "SBK_BOOKKEEPER_Reading_ms_99" },
    { "expr": "SBK_BOOKKEEPER_Reading_ms_99_9" },
    {
     "expr": "SBK_BOOKKEEPER_Reading_ms_99_99"
    }
   ]
  },
  {
   "title": "BOOKKEEPER Reading  Avg and Max Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_BOOKKEEPER_Reading_ms_AvgLatency"
    },
    {
     "expr": "SBK_BOOKKEEPER_Reading_ms_MaxLatency"
    }
   ]
  },
  {
   "title": "BOOKKEEPER Readers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_BOOKKEEPER_Reading_Readers" }
   ]
  },
  {
   "title": "BOOKKEEPER Read Bytes Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_BOOKKEEPER_Reading_Bytes_total"
    }
   ]
  },
  {
   "title": "BOOKKEEPER Writing Discarded Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_BOOKKEEPER_Writing_LowerDiscardedLatencyRecords_total"
    },
    {
     "expr": "SBK_BOOKKEEPER_Writing_HigherDiscardLatencyRecords_total"
    }
   ]
  },
  {
   "title": "BOOKKEEPER Reading Discarded Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_BOOKKEEPER_Reading_LowerDiscardedLatencyRecords_total"
    },
    {
     "expr": "SBK_BOOKKEEPER_Reading_HigherDiscardLatencyRecords_total"
    }
   ]
  }
 ]
}