{
 "title": "SBK PRAVEGA Benchmark",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "PRAVEGA Write Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_PRAVEGA_Writing_MBPerSec" }
   ]
  },
  {
   "title": "PRAVEGA Writing Records/Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Writing_RecordsPerSec"
    }
   ]
  },
  {
   "title": "PRAVEGA Writing Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_PRAVEGA_Writing_ms_10" },
    { "expr": "SBK_PRAVEGA_Writing_ms_25" },
    { "expr": "SBK_PRAVEGA_Writing_ms_50" },
    { "expr": "SBK_PRAVEGA_Writing_ms_75" },
    { "expr": "SBK_PRAVEGA_Writing_ms_90" },
    { "expr": "SBK_PRAVEGA_Writing_ms_95" },
    { "expr": "SBK_PRAVEGA_Writing_ms_99" },
    { "expr": "SBK_PRAVEGA_Writing_ms_99_9" },
    { "expr": "SBK_PRAVEGA_Writing_ms_99_99" }
   ]
  },
  {
   "title": "PRAVEGA Writing Avg and Max Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Writing_ms_AvgLatency"
    },
    {
     "expr": "SBK_PRAVEGA_Writing_ms_MaxLatency"
    }
   ]
  },
  {
   "title": "PRAVEGA Writers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_PRAVEGA_Writing_Writers" }
   ]
  },
  {
   "title": "PRAVEGA Write Bytes Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Writing_Records_total"
    }
   ]
  },
  {
   "title": "PRAVEGA Read Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_PRAVEGA_Reading_MBPerSec" }
   ]
  },
  {
   "title": "PRAVEGA Read Records/Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Reading_RecordsPerSec"
    }
   ]
  },
  {
   "title": "PRAVEGA Reading Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_PRAVEGA_Reading_ms_10" },
    { "expr": "SBK_PRAVEGA_Reading_ms_25" },
    { "expr": "SBK_PRAVEGA_Reading_ms_50" },
    { "expr": "SBK_PRAVEGA_Reading_ms_75" },
    { "expr": "SBK_PRAVEGA_Reading_ms_90" },
    { "expr": "SBK_PRAVEGA_Reading_ms_95" },
    { "expr": "SBK_PRAVEGA_Reading_ms_99" },
    { "expr": "SBK_PRAVEGA_Reading_ms_99_9" },
    { "expr": "SBK_PRAVEGA_Reading_ms_99_99" }
   ]
  },
  {
   "title": "PRAVEGA Reading  Avg and Max Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Reading_ms_AvgLatency"
    },
    {
     "expr": "SBK_PRAVEGA_Reading_ms_MaxLatency"
    }
   ]
  },
  {
   "title": "PRAVEGA Readers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_PRAVEGA_Reading_Readers" }
   ]
  },
  {
   "title": "PRAVEGA Read Bytes Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Reading_Bytes_total"
    }
   ]
  },
  {
   "title": "PRAVEGA Writing Discarded Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Writing_LowerDiscardedLatencyRecords_total"
    },
    {
     "expr": "SBK_PRAVEGA_Writing_HigherDiscardLatencyRecords_total"
    }
   ]
  },
  {
   "title": "PRAVEGA Reading Discarded Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Reading_LowerDiscardedLatencyRecords_total"
    },
    {
     "expr": "SBK_PRAVEGA_Reading_HigherDiscardLatencyRecords_total"
    }
   ]
  }
 ]
}