{
 "title": "SBK FILESTREAM Benchmark",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "FILESTREAM Write Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_FILESTREAM_Writing_MBPerSec"
    }
   ]
  },
  {
   "title": "FILESTREAM Writing Records/Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_FILESTREAM_Writing_RecordsPerSec"
    }
   ]
  },
  {
   "title": "FILESTREAM Writing Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_FILESTREAM_Writing_ms_10" },
    { "expr": "SBK_FILESTREAM_Writing_ms_25" },
    { "expr": "SBK_FILESTREAM_Writing_ms_50" },
    { "expr": "SBK_FILESTREAM_Writing_ms_75" },
    { "expr": "SBK_FILESTREAM_Writing_ms_90" },
    { "expr": "SBK_FILESTREAM_Writing_ms_95" },
    { "expr": "SBK_FILESTREAM_Writing_ms_99" },
    { "expr": "SBK_FILESTREAM_Writing_ms_99_9" },
    {
     "expr": "SBK_FILESTREAM_Writing_ms_99_99"
    }
   ]
  },
  {
   "title": "FILESTREAM Writing Avg and Max Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_FILESTREAM_Writing_ms_AvgLatency"
    },
    {
     "expr": "SBK_FILESTREAM_Writing_ms_MaxLatency"
    }
   ]
  },
  {
   "title": "FILESTREAM Writers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_FILESTREAM_Writing_Writers" }
   ]
  },
  {
   "title": "FILESTREAM Write Bytes Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_FILESTREAM_Writing_Records_total"
    }
   ]
  },
  {
   "title": "FILESTREAM Read Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_FILESTREAM_Reading_MBPerSec"
    }
   ]
  },
  {
   "title": "FILESTREAM Read Records/Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_FILESTREAM_Reading_RecordsPerSec"
    }
   ]
  },
  {
   "title": "FILESTREAM Reading Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_FILESTREAM_Reading_ms_10" },
    { "expr": "SBK_FILESTREAM_Reading_ms_25" },
    { "expr": "SBK_FILESTREAM_Reading_ms_50" },
    { "expr": "SBK_FILESTREAM_Reading_ms_75" },
    { "expr": "SBK_FILESTREAM_Reading_ms_90" },
    { "expr": "SBK_FILESTREAM_Reading_ms_95" },
    { "expr": "SBK_FILESTREAM_Reading_ms_99" },
    { "expr": "SBK_FILESTREAM_Reading_ms_99_9" },
    {
     "expr": "SBK_FILESTREAM_Reading_ms_99_99"
    }
   ]
  },
  {
   "title": "FILESTREAM Reading  Avg and Max Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_FILESTREAM_Reading_ms_AvgLatency"
    },
    {
     "expr": "SBK_FILESTREAM_Reading_ms_MaxLatency"
    }
   ]
  },
  {
   "title": "FILESTREAM Readers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_FILESTREAM_Reading_Readers" }
   ]
  },
  {
   "title": "FILESTREAM Read Bytes Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_FILESTREAM_Reading_Bytes_total"
    }
   ]
  },
  {
   "title": "FILESTREAM Writing Discarded Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_FILESTREAM_Writing_LowerDiscardedLatencyRecords_total"
    },
    {
     "expr": "SBK_FILESTREAM_Writing_HigherDiscardLatencyRecords_total"
    }
   ]
  },
  {
   "title": "FILESTREAM Reading Discarded Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_FILESTREAM_Reading_LowerDiscardedLatencyRecords_total"
    },
    {
     "expr": "SBK_FILESTREAM_Reading_HigherDiscardLatencyRecords_total"
    }
   ]
  }
 ]
}