{
 "title": "SBK JDBC Benchmark",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "JDBC Write Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_JDBC_Writing_MBPerSec" }
   ]
  },
  {
   "title": "JDBC Writing Records/Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_JDBC_Writing_RecordsPerSec" }
   ]
  },
  {
   "title": "JDBC Writing Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_JDBC_Writing_ms_10" },
    { "expr": "SBK_JDBC_Writing_ms_25" },
    { "expr": "SBK_JDBC_Writing_ms_50" },
    { "expr": "SBK_JDBC_Writing_ms_75" },
    { "expr": "SBK_JDBC_Writing_ms_90" },
    { "expr": "SBK_JDBC_Writing_ms_95" },
    { "expr": "SBK_JDBC_Writing_ms_99" },
    { "expr": "SBK_JDBC_Writing_ms_99_9" },
    { "expr": "SBK_JDBC_Writing_ms_99_99" }
   ]
  },
  {
   "title": "JDBC Writing Avg and Max Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_JDBC_Writing_ms_AvgLatency" },
    { "expr": "SBK_JDBC_Writing_ms_MaxLatency" }
   ]
  },
  {
   "title": "JDBC Writers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_JDBC_Writing_Writers" }
   ]
  },
  {
   "title": "JDBC Write Bytes Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_JDBC_Writing_Records_total" }
   ]
  },
  {
   "title": "JDBC Read Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_JDBC_Reading_MBPerSec" }
   ]
  },
  {
   "title": "JDBC Read Records/Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_JDBC_Reading_RecordsPerSec" }
   ]
  },
  {
   "title": "JDBC Reading Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_JDBC_Reading_ms_10" },
    { "expr": "SBK_JDBC_Reading_ms_25" },
    { "expr": "SBK_JDBC_Reading_ms_50" },
    { "expr": "SBK_JDBC_Reading_ms_75" },
    { "expr": "SBK_JDBC_Reading_ms_90" },
    { "expr": "SBK_JDBC_Reading_ms_95" },
    { "expr": "SBK_JDBC_Reading_ms_99" },
    { "expr": "SBK_JDBC_Reading_ms_99_9" },
    { "expr": "SBK_JDBC_Reading_ms_99_99" }
   ]
  },
  {
   "title": "JDBC Reading  Avg and Max Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_JDBC_Reading_ms_AvgLatency" },
    { "expr": "SBK_JDBC_Reading_ms_MaxLatency" }
   ]
  },
  {
   "title": "JDBC Readers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_JDBC_Reading_Readers" }
   ]
  },
  {
   "title": "JDBC Read Bytes Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_JDBC_Reading_Bytes_total" }
   ]
  },
  {
   "title": "JDBC Writing Discarded Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_JDBC_Writing_LowerDiscardedLatencyRecords_total"
    },
    {
     "expr": "SBK_JDBC_Writing_HigherDiscardLatencyRecords_total"
    }
   ]
  },
  {
   "title": "JDBC Reading Discarded Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_JDBC_Reading_LowerDiscardedLatencyRecords_total"
    },
    {
     "expr": "SBK_JDBC_Reading_HigherDiscardLatencyRecords_total"
    }
   ]
  }
 ]
}