{
 "title": "SBK RABBITMQ Benchmark",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RABBITMQ Write Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_RABBITMQ_Writing_MBPerSec" }
   ]
  },
  {
   "title": "RABBITMQ Writing Records/Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_RABBITMQ_Writing_RecordsPerSec"
    }
   ]
  },
  {
   "title": "RABBITMQ Writing Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_RABBITMQ_Writing_ms_10" },
    { "expr": "SBK_RABBITMQ_Writing_ms_25" },
    { "expr": "SBK_RABBITMQ_Writing_ms_50" },
    { "expr": "SBK_RABBITMQ_Writing_ms_75" },
    { "expr": "SBK_RABBITMQ_Writing_ms_90" },
    { "expr": "SBK_RABBITMQ_Writing_ms_95" },
    { "expr": "SBK_RABBITMQ_Writing_ms_99" },
    { "expr": "SBK_RABBITMQ_Writing_ms_99_9" },
    { "expr": "SBK_RABBITMQ_Writing_ms_99_99" }
   ]
  },
  {
   "title": "RABBITMQ Writing Avg and Max Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_RABBITMQ_Writing_ms_AvgLatency"
    },
    {
     "expr": "SBK_RABBITMQ_Writing_ms_MaxLatency"
    }
   ]
  },
  {
   "title": "RABBITMQ Writers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_RABBITMQ_Writing_Writers" }
   ]
  },
  {
   "title": "RABBITMQ Write Bytes Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_RABBITMQ_Writing_Records_total"
    }
   ]
  },
  {
   "title": "RABBITMQ Read Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_RABBITMQ_Reading_MBPerSec" }
   ]
  },
  {
   "title": "RABBITMQ Read Records/Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_RABBITMQ_Reading_RecordsPerSec"
    }
   ]
  },
  {
   "title": "RABBITMQ Reading Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_RABBITMQ_Reading_ms_10" },
    { "expr": "SBK_RABBITMQ_Reading_ms_25" },
    { "expr": "SBK_RABBITMQ_Reading_ms_50" },
    { "expr": "SBK_RABBITMQ_Reading_ms_75" },
    { "expr": "SBK_RABBITMQ_Reading_ms_90" },
    { "expr": "SBK_RABBITMQ_Reading_ms_95" },
    { "expr": "SBK_RABBITMQ_Reading_ms_99" },
    { "expr": "SBK_RABBITMQ_Reading_ms_99_9" },
    { "expr": "SBK_RABBITMQ_Reading_ms_99_99" }
   ]
  },
  {
   "title": "RABBITMQ Reading  Avg and Max Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_RABBITMQ_Reading_ms_AvgLatency"
    },
    {
     "expr": "SBK_RABBITMQ_Reading_ms_MaxLatency"
    }
   ]
  },
  {
   "title": "RABBITMQ Readers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_RABBITMQ_Reading_Readers" }
   ]
  },
  {
   "title": "RABBITMQ Read Bytes Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_RABBITMQ_Reading_Bytes_total"
    }
   ]
  },
  {
   "title": "RABBITMQ Writing Discarded Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_RABBITMQ_Writing_LowerDiscardedLatencyRecords_total"
    },
    {
     "expr": "SBK_RABBITMQ_Writing_HigherDiscardLatencyRecords_total"
    }
   ]
  },
  {
   "title": "RABBITMQ Reading Discarded Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_RABBITMQ_Reading_LowerDiscardedLatencyRecords_total"
    },
    {
     "expr": "SBK_RABBITMQ_Reading_HigherDiscardLatencyRecords_total"
    }
   ]
  }
 ]
}