{
 "title": "SBK NULL Benchmark",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "NULL Write Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_NULL_Writing_MBPerSec" }
   ]
  },
  {
   "title": "NULL Writing Records/Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_NULL_Writing_RecordsPerSec" }
   ]
  },
  {
   "title": "NULL Writing Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_NULL_Writing_ms_10" },
    { "expr": "SBK_NULL_Writing_ms_25" },
    { "expr": "SBK_NULL_Writing_ms_50" },
    { "expr": "SBK_NULL_Writing_ms_75" },
    { "expr": "SBK_NULL_Writing_ms_90" },
    { "expr": "SBK_NULL_Writing_ms_95" },
    { "expr": "SBK_NULL_Writing_ms_99" },
    { "expr": "SBK_NULL_Writing_ms_99_9" },
    { "expr": "SBK_NULL_Writing_ms_99_99" }
   ]
  },
  {
   "title": "NULL Writing Avg and Max Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_NULL_Writing_ms_AvgLatency" },
    { "expr": "SBK_NULL_Writing_ms_MaxLatency" }
   ]
  },
  {
   "title": "NULL Writers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_NULL_Writing_Writers" }
   ]
  },
  {
   "title": "NULL Write Bytes Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_NULL_Writing_Records_total" }
   ]
  },
  {
   "title": "NULL Read Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_NULL_Reading_MBPerSec" }
   ]
  },
  {
   "title": "NULL Read Records/Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_NULL_Reading_RecordsPerSec" }
   ]
  },
  {
   "title": "NULL Reading Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_NULL_Reading_ms_10" },
    { "expr": "SBK_NULL_Reading_ms_25" },
    { "expr": "SBK_NULL_Reading_ms_50" },
    { "expr": "SBK_NULL_Reading_ms_75" },
    { "expr": "SBK_NULL_Reading_ms_90" },
    { "expr": "SBK_NULL_Reading_ms_95" },
    { "expr": "SBK_NULL_Reading_ms_99" },
    { "expr": "SBK_NULL_Reading_ms_99_9" },
    { "expr": "SBK_NULL_Reading_ms_99_99" }
   ]
  },
  {
   "title": "NULL Reading  Avg and Max Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_NULL_Reading_ms_AvgLatency" },
    { "expr": "SBK_NULL_Reading_ms_MaxLatency" }
   ]
  },
  {
   "title": "NULL Readers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_NULL_Reading_Readers" }
   ]
  },
  {
   "title": "NULL Read Bytes Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_NULL_Reading_Bytes_total" }
   ]
  },
  {
   "title": "NULL Writing Discarded Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_NULL_Writing_LowerDiscardedLatencyRecords_total"
    },
    {
     "expr": "SBK_NULL_Writing_HigherDiscardLatencyRecords_total"
    }
   ]
  },
  {
   "title": "NULL Reading Discarded Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_NULL_Reading_LowerDiscardedLatencyRecords_total"
    },
    {
     "expr": "SBK_NULL_Reading_HigherDiscardLatencyRecords_total"
    }
   ]
  }
 ]
}