{
 "title": "SBK KAFKA Benchmark",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "KAFKA Write Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_KAFKA_Writing_MBPerSec" }
   ]
  },
  {
   "title": "KAFKA Writing Records/Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_KAFKA_Writing_RecordsPerSec"
    }
   ]
  },
  {
   "title": "KAFKA Writing Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_KAFKA_Writing_ms_10" },
    { "expr": "SBK_KAFKA_Writing_ms_25" },
    { "expr": "SBK_KAFKA_Writing_ms_50" },
    { "expr": "SBK_KAFKA_Writing_ms_75" },
    { "expr": "SBK_KAFKA_Writing_ms_90" },
    { "expr": "SBK_KAFKA_Writing_ms_95" },
    { "expr": "SBK_KAFKA_Writing_ms_99" },
    { "expr": "SBK_KAFKA_Writing_ms_99_9" },
    { "expr": "SBK_KAFKA_Writing_ms_99_99" }
   ]
  },
  {
   "title": "KAFKA Writing Avg and Max Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_KAFKA_Writing_ms_AvgLatency"
    },
    {
     "expr": "SBK_KAFKA_Writing_ms_MaxLatency"
    }
   ]
  },
  {
   "title": "KAFKA Writers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_KAFKA_Writing_Writers" }
   ]
  },
  {
   "title": "KAFKA Write Bytes Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_KAFKA_Writing_Records_total"
    }
   ]
  },
  {
   "title": "KAFKA Read Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_KAFKA_Reading_MBPerSec" }
   ]
  },
  {
   "title": "KAFKA Read Records/Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_KAFKA_Reading_RecordsPerSec"
    }
   ]
  },
  {
   "title": "KAFKA Reading Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_KAFKA_Reading_ms_10" },
    { "expr": "SBK_KAFKA_Reading_ms_25" },
    { "expr": "SBK_KAFKA_Reading_ms_50" },
    { "expr": "SBK_KAFKA_Reading_ms_75" },
    { "expr": "SBK_KAFKA_Reading_ms_90" },
    { "expr": "SBK_KAFKA_Reading_ms_95" },
    { "expr": "SBK_KAFKA_Reading_ms_99" },
    { "expr": "SBK_KAFKA_Reading_ms_99_9" },
    { "expr": "SBK_KAFKA_Reading_ms_99_99" }
   ]
  },
  {
   "title": "KAFKA Reading  Avg and Max Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_KAFKA_Reading_ms_AvgLatency"
    },
    {
     "expr": "SBK_KAFKA_Reading_ms_MaxLatency"
    }
   ]
  },
  {
   "title": "KAFKA Readers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_KAFKA_Reading_Readers" }
   ]
  },
  {
   "title": "KAFKA Read Bytes Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_KAFKA_Reading_Bytes_total" }
   ]
  },
  {
   "title": "KAFKA Writing Discarded Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_KAFKA_Writing_LowerDiscardedLatencyRecords_total"
    },
    {
     "expr": "SBK_KAFKA_Writing_HigherDiscardLatencyRecords_total"
    }
   ]
  },
  {
   "title": "KAFKA Reading Discarded Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_KAFKA_Reading_LowerDiscardedLatencyRecords_total"
    },
    {
     "expr": "SBK_KAFKA_Reading_HigherDiscardLatencyRecords_total"
    }
   ]
  }
 ]
}