{
 "title": "SBK MINIO Benchmark",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "MINIO Write Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_MINIO_Writing_MBPerSec" }
   ]
  },
  {
   "title": "MINIO Writing Records/Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_MINIO_Writing_RecordsPerSec"
    }
   ]
  },
  {
   "title": "MINIO Writing Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_MINIO_Writing_ms_10" },
    { "expr": "SBK_MINIO_Writing_ms_25" },
    { "expr": "SBK_MINIO_Writing_ms_50" },
    { "expr": "SBK_MINIO_Writing_ms_75" },
    { "expr": "SBK_MINIO_Writing_ms_90" },
    { "expr": "SBK_MINIO_Writing_ms_95" },
    { "expr": "SBK_MINIO_Writing_ms_99" },
    { "expr": "SBK_MINIO_Writing_ms_99_9" },
    { "expr": "SBK_MINIO_Writing_ms_99_99" }
   ]
  },
  {
   "title": "MINIO Writing Avg and Max Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_MINIO_Writing_ms_AvgLatency"
    },
    {
     "expr": "SBK_MINIO_Writing_ms_MaxLatency"
    }
   ]
  },
  {
   "title": "MINIO Writers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_MINIO_Writing_Writers" }
   ]
  },
  {
   "title": "MINIO Write Bytes Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_MINIO_Writing_Records_total"
    }
   ]
  },
  {
   "title": "MINIO Read Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_MINIO_Reading_MBPerSec" }
   ]
  },
  {
   "title": "MINIO Read Records/Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_MINIO_Reading_RecordsPerSec"
    }
   ]
  },
  {
   "title": "MINIO Reading Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_MINIO_Reading_ms_10" },
    { "expr": "SBK_MINIO_Reading_ms_25" },
    { "expr": "SBK_MINIO_Reading_ms_50" },
    { "expr": "SBK_MINIO_Reading_ms_75" },
    { "expr": "SBK_MINIO_Reading_ms_90" },
    { "expr": "SBK_MINIO_Reading_ms_95" },
    { "expr": "SBK_MINIO_Reading_ms_99" },
    { "expr": "SBK_MINIO_Reading_ms_99_9" },
    { "expr": "SBK_MINIO_Reading_ms_99_99" }
   ]
  },
  {
   "title": "MINIO Reading  Avg and Max Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_MINIO_Reading_ms_AvgLatency"
    },
    {
     "expr": "SBK_MINIO_Reading_ms_MaxLatency"
    }
   ]
  },
  {
   "title": "MINIO Readers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_MINIO_Reading_Readers" }
   ]
  },
  {
   "title": "MINIO Read Bytes Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_MINIO_Reading_Bytes_total" }
   ]
  },
  {
   "title": "MINIO Writing Discarded Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_MINIO_Writing_LowerDiscardedLatencyRecords_total"
    },
    {
     "expr": "SBK_MINIO_Writing_HigherDiscardLatencyRecords_total"
    }
   ]
  },
  {
   "title": "MINIO Reading Discarded Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_MINIO_Reading_LowerDiscardedLatencyRecords_total"
    },
    {
     "expr": "SBK_MINIO_Reading_HigherDiscardLatencyRecords_total"
    }
   ]
  }
 ]
}