{
 "title": "SBK FOUNDATIONDB Benchmark",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "FOUNDATIONDB Write Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_FOUNDATIONDB_Writing_MBPerSec"
    }
   ]
  },
  {
   "title": "FOUNDATIONDB Writing Records/Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_FOUNDATIONDB_Writing_RecordsPerSec"
    }
   ]
  },
  {
   "title": "FOUNDATIONDB Writing Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_FOUNDATIONDB_Writing_ms_10" },
    { "expr": "SBK_FOUNDATIONDB_Writing_ms_25" },
    { "expr": "SBK_FOUNDATIONDB_Writing_ms_50" },
    { "expr": "SBK_FOUNDATIONDB_Writing_ms_75" },
    { "expr": "SBK_FOUNDATIONDB_Writing_ms_90" },
    { "expr": "SBK_FOUNDATIONDB_Writing_ms_95" },
    { "expr": "SBK_FOUNDATIONDB_Writing_ms_99" },
    {
     "expr": "SBK_FOUNDATIONDB_Writing_ms_99_9"
    },
    {
     "expr": "SBK_FOUNDATIONDB_Writing_ms_99_99"
    }
   ]
  },
  {
   "title": "FOUNDATIONDB Writing Avg and Max Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_FOUNDATIONDB_Writing_ms_AvgLatency"
    },
    {
     "expr": "SBK_FOUNDATIONDB_Writing_ms_MaxLatency"
    }
   ]
  },
  {
   "title": "FOUNDATIONDB Writers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_FOUNDATIONDB_Writing_Writers"
    }
   ]
  },
  {
   "title": "FOUNDATIONDB Write Bytes Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_FOUNDATIONDB_Writing_Records_total"
    }
   ]
  },
  {
   "title": "FOUNDATIONDB Read Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_FOUNDATIONDB_Reading_MBPerSec"
    }
   ]
  },
  {
   "title": "FOUNDATIONDB Read Records/Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_FOUNDATIONDB_Reading_RecordsPerSec"
    }
   ]
  },
  {
   "title": "FOUNDATIONDB Reading Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_FOUNDATIONDB_Reading_ms_10" },
    { "expr": "SBK_FOUNDATIONDB_Reading_ms_25" },
    { "expr": "SBK_FOUNDATIONDB_Reading_ms_50" },
    { "expr": "SBK_FOUNDATIONDB_Reading_ms_75" },
    { "expr": "SBK_FOUNDATIONDB_Reading_ms_90" },
    { "expr": "SBK_FOUNDATIONDB_Reading_ms_95" },
    { "expr": "SBK_FOUNDATIONDB_Reading_ms_99" },
    {
     "expr": "SBK_FOUNDATIONDB_Reading_ms_99_9"
    },
    {
     "expr": "SBK_FOUNDATIONDB_Reading_ms_99_99"
    }
   ]
  },
  {
   "title": "FOUNDATIONDB Reading  Avg and Max Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_FOUNDATIONDB_Reading_ms_AvgLatency"
    },
    {
     "expr": "SBK_FOUNDATIONDB_Reading_ms_MaxLatency"
    }
   ]
  },
  {
   "title": "FOUNDATIONDB Readers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_FOUNDATIONDB_Reading_Readers"
    }
   ]
  },
  {
   "title": "FOUNDATIONDB Read Bytes Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_FOUNDATIONDB_Reading_Bytes_total"
    }
   ]
  },
  {
   "title": "FOUNDATIONDB Writing Discarded Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_FOUNDATIONDB_Writing_LowerDiscardedLatencyRecords_total"
    },
    {
     "expr": "SBK_FOUNDATIONDB_Writing_HigherDiscardLatencyRecords_total"
    }
   ]
  },
  {
   "title": "FOUNDATIONDB Reading Discarded Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_FOUNDATIONDB_Reading_LowerDiscardedLatencyRecords_total"
    },
    {
     "expr": "SBK_FOUNDATIONDB_Reading_HigherDiscardLatencyRecords_total"
    }
   ]
  }
 ]
}