{
 "title": "SBK IGNITE Benchmark",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "IGNITE Write Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_IGNITE_Writing_MBPerSec" }
   ]
  },
  {
   "title": "IGNITE Writing Records/Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_IGNITE_Writing_RecordsPerSec"
    }
   ]
  },
  {
   "title": "IGNITE Writing Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_IGNITE_Writing_ms_10" },
    { "expr": "SBK_IGNITE_Writing_ms_25" },
    { "expr": "SBK_IGNITE_Writing_ms_50" },
    { "expr": "SBK_IGNITE_Writing_ms_75" },
    { "expr": "SBK_IGNITE_Writing_ms_90" },
    { "expr": "SBK_IGNITE_Writing_ms_95" },
    { "expr": "SBK_IGNITE_Writing_ms_99" },
    { "expr": "SBK_IGNITE_Writing_ms_99_9" },
    { "expr": "SBK_IGNITE_Writing_ms_99_99" }
   ]
  },
  {
   "title": "IGNITE Writing Avg and Max Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_IGNITE_Writing_ms_AvgLatency"
    },
    {
     "expr": "SBK_IGNITE_Writing_ms_MaxLatency"
    }
   ]
  },
  {
   "title": "IGNITE Writers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_IGNITE_Writing_Writers" }
   ]
  },
  {
   "title": "IGNITE Write Bytes Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_IGNITE_Writing_Records_total"
    }
   ]
  },
  {
   "title": "IGNITE Read Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_IGNITE_Reading_MBPerSec" }
   ]
  },
  {
   "title": "IGNITE Read Records/Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_IGNITE_Reading_RecordsPerSec"
    }
   ]
  },
  {
   "title": "IGNITE Reading Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_IGNITE_Reading_ms_10" },
    { "expr": "SBK_IGNITE_Reading_ms_25" },
    { "expr": "SBK_IGNITE_Reading_ms_50" },
    { "expr": "SBK_IGNITE_Reading_ms_75" },
    { "expr": "SBK_IGNITE_Reading_ms_90" },
    { "expr": "SBK_IGNITE_Reading_ms_95" },
    { "expr": "SBK_IGNITE_Reading_ms_99" },
    { "expr": "SBK_IGNITE_Reading_ms_99_9" },
    { "expr": "SBK_IGNITE_Reading_ms_99_99" }
   ]
  },
  {
   "title": "IGNITE Reading  Avg and Max Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_IGNITE_Reading_ms_AvgLatency"
    },
    {
     "expr": "SBK_IGNITE_Reading_ms_MaxLatency"
    }
   ]
  },
  {
   "title": "IGNITE Readers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_IGNITE_Reading_Readers" }
   ]
  },
  {
   "title": "IGNITE Read Bytes Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_IGNITE_Reading_Bytes_total" }
   ]
  },
  {
   "title": "IGNITE Writing Discarded Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_IGNITE_Writing_LowerDiscardedLatencyRecords_total"
    },
    {
     "expr": "SBK_IGNITE_Writing_HigherDiscardLatencyRecords_total"
    }
   ]
  },
  {
   "title": "IGNITE Reading Discarded Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_IGNITE_Reading_LowerDiscardedLatencyRecords_total"
    },
    {
     "expr": "SBK_IGNITE_Reading_HigherDiscardLatencyRecords_total"
    }
   ]
  }
 ]
}