{
 "title": "SBK Dashboard",
 "tags": [ "SBK" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "SBK Driver",
   "type": "stat",
   "description": "Storage System / Class Name",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Readers", "legendFormat": "Active" }
   ]
  },
  { "title": "SBK Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Connections", "legendFormat": "Active" }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Max_Connections", "legendFormat": "Active" }
   ]
  },
  { "title": "SBK Readers and Writers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Active Readers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Readers", "legendFormat": "Active" }
   ]
  },
  {
   "title": "Max Readers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Max_Readers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Writers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Writers", "legendFormat": "Active" }
   ]
  },
  {
   "title": "Max Writers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Max_Writers", "legendFormat": "Active" }
   ]
  },
  {
   "title": "Write Performance Benchmarking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "SBK Write Throughput MB/s",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      { "expr": "SBK_Writing_MBPerSec" },
      {
       "expr": "SBK_Write_Request_Bytes_MBPerSec{action=\"Writing\"}"
      }
     ]
    },
    {
     "title": "SBK Write Records/Sec",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "wps" } },
     "targets": [
      { "expr": "SBK_Writing_RecordsPerSec" },
      {
       "expr": "SBK_Write_Request_RecordsPerSec{action=\"Writing\"}"
      }
     ]
    },
    {
     "title": "SBK Write Avg and Max Latencies (Nanoseconds)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Writing_ns_AvgLatency", "legendFormat": "Average Latency" },
      { "expr": "SBK_Writing_ns_MaxLatency", "legendFormat": "Max Latency" }
     ]
    },
    {
     "title": "SBK Write Percentiles (Nanoseconds) 1",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      { "expr": "SBK_Writing_ns_5" },
      { "expr": "SBK_Writing_ns_10" },
      { "expr": "SBK_Writing_ns_20" },
      { "expr": "SBK_Writing_ns_25" },
      { "expr": "SBK_Writing_ns_30" },
      { "expr": "SBK_Writing_ns_40" },
      { "expr": "SBK_Writing_ns_50" }
     ]
    },
    {
     "title": "SBK Write Throughput MB/s",
     "type": "gauge",
     "gridPos": { "h": 13, "w": 8, "x": 8, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Writing_MBPerSec" }
     ]
    },
    {
     "title": "SBK Write Percentiles (Nanoseconds) 2",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 16, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      { "expr": "SBK_Writing_ns_50" },
      { "expr": "SBK_Writing_ns_60" },
      { "expr": "SBK_Writing_ns_70" },
      { "expr": "SBK_Writing_ns_75" },
      { "expr": "SBK_Writing_ns_80" },
      { "expr": "SBK_Writing_ns_90" },
      { "expr": "SBK_Writing_ns_92_5" },
      { "expr": "SBK_Writing_ns_95" },
      { "expr": "SBK_Writing_ns_97_5" },
      { "expr": "SBK_Writing_ns_99" },
      { "expr": "SBK_Writing_ns_99_25" },
      { "expr": "SBK_Writing_ns_99_5" },
      { "expr": "SBK_Writing_ns_99_75" },
      { "expr": "SBK_Writing_ns_99_9" },
      { "expr": "SBK_Writing_ns_99_95" },
      { "expr": "SBK_Writing_ns_99_99" }
     ]
    },
    {
     "title": "SBK Write  Sliding Latency Coverage (SLC)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Writing_SLC_1", "legendFormat": "SLC 1" },
      { "expr": "SBK_Writing_SLC_2", "legendFormat": "SLC 2" }
     ]
    },
    {
     "title": "SBK Write Bytes Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Writing_Bytes_total", "legendFormat": "Write Bytes" },
      {
       "expr": "SBK_Write_Request_Bytes_total{action=\"Writing\"}",
       "legendFormat": "Write Request Bytes"
      }
     ]
    },
    {
     "title": "SBK Write Discarded Latencies",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 156 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Reading_LowerDiscardedLatencyRecords_total",
       "legendFormat": "Lower"
      },
      {
       "expr": "SBK_Reading_HigherDiscardLatencyRecords_total",
       "legendFormat": "Higher"
      },
      {
       "expr": "SBK_Reading_InvalidLatencyRecords_total",
       "legendFormat": "Invalid/Negative"
      }
     ]
    },
    {
     "title": "SBK Write Latency Percentiles Histogram",
     "type": "bargauge",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "SBK_Writing_Count_5", "legendFormat": "__auto" },
      { "expr": "SBK_Writing_Count_10", "legendFormat": "__auto" },
      { "expr": "SBK_Writing_Count_15", "legendFormat": "__auto" },
      { "expr": "SBK_Writing_Count_20", "legendFormat": "__auto" },
      { "expr": "SBK_Writing_Count_25", "legendFormat": "__auto" },
      { "expr": "SBK_Writing_Count_30", "legendFormat": "__auto" },
      { "expr": "SBK_Writing_Count_35", "legendFormat": "__auto" },
      { "expr": "SBK_Writing_Count_40", "legendFormat": "__auto" },
      { "expr": "SBK_Writing_Count_45", "legendFormat": "__auto" },
      { "expr": "SBK_Writing_Count_50", "legendFormat": "__auto" },
      { "expr": "SBK_Writing_Count_55", "legendFormat": "__auto" },
      { "expr": "SBK_Writing_Count_60", "legendFormat": "__auto" },
      { "expr": "SBK_Writing_Count_65", "legendFormat": "__auto" },
      { "expr": "SBK_Writing_Count_70", "legendFormat": "__auto" },
      { "expr": "SBK_Writing_Count_75", "legendFormat": "__auto" },
      { "expr": "SBK_Writing_Count_80", "legendFormat": "__auto" },
      { "expr": "SBK_Writing_Count_85", "legendFormat": "__auto" },
      { "expr": "SBK_Writing_Count_90", "legendFormat": "__auto" },
      { "expr": "SBK_Writing_Count_92_5", "legendFormat": "__auto" },
      { "expr": "SBK_Writing_Count_95", "legendFormat": "__auto" },
      { "expr": "SBK_Writing_Count_97_5", "legendFormat": "__auto" },
      { "expr": "SBK_Writing_Count_99", "legendFormat": "__auto" },
      { "expr": "SBK_Writing_Count_99_25", "legendFormat": "__auto" },
      { "expr": "SBK_Writing_Count_99_5", "legendFormat": "__auto" },
      { "expr": "SBK_Writing_Count_99_75", "legendFormat": "__auto" },
      { "expr": "SBK_Writing_Count_99_99", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Read Performance Benchmarking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "SBK Read Throughput MB/s",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 465 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      { "expr": "SBK_Reading_MBPerSec" },
      {
       "expr": "SBK_Read_Request_MBPerSec{action=\"Reading\"}"
      }
     ]
    },
    {
     "title": "SBK Read Records/Sec",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 465 },
     "fieldConfig": { "defaults": { "unit": "rps" } },
     "targets": [
      { "expr": "SBK_Reading_RecordsPerSec" },
      {
       "expr": "SBK_Read_Request_RecordsPerSec{action=\"Reading\"}"
      }
     ]
    },
    {
     "title": "SBK Read Avg and Max Latencies (Nanoseconds)",
     "type": "stat",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 465 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Reading_ns_AvgLatency", "legendFormat": "Average Latency" },
      { "expr": "SBK_Reading_ns_MaxLatency", "legendFormat": "Max Latency" }
     ]
    },
    {
     "title": "SBK Read Percentiles (Nanoseconds) 1",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 477 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      { "expr": "SBK_Reading_ns_5" },
      { "expr": "SBK_Reading_ns_10" },
      { "expr": "SBK_Reading_ns_20" },
      { "expr": "SBK_Reading_ns_25" },
      { "expr": "SBK_Reading_ns_30" },
      { "expr": "SBK_Reading_ns_40" },
      { "expr": "SBK_Reading_ns_50" }
     ]
    },
    {
     "title": "SBK Read Throughput MB/s",
     "type": "gauge",
     "gridPos": { "h": 13, "w": 8, "x": 8, "y": 477 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Reading_MBPerSec" }
     ]
    },
    {
     "title": "SBK Read Percentiles (Nanoseconds) 2",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 16, "y": 477 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      { "expr": "SBK_Reading_ns_50" },
      { "expr": "SBK_Reading_ns_60" },
      { "expr": "SBK_Reading_ns_70" },
      { "expr": "SBK_Reading_ns_75" },
      { "expr": "SBK_Reading_ns_80" },
      { "expr": "SBK_Reading_ns_90" },
      { "expr": "SBK_Reading_ns_92_25" },
      { "expr": "SBK_Reading_ns_95" },
      { "expr": "SBK_Reading_ns_97_5" },
      { "expr": "SBK_Reading_ns_99" },
      { "expr": "SBK_Reading_ns_99_25" },
      { "expr": "SBK_Reading_ns_99_5" },
      { "expr": "SBK_Reading_ns_99_75" },
      { "expr": "SBK_Reading_ns_99_9" },
      { "expr": "SBK_Reading_ns_99_95" },
      { "expr": "SBK_Reading_ns_99_99" }
     ]
    },
    {
     "title": "SBK Read  Sliding Latency Coverage (SLC)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 490 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Reading_SLC_1", "legendFormat": "SLC 1" },
      { "expr": "SBK_Reading_SLC_2", "legendFormat": "SLC 2" }
     ]
    },
    {
     "title": "SBK Read Bytes Total",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 490 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Reading_Bytes_total", "legendFormat": "Read Bytes" },
      {
       "expr": "SBK_Read_Request_Bytes_total{action=\"Reading\"}",
       "legendFormat": "Read Request Bytes"
      }
     ]
    },
    {
     "title": "SBK Read Discarded Latencies",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 490 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Reading_LowerDiscardedLatencyRecords_total",
       "legendFormat": "Lower"
      },
      {
       "expr": "SBK_Reading_HigherDiscardLatencyRecords_total",
       "legendFormat": "Higher"
      },
      {
       "expr": "SBK_Reading_InvalidLatencyRecords_total",
       "legendFormat": "Invalid/Negative"
      }
     ]
    },
    {
     "title": "SBK Read Latency Percentiles Histogram",
     "type": "bargauge",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 497 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "SBK_Reading_Count_5", "legendFormat": "__auto" },
      { "expr": "SBK_Reading_Count_10", "legendFormat": "__auto" },
      { "expr": "SBK_Reading_Count_15", "legendFormat": "__auto" },
      { "expr": "SBK_Reading_Count_20", "legendFormat": "__auto" },
      { "expr": "SBK_Reading_Count_25", "legendFormat": "__auto" },
      { "expr": "SBK_Reading_Count_30", "legendFormat": "__auto" },
      { "expr": "SBK_Reading_Count_35", "legendFormat": "__auto" },
      { "expr": "SBK_Reading_Count_40", "legendFormat": "__auto" },
      { "expr": "SBK_Reading_Count_45", "legendFormat": "__auto" },
      { "expr": "SBK_Reading_Count_50", "legendFormat": "__auto" },
      { "expr": "SBK_Reading_Count_55", "legendFormat": "__auto" },
      { "expr": "SBK_Reading_Count_60", "legendFormat": "__auto" },
      { "expr": "SBK_Reading_Count_65", "legendFormat": "__auto" },
      { "expr": "SBK_Reading_Count_70", "legendFormat": "__auto" },
      { "expr": "SBK_Reading_Count_75", "legendFormat": "__auto" },
      { "expr": "SBK_Reading_Count_80", "legendFormat": "__auto" },
      { "expr": "SBK_Reading_Count_85", "legendFormat": "__auto" },
      { "expr": "SBK_Reading_Count_90", "legendFormat": "__auto" },
      { "expr": "SBK_Reading_Count_92_5", "legendFormat": "__auto" },
      { "expr": "SBK_Reading_Count_95", "legendFormat": "__auto" },
      { "expr": "SBK_Reading_Count_97_5", "legendFormat": "__auto" },
      { "expr": "SBK_Reading_Count_99", "legendFormat": "__auto" },
      { "expr": "SBK_Reading_Count_99_25", "legendFormat": "__auto" },
      { "expr": "SBK_Reading_Count_99_5", "legendFormat": "__auto" },
      { "expr": "SBK_Reading_Count_99_75", "legendFormat": "__auto" },
      { "expr": "SBK_Reading_Count_99_99", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Write-Read Performance Benchmarking (End to End Latencies)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "SBK Write-Read Throughput MB/s ",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      { "expr": "SBK_Write_Reading_MBPerSec" },
      {
       "expr": "SBK_Write_Request_Bytes_MBPerSec{action=\"Write_Reading\"}"
      },
      {
       "expr": "SBK_Read_Request_Bytes_MBPerSec{action=\"Write_Reading\"}"
      }
     ]
    },
    {
     "title": "SBK Write-Read Records/Sec",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "SBK_Write_Reading_RecordsPerSec"
      },
      {
       "expr": "SBK_Write_Request_RecordsPerSec{action=\"Write_Reading\"}"
      },
      {
       "expr": "SBK_Read_Request_RecordsPerSec{action=\"Write_Reading\"}"
      }
     ]
    },
    {
     "title": "SBK Write-Read Avg and Max Latencies (Nanoseconds)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Write_Reading_ns_AvgLatency",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_Write_Reading_ns_MaxLatency",
       "legendFormat": "Max Latency"
      }
     ]
    },
    {
     "title": "SBK Write-Read Percentiles (Nanoseconds) 1",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      { "expr": "SBK_Write_Reading_ns_5" },
      { "expr": "SBK_Write_Reading_ns_10" },
      { "expr": "SBK_Write_Reading_ns_20" },
      { "expr": "SBK_Write_Reading_ns_25" },
      { "expr": "SBK_Write_Reading_ns_30" },
      { "expr": "SBK_Write_Reading_ns_40" },
      { "expr": "SBK_Write_Reading_ns_50" }
     ]
    },
    {
     "title": "SBK Write-Read Throughput MB/s",
     "type": "gauge",
     "gridPos": { "h": 13, "w": 8, "x": 8, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Write_Reading_MBPerSec" }
     ]
    },
    {
     "title": "SBK Write-Read Percentiles (Nanoseconds) 2",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 16, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      { "expr": "SBK_Write_Reading_ns_50" },
      { "expr": "SBK_Write_Reading_ns_60" },
      { "expr": "SBK_Write_Reading_ns_70" },
      { "expr": "SBK_Write_Reading_ns_75" },
      { "expr": "SBK_Write_Reading_ns_80" },
      { "expr": "SBK_Write_Reading_ns_90" },
      { "expr": "SBK_Write_Reading_ns_92_5" },
      { "expr": "SBK_Write_Reading_ns_95" },
      { "expr": "SBK_Write_Reading_ns_97_5" },
      { "expr": "SBK_Write_Reading_ns_99" },
      { "expr": "SBK_Write_Reading_ns_99_25" },
      { "expr": "SBK_Write_Reading_ns_99_5" },
      { "expr": "SBK_Write_Reading_ns_99_75" },
      { "expr": "SBK_Write_Reading_ns_99_9" },
      { "expr": "SBK_Write_Reading_ns_99_95" },
      { "expr": "SBK_Write_Reading_ns_99_99" }
     ]
    },
    {
     "title": "SBK Write-Read Sliding Latency Coverage (SLC)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Write_Reading_SLC_1", "legendFormat": "SLC 1" },
      { "expr": "SBK_Write_Reading_SLC_2", "legendFormat": "SLC 2" }
     ]
    },
    {
     "title": "SBK Write Read Bytes Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_Write_Reading_Bytes_total", "legendFormat": "Write Reading Bytes" },
      {
       "expr": "SBK_Read_Request_Bytes_total{action=\"Write_Reading\"}",
       "legendFormat": "Read Request Bytes"
      },
      {
       "expr": "SBK_Write_Request_Bytes_total{action=\"Write_Reading\"}",
       "legendFormat": "Write Request Bytes"
      }
     ]
    },
    {
     "title": "SBK Write-Read  Discarded Latencies",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Write_Reading_LowerDiscardedLatencyRecords_total",
       "legendFormat": "Lower"
      },
      {
       "expr": "SBK_Write_Reading_HigherDiscardLatencyRecords_total",
       "legendFormat": "Higher"
      },
      {
       "expr": "SBK_Write_Reading_InvalidLatencyRecords_total",
       "legendFormat": "Invalid/Negative"
      }
     ]
    },
    {
     "title": "SBK Write-Read Latency Percentiles Histogram",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "SBK_Write_Reading_Count_5", "legendFormat": "__auto" },
      { "expr": "SBK_Write_Reading_Count_10", "legendFormat": "__auto" },
      { "expr": "SBK_Write_Reading_Count_15", "legendFormat": "__auto" },
      { "expr": "SBK_Write_Reading_Count_20", "legendFormat": "__auto" },
      { "expr": "SBK_Write_Reading_Count_25", "legendFormat": "__auto" },
      { "expr": "SBK_Write_Reading_Count_30", "legendFormat": "__auto" },
      { "expr": "SBK_Write_Reading_Count_35", "legendFormat": "__auto" },
      { "expr": "SBK_Write_Reading_Count_40", "legendFormat": "__auto" },
      { "expr": "SBK_Write_Reading_Count_45", "legendFormat": "__auto" },
      { "expr": "SBK_Write_Reading_Count_50", "legendFormat": "__auto" },
      { "expr": "SBK_Write_Reading_Count_55", "legendFormat": "__auto" },
      { "expr": "SBK_Write_Reading_Count_60", "legendFormat": "__auto" },
      { "expr": "SBK_Write_Reading_Count_65", "legendFormat": "__auto" },
      { "expr": "SBK_Write_Reading_Count_70", "legendFormat": "__auto" },
      { "expr": "SBK_Write_Reading_Count_75", "legendFormat": "__auto" },
      { "expr": "SBK_Write_Reading_Count_80", "legendFormat": "__auto" },
      { "expr": "SBK_Write_Reading_Count_85", "legendFormat": "__auto" },
      { "expr": "SBK_Write_Reading_Count_90", "legendFormat": "__auto" },
      { "expr": "SBK_Write_Reading_Count_92_5", "legendFormat": "__auto" },
      { "expr": "SBK_Write_Reading_Count_95", "legendFormat": "__auto" },
      { "expr": "SBK_Write_Reading_Count_97_5", "legendFormat": "__auto" },
      { "expr": "SBK_Write_Reading_Count_99", "legendFormat": "__auto" },
      { "expr": "SBK_Write_Reading_Count_99_25", "legendFormat": "__auto" },
      { "expr": "SBK_Write_Reading_Count_99_5", "legendFormat": "__auto" },
      { "expr": "SBK_Write_Reading_Count_99_75", "legendFormat": "__auto" },
      { "expr": "SBK_Write_Reading_Count_99_99", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  { "title": "Write-Only Read Benchmarking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "SBK Write-Only Read Throughput MB/s ",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    { "expr": "SBK_Write_OnlyReading_MBPerSec" },
    {
     "expr": "SBK_Read_Request_MBPerSec{action=\"Write_OnlyReading\"}"
    },
    {
     "expr": "SBK_Write_Request_Bytes_MBPerSec{action=\"Write_OnlyReading\"}"
    }
   ]
  },
  {
   "title": "SBK Write-Only Read Records/Sec",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_RecordsPerSec"
    },
    {
     "expr": "SBK_Read_Request_RecordsPerSec{class=\"SBK@2020\",action=\"Write_OnlyReading\"}"
    },
    {
     "expr": "SBK_Write_Request_RecordsPerSec{action=\"Write_OnlyReading\"}"
    }
   ]
  },
  {
   "title": "SBK Write-Only Read Avg and Max Latencies (Nanoseconds)",
   "type": "stat",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_ns_AvgLatency",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_MaxLatency",
     "legendFormat": "Max Latency"
    }
   ]
  },
  {
   "title": "SBK Write-Only Read Percentiles (Nanoseconds) 1",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expr": "SBK_Write_OnlyReading_ns_5" },
    { "expr": "SBK_Write_OnlyReading_ns_10" },
    { "expr": "SBK_Write_OnlyReading_ns_20" },
    { "expr": "SBK_Write_OnlyReading_ns_25" },
    { "expr": "SBK_Write_OnlyReading_ns_30" },
    { "expr": "SBK_Write_OnlyReading_ns_40" },
    { "expr": "SBK_Write_OnlyReading_ns_50" }
   ]
  },
  {
   "title": "SBK Write-Only Read Throughput MB/s",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Write_OnlyReading_MBPerSec" }
   ]
  },
  {
   "title": "SBK Write-Only Read Percentiles (Nanoseconds) 2",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expr": "SBK_Write_OnlyReading_ns_50" },
    { "expr": "SBK_Write_OnlyReading_ns_60" },
    { "expr": "SBK_Write_OnlyReading_ns_70" },
    { "expr": "SBK_Write_OnlyReading_ns_75" },
    { "expr": "SBK_Write_OnlyReading_ns_80" },
    { "expr": "SBK_Write_OnlyReading_ns_90" },
    { "expr": "SBK_Write_OnlyReading_ns_92_5" },
    { "expr": "SBK_Write_OnlyReading_ns_95" },
    { "expr": "SBK_Write_OnlyReading_ns_97_5" },
    { "expr": "SBK_Write_OnlyReading_ns_99" },
    { "expr": "SBK_Write_OnlyReading_ns_99_25" },
    { "expr": "SBK_Write_OnlyReading_ns_99_5" },
    { "expr": "SBK_Write_OnlyReading_ns_99_75" },
    { "expr": "SBK_Write_OnlyReading_ns_99_9" },
    { "expr": "SBK_Write_OnlyReading_ns_99_95" },
    { "expr": "SBK_Write_OnlyReading_ns_99_99" }
   ]
  },
  {
   "title": "SBK Write-Only Read Sliding Latency Coverage (SLC)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Write_OnlyReading_SLC_1", "legendFormat": "SLC 1" },
    { "expr": "SBK_Write_OnlyReading_SLC_2", "legendFormat": "SLC 2" }
   ]
  },
  {
   "title": "SBK Write-Only Read Bytes Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_Bytes_total",
     "legendFormat": "Write Only Reading Bytes"
    },
    {
     "expr": "SBK_Read_Request_Bytes_total{action=\"Write_OnlyReading\"}",
     "legendFormat": "Read Request Bytes"
    },
    {
     "expr": "SBK_Write_Request_Bytes_total{action=\"Write_OnlyReading\"}",
     "legendFormat": "Write Request Bytes"
    }
   ]
  },
  {
   "title": "SBK Write-Only Read  Discarded Latencies",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_LowerDiscardedLatencyRecords_total",
     "legendFormat": "Lower"
    },
    {
     "expr": "SBK_Write_OnlyReading_HigherDiscardLatencyRecords_total",
     "legendFormat": "Higher"
    },
    {
     "expr": "SBK_Write_OnlyReading_InvalidLatencyRecords_total",
     "legendFormat": "Invalid/Negative"
    }
   ]
  },
  {
   "title": "SBK Write-Only Read Latency Percentiles Histogram",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "SBK_Write_OnlyReading_Count_5", "legendFormat": "__auto" },
    { "expr": "SBK_Write_OnlyReading_Count_10", "legendFormat": "__auto" },
    { "expr": "SBK_Write_OnlyReading_Count_15", "legendFormat": "__auto" },
    { "expr": "SBK_Write_OnlyReading_Count_20", "legendFormat": "__auto" },
    { "expr": "SBK_Write_OnlyReading_Count_25", "legendFormat": "__auto" },
    { "expr": "SBK_Write_OnlyReading_Count_30", "legendFormat": "__auto" },
    { "expr": "SBK_Write_OnlyReading_Count_35", "legendFormat": "__auto" },
    { "expr": "SBK_Write_OnlyReading_Count_40", "legendFormat": "__auto" },
    { "expr": "SBK_Write_OnlyReading_Count_45", "legendFormat": "__auto" },
    { "expr": "SBK_Write_OnlyReading_Count_50", "legendFormat": "__auto" },
    { "expr": "SBK_Write_OnlyReading_Count_55", "legendFormat": "__auto" },
    { "expr": "SBK_Write_OnlyReading_Count_60", "legendFormat": "__auto" },
    { "expr": "SBK_Write_OnlyReading_Count_65", "legendFormat": "__auto" },
    { "expr": "SBK_Write_OnlyReading_Count_70", "legendFormat": "__auto" },
    { "expr": "SBK_Write_OnlyReading_Count_75", "legendFormat": "__auto" },
    { "expr": "SBK_Write_OnlyReading_Count_80", "legendFormat": "__auto" },
    { "expr": "SBK_Write_OnlyReading_Count_85", "legendFormat": "__auto" },
    { "expr": "SBK_Write_OnlyReading_Count_90", "legendFormat": "__auto" },
    {
     "expr": "SBK_Write_OnlyReading_Count_92_5",
     "legendFormat": "__auto"
    },
    { "expr": "SBK_Write_OnlyReading_Count_95", "legendFormat": "__auto" },
    {
     "expr": "SBK_Write_OnlyReading_Count_97_5",
     "legendFormat": "__auto"
    },
    { "expr": "SBK_Write_OnlyReading_Count_99", "legendFormat": "__auto" },
    {
     "expr": "SBK_Write_OnlyReading_Count_99_25",
     "legendFormat": "__auto"
    },
    {
     "expr": "SBK_Write_OnlyReading_Count_99_5",
     "legendFormat": "__auto"
    },
    {
     "expr": "SBK_Write_OnlyReading_Count_99_75",
     "legendFormat": "__auto"
    },
    {
     "expr": "SBK_Write_OnlyReading_Count_99_99",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}