{
 "title": "SBK FILE Benchmark",
 "tags": [ "SBK" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Write Performance Benchmarking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "FILE Write Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_FILE_Writing_MBPerSec" }
   ]
  },
  {
   "title": "FILE Write Records/Sec",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    { "expr": "SBK_FILE_Writing_RecordsPerSec" }
   ]
  },
  {
   "title": "FILE Write Avg and Max Latencies (Milliseconds)",
   "type": "stat",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_FILE_Writing_ms_AvgLatency", "legendFormat": "Average Latency" },
    { "expr": "SBK_FILE_Writing_ms_MaxLatency", "legendFormat": "Max Latency" }
   ]
  },
  {
   "title": "FILE Write Percentiles (Milliseconds)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "SBK_FILE_Writing_ms_10" },
    { "expr": "SBK_FILE_Writing_ms_25" },
    { "expr": "SBK_FILE_Writing_ms_50" },
    { "expr": "SBK_FILE_Writing_ms_75" },
    { "expr": "SBK_FILE_Writing_ms_90" },
    { "expr": "SBK_FILE_Writing_ms_95" },
    { "expr": "SBK_FILE_Writing_ms_99" },
    { "expr": "SBK_FILE_Writing_ms_99_9" },
    { "expr": "SBK_FILE_Writing_ms_99_99" }
   ]
  },
  {
   "title": "FILE Writers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_FILE_Writing_Writers" }
   ]
  },
  {
   "title": "FILE Write Throughput MB/s",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_FILE_Writing_MBPerSec" }
   ]
  },
  {
   "title": "FILE Write Percentiles (Microseconds)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    { "expr": "SBK_FILE_Writing_mcs_10" },
    { "expr": "SBK_FILE_Writing_mcs_25" },
    { "expr": "SBK_FILE_Writing_mcs_50" },
    { "expr": "SBK_FILE_Writing_mcs_75" },
    { "expr": "SBK_FILE_Writing_mcs_90" },
    { "expr": "SBK_FILE_Writing_mcs_95" },
    { "expr": "SBK_FILE_Writing_mcs_99" },
    { "expr": "SBK_FILE_Writing_mcs_99_9" },
    { "expr": "SBK_FILE_Writing_mcs_99_99" }
   ]
  },
  {
   "title": "FILE Write Bytes Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_FILE_Writing_Records_total" }
   ]
  },
  {
   "title": "FILE Write Discarded Latencies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_FILE_Reading_LowerDiscardedLatencyRecords_total",
     "legendFormat": "Lower"
    },
    {
     "expr": "SBK_FILE_Reading_HigherDiscardLatencyRecords_total",
     "legendFormat": "Higher"
    },
    {
     "expr": "SBK_FILE_Reading_InvalidLatencyRecords_total",
     "legendFormat": "Invalid/Negative"
    }
   ]
  },
  {
   "title": "FILE Write Avg and Max Latencies (Microseconds)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_FILE_Writing_mcs_AvgLatency",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_FILE_Writing_mcs_MaxLatency",
     "legendFormat": "Max Latency"
    }
   ]
  },
  {
   "title": "FILE Write Percentiles (Nanoseconds)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "SBK_FILE_Writing_ns_10" },
    { "expr": "SBK_FILE_Writing_ns_25" },
    { "expr": "SBK_FILE_Writing_ns_50" },
    { "expr": "SBK_FILE_Writing_ns_75" },
    { "expr": "SBK_FILE_Writing_ns_90" },
    { "expr": "SBK_FILE_Writing_ns_95" },
    { "expr": "SBK_FILE_Writing_ns_99" },
    { "expr": "SBK_FILE_Writing_ns_99_9" },
    { "expr": "SBK_FILE_Writing_ns_99_99" }
   ]
  },
  {
   "title": "FILE Write Avg and Max Latencies (Nanoseconds)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_FILE_Writing_ns_AvgLatency", "legendFormat": "Average Latency" },
    { "expr": "SBK_FILE_Writing_ns_MaxLatency", "legendFormat": "Max Latency" }
   ]
  },
  { "title": "Read Performance Benchmarking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "FILE Read Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_FILE_Reading_MBPerSec" }
   ]
  },
  {
   "title": "FILE Read Records/Sec",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    { "expr": "SBK_FILE_Reading_RecordsPerSec" }
   ]
  },
  {
   "title": "FILE Read Avg and Max Latencies (Milliseconds)",
   "type": "stat",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_FILE_Reading_ms_AvgLatency", "legendFormat": "Average Latency" },
    { "expr": "SBK_FILE_Reading_ms_MaxLatency", "legendFormat": "Max Latency" }
   ]
  },
  {
   "title": "FILE Read Percentiles (Milli Seconds)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "SBK_FILE_Reading_ms_10" },
    { "expr": "SBK_FILE_Reading_ms_25" },
    { "expr": "SBK_FILE_Reading_ms_50" },
    { "expr": "SBK_FILE_Reading_ms_75" },
    { "expr": "SBK_FILE_Reading_ms_90" },
    { "expr": "SBK_FILE_Reading_ms_95" },
    { "expr": "SBK_FILE_Reading_ms_99" },
    { "expr": "SBK_FILE_Reading_ms_99_9" },
    { "expr": "SBK_FILE_Reading_ms_99_99" }
   ]
  },
  {
   "title": "FILE Readers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_FILE_Reading_Readers" }
   ]
  },
  {
   "title": "FILE Read Throughput MB/s",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_FILE_Reading_MBPerSec" }
   ]
  },
  {
   "title": "FILE Read Percentiles (Microseconds)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    { "expr": "SBK_FILE_Reading_mcs_10" },
    { "expr": "SBK_FILE_Reading_mcs_25" },
    { "expr": "SBK_FILE_Reading_mcs_50" },
    { "expr": "SBK_FILE_Reading_mcs_75" },
    { "expr": "SBK_FILE_Reading_mcs_90" },
    { "expr": "SBK_FILE_Reading_mcs_95" },
    { "expr": "SBK_FILE_Reading_mcs_99" },
    { "expr": "SBK_FILE_Reading_mcs_99_9" },
    { "expr": "SBK_FILE_Reading_mcs_99_99" }
   ]
  },
  {
   "title": "FILE Read Bytes Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_FILE_Reading_Bytes_total" }
   ]
  },
  {
   "title": "FILE Read Discarded Latencies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_FILE_Reading_LowerDiscardedLatencyRecords_total",
     "legendFormat": "Lower"
    },
    {
     "expr": "SBK_FILE_Reading_HigherDiscardLatencyRecords_total",
     "legendFormat": "Higher"
    },
    {
     "expr": "SBK_FILE_Reading_InvalidLatencyRecords_total",
     "legendFormat": "Invalid/Negative"
    }
   ]
  },
  {
   "title": "FILE Read Avg and Max Latencies (Microseconds)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_FILE_Reading_mcs_AvgLatency",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_FILE_Reading_mcs_MaxLatency",
     "legendFormat": "Max Latency"
    }
   ]
  },
  {
   "title": "FILE Read Percentiles (Nanoseconds)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 57 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "SBK_FILE_Reading_ns_10" },
    { "expr": "SBK_FILE_Reading_ns_25" },
    { "expr": "SBK_FILE_Reading_ns_50" },
    { "expr": "SBK_FILE_Reading_ns_75" },
    { "expr": "SBK_FILE_Reading_ns_90" },
    { "expr": "SBK_FILE_Reading_ns_95" },
    { "expr": "SBK_FILE_Reading_ns_99" },
    { "expr": "SBK_FILE_Reading_ns_99_9" },
    { "expr": "SBK_FILE_Reading_ns_99_99" }
   ]
  },
  {
   "title": "FILE Read Avg and Max Latencies (Nanoseconds)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_FILE_Reading_ns_AvgLatency", "legendFormat": "Average Latency" },
    { "expr": "SBK_FILE_Reading_ns_MaxLatency", "legendFormat": "Max Latency" }
   ]
  },
  {
   "title": "Write-Read Performance Benchmarking (End to End Latencies)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 }
  },
  {
   "title": "FILE Write-Read Throughput MB/s ",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "SBK_FILE_Write_Reading_MBPerSec"
    }
   ]
  },
  {
   "title": "FILE Write-Read Records/Sec",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 68 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "SBK_FILE_Write_Reading_RecordsPerSec"
    }
   ]
  },
  {
   "title": "FILE Write-Read Avg and Max Latencies (Milliseconds)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_FILE_Write_Reading_ms_AvgLatency",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_FILE_Write_Reading_ms_MaxLatency",
     "legendFormat": "Max Latency"
    }
   ]
  },
  {
   "title": "FILE Write-Read Percentiles (Milliseconds)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "SBK_FILE_Write_Reading_ms_10" },
    { "expr": "SBK_FILE_Write_Reading_ms_25" },
    { "expr": "SBK_FILE_Write_Reading_ms_50" },
    { "expr": "SBK_FILE_Write_Reading_ms_75" },
    { "expr": "SBK_FILE_Write_Reading_ms_90" },
    { "expr": "SBK_FILE_Write_Reading_ms_95" },
    { "expr": "SBK_FILE_Write_Reading_ms_99" },
    { "expr": "SBK_FILE_Write_Reading_ms_99_9" },
    {
     "expr": "SBK_FILE_Write_Reading_ms_99_99"
    }
   ]
  },
  {
   "title": "FILE Write-Read Bytes Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_FILE_Write_Reading_Bytes_total"
    }
   ]
  },
  {
   "title": "FILE Write-Read Throughput MB/s",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_FILE_Write_Reading_MBPerSec"
    }
   ]
  },
  {
   "title": "FILE Write-Read Percentiles (Microseconds)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 79 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    { "expr": "SBK_FILE_Write_Reading_mcs_10" },
    { "expr": "SBK_FILE_Write_Reading_mcs_25" },
    { "expr": "SBK_FILE_Write_Reading_mcs_50" },
    { "expr": "SBK_FILE_Write_Reading_mcs_75" },
    { "expr": "SBK_FILE_Write_Reading_mcs_90" },
    { "expr": "SBK_FILE_Write_Reading_mcs_95" },
    { "expr": "SBK_FILE_Write_Reading_mcs_99" },
    {
     "expr": "SBK_FILE_Write_Reading_mcs_99_9"
    },
    {
     "expr": "SBK_FILE_Write_Reading_mcs_99_99"
    }
   ]
  },
  {
   "title": "FILE Write-Read  Writers and Readers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_FILE_Write_Reading_Readers", "legendFormat": "Readers" },
    { "expr": "SBK_FILE_Write_Reading_Writers", "legendFormat": "Writers" }
   ]
  },
  {
   "title": "FILE Write-Read  Discarded Latencies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_FILE_Write_Reading_LowerDiscardedLatencyRecords_total",
     "legendFormat": "Lower"
    },
    {
     "expr": "SBK_FILE_Write_Reading_HigherDiscardLatencyRecords_total",
     "legendFormat": "Higher"
    },
    {
     "expr": "SBK_FILE_Write_Reading_InvalidLatencyRecords_total",
     "legendFormat": "Invalid/Negative"
    }
   ]
  },
  {
   "title": "FILE Write-Read Avg and Max Latencies (Microseconds)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_FILE_Write_Reading_mcs_AvgLatency",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_FILE_Write_Reading_mcs_MaxLatency",
     "legendFormat": "Max Latency"
    }
   ]
  },
  {
   "title": "FILE Write-Read Percentiles (Nanoseconds)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 90 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "SBK_FILE_Write_Reading_ns_10" },
    { "expr": "SBK_FILE_Write_Reading_ns_25" },
    { "expr": "SBK_FILE_Write_Reading_ns_50" },
    { "expr": "SBK_FILE_Write_Reading_ns_75" },
    { "expr": "SBK_FILE_Write_Reading_ns_90" },
    { "expr": "SBK_FILE_Write_Reading_ns_95" },
    { "expr": "SBK_FILE_Write_Reading_ns_99" },
    { "expr": "SBK_FILE_Write_Reading_ns_99_9" },
    {
     "expr": "SBK_FILE_Write_Reading_ns_99_99"
    }
   ]
  },
  {
   "title": "FILE Write-Read Avg and Max Latencies (Nanoseconds)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_FILE_Write_Reading_ns_AvgLatency",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_FILE_Write_Reading_ns_MaxLatency",
     "legendFormat": "Max Latency"
    }
   ]
  }
 ]
}