{
 "title": "SBK NATSSTREAM Benchmark",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "NATSSTREAM Write Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "SBK_NATSSTREAM_Writing_MBPerSec"
    }
   ]
  },
  {
   "title": "NATSSTREAM Write Records/Sec",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "SBK_NATSSTREAM_Writing_RecordsPerSec"
    }
   ]
  },
  {
   "title": "NATSSTREAM Write Avg and Max Latencies",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "SBK_NATSSTREAM_Writing_ms_AvgLatency"
    },
    {
     "expr": "SBK_NATSSTREAM_Writing_ms_MaxLatency"
    }
   ]
  },
  {
   "title": "NATSSTREAM Write Percentiles",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "SBK_NATSSTREAM_Writing_ms_10" },
    { "expr": "SBK_NATSSTREAM_Writing_ms_25" },
    { "expr": "SBK_NATSSTREAM_Writing_ms_50" },
    { "expr": "SBK_NATSSTREAM_Writing_ms_75" },
    { "expr": "SBK_NATSSTREAM_Writing_ms_90" },
    { "expr": "SBK_NATSSTREAM_Writing_ms_95" },
    { "expr": "SBK_NATSSTREAM_Writing_ms_99" },
    { "expr": "SBK_NATSSTREAM_Writing_ms_99_9" },
    {
     "expr": "SBK_NATSSTREAM_Writing_ms_99_99"
    }
   ]
  },
  {
   "title": "NATSSTREAM Write Bytes Total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "SBK_NATSSTREAM_Writing_Records_total"
    }
   ]
  },
  {
   "title": "NATSSTREAM Write Discarded Latencies",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_NATSSTREAM_Writing_LowerDiscardedLatencyRecords_total"
    },
    {
     "expr": "SBK_NATSSTREAM_Writing_HigherDiscardLatencyRecords_total"
    }
   ]
  },
  {
   "title": "NATSSTREAM Writers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_NATSSTREAM_Writing_Writers" }
   ]
  },
  {
   "title": "NATSSTREAM Read Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "SBK_NATSSTREAM_Reading_MBPerSec"
    }
   ]
  },
  {
   "title": "NATSSTREAM Read Records/Sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "SBK_NATSSTREAM_Reading_RecordsPerSec"
    }
   ]
  },
  {
   "title": "NATSSTREAM Read Avg and Max Latencies",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "SBK_NATSSTREAM_Reading_ms_AvgLatency"
    },
    {
     "expr": "SBK_NATSSTREAM_Reading_ms_MaxLatency"
    }
   ]
  },
  {
   "title": "NATSSTREAM Read Percentiles",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "SBK_NATSSTREAM_Reading_ms_10" },
    { "expr": "SBK_NATSSTREAM_Reading_ms_25" },
    { "expr": "SBK_NATSSTREAM_Reading_ms_50" },
    { "expr": "SBK_NATSSTREAM_Reading_ms_75" },
    { "expr": "SBK_NATSSTREAM_Reading_ms_90" },
    { "expr": "SBK_NATSSTREAM_Reading_ms_95" },
    { "expr": "SBK_NATSSTREAM_Reading_ms_99" },
    { "expr": "SBK_NATSSTREAM_Reading_ms_99_9" },
    {
     "expr": "SBK_NATSSTREAM_Reading_ms_99_99"
    }
   ]
  },
  {
   "title": "NATSSTREAM Read Bytes Total",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "SBK_NATSSTREAM_Reading_Bytes_total"
    }
   ]
  },
  {
   "title": "NATSSTREAM Read Discarded Latencies",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_NATSSTREAM_Reading_LowerDiscardedLatencyRecords_total"
    },
    {
     "expr": "SBK_NATSSTREAM_Reading_HigherDiscardLatencyRecords_total"
    }
   ]
  },
  {
   "title": "NATSSTREAM Readers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_NATSSTREAM_Reading_Readers" }
   ]
  },
  {
   "title": "NATSSTREAM Write-Read Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "SBK_NATSSTREAM_Write_Reading_MBPerSec"
    }
   ]
  },
  {
   "title": "NATSSTREAM Write-Read Records/Sec",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "SBK_NATSSTREAM_Write_Reading_RecordsPerSec"
    }
   ]
  },
  {
   "title": "NATSSTREAM Write-Read Avg and Max Latencies",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "SBK_NATSSTREAM_Write_Reading_ms_AvgLatency"
    },
    {
     "expr": "SBK_NATSSTREAM_Write_Reading_ms_MaxLatency"
    }
   ]
  },
  {
   "title": "NATSSTREAM Write-Read Percentiles",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "SBK_NATSSTREAM_Write_Reading_ms_10"
    },
    {
     "expr": "SBK_NATSSTREAM_Write_Reading_ms_25"
    },
    {
     "expr": "SBK_NATSSTREAM_Write_Reading_ms_50"
    },
    {
     "expr": "SBK_NATSSTREAM_Write_Reading_ms_75"
    },
    {
     "expr": "SBK_NATSSTREAM_Write_Reading_ms_90"
    },
    {
     "expr": "SBK_NATSSTREAM_Write_Reading_ms_95"
    },
    {
     "expr": "SBK_NATSSTREAM_Write_Reading_ms_99"
    },
    {
     "expr": "SBK_NATSSTREAM_Write_Reading_ms_99_9"
    },
    {
     "expr": "SBK_NATSSTREAM_Write_Reading_ms_99_99"
    }
   ]
  },
  {
   "title": "NATSSTREAM Write-Read Bytes Total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "SBK_NATSSTREAM_Write_Reading_Bytes_total"
    }
   ]
  },
  {
   "title": "NATSSTREAM Write-Read  Discarded Latencies",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_NATSSTREAM_Write_Reading_LowerDiscardedLatencyRecords_total"
    },
    {
     "expr": "SBK_NATSSTREAM_Write_Reading_HigherDiscardLatencyRecords_total"
    }
   ]
  },
  {
   "title": "NATSSTREAM Write-Read  Writers and Readers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_NATSSTREAM_Write_Reading_Readers"
    },
    {
     "expr": "SBK_NATSSTREAM_Write_Reading_Writers"
    }
   ]
  }
 ]
}