{
 "title": "SBK PRAVEGA Benchmark",
 "tags": [ "SBK" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Prometheus", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_uname_info, job)"
   },
   { "name": "node", "label": "Host:" }
  ]
 },
 "panels": [
  { "title": "Write Performance Benchmarking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PRAVEGA Write Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    { "expr": "SBK_PRAVEGA_Writing_MBPerSec" }
   ]
  },
  {
   "title": "PRAVEGA Write Records/Sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Writing_RecordsPerSec"
    }
   ]
  },
  {
   "title": "PRAVEGA Writers",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_PRAVEGA_Writing_Writers" }
   ]
  },
  {
   "title": "PRAVEGA Write Bytes Total",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Writing_Records_total"
    }
   ]
  },
  {
   "title": "PRAVEGA Write Discarded Latencies",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Reading_LowerDiscardedLatencyRecords_total",
     "legendFormat": "Lower"
    },
    {
     "expr": "SBK_PRAVEGA_Reading_HigherDiscardLatencyRecords_total",
     "legendFormat": "Higher"
    },
    {
     "expr": "SBK_PRAVEGA_Reading_InvalidLatencyRecords_total",
     "legendFormat": "Invalid/Negative"
    }
   ]
  },
  {
   "title": "PRAVEGA Write Avg and Max Latencies (Milliseconds)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Writing_ms_AvgLatency"
    },
    {
     "expr": "SBK_PRAVEGA_Writing_ms_MaxLatency"
    }
   ]
  },
  {
   "title": "PRAVEGA Write Percentiles (Milliseconds)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "SBK_PRAVEGA_Writing_ms_10" },
    { "expr": "SBK_PRAVEGA_Writing_ms_25" },
    { "expr": "SBK_PRAVEGA_Writing_ms_50" },
    { "expr": "SBK_PRAVEGA_Writing_ms_75" },
    { "expr": "SBK_PRAVEGA_Writing_ms_90" },
    { "expr": "SBK_PRAVEGA_Writing_ms_95" },
    { "expr": "SBK_PRAVEGA_Writing_ms_99" },
    { "expr": "SBK_PRAVEGA_Writing_ms_99_9" },
    { "expr": "SBK_PRAVEGA_Writing_ms_99_99" }
   ]
  },
  {
   "title": "PRAVEGA Write Avg and Max Latencies (Microseconds)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Writing_mcs_AvgLatency"
    },
    {
     "expr": "SBK_PRAVEGA_Writing_mcs_MaxLatency"
    }
   ]
  },
  {
   "title": "PRAVEGA Write Percentiles (Microseconds)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    { "expr": "SBK_PRAVEGA_Writing_mcs_10" },
    { "expr": "SBK_PRAVEGA_Writing_mcs_25" },
    { "expr": "SBK_PRAVEGA_Writing_mcs_50" },
    { "expr": "SBK_PRAVEGA_Writing_mcs_75" },
    { "expr": "SBK_PRAVEGA_Writing_mcs_90" },
    { "expr": "SBK_PRAVEGA_Writing_mcs_95" },
    { "expr": "SBK_PRAVEGA_Writing_mcs_99" },
    { "expr": "SBK_PRAVEGA_Writing_mcs_99_9" },
    { "expr": "SBK_PRAVEGA_Writing_mcs_99_99" }
   ]
  },
  {
   "title": "PRAVEGA Write Avg and Max Latencies (Nanoseconds)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Writing_ns_AvgLatency"
    },
    {
     "expr": "SBK_PRAVEGA_Writing_ns_MaxLatency"
    }
   ]
  },
  {
   "title": "PRAVEGA Write Percentiles (Nanoseconds)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "SBK_PRAVEGA_Writing_ns_10" },
    { "expr": "SBK_PRAVEGA_Writing_ns_25" },
    { "expr": "SBK_PRAVEGA_Writing_ns_50" },
    { "expr": "SBK_PRAVEGA_Writing_ns_75" },
    { "expr": "SBK_PRAVEGA_Writing_ns_90" },
    { "expr": "SBK_PRAVEGA_Writing_ns_95" },
    { "expr": "SBK_PRAVEGA_Writing_ns_99" },
    { "expr": "SBK_PRAVEGA_Writing_ns_99_9" },
    { "expr": "SBK_PRAVEGA_Writing_ns_99_99" }
   ]
  },
  { "title": "Read Performance Benchmarking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "PRAVEGA Read Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    { "expr": "SBK_PRAVEGA_Reading_MBPerSec" }
   ]
  },
  {
   "title": "PRAVEGA Read Records/Sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Reading_RecordsPerSec"
    }
   ]
  },
  {
   "title": "PRAVEGA Readers",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_PRAVEGA_Reading_Readers" }
   ]
  },
  {
   "title": "PRAVEGA Read Bytes Total",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Reading_Bytes_total"
    }
   ]
  },
  {
   "title": "PRAVEGA Read Discarded Latencies",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Reading_LowerDiscardedLatencyRecords_total",
     "legendFormat": "Lower"
    },
    {
     "expr": "SBK_PRAVEGA_Reading_HigherDiscardLatencyRecords_total",
     "legendFormat": "Higher"
    },
    {
     "expr": "SBK_PRAVEGA_Reading_InvalidLatencyRecords_total",
     "legendFormat": "Invalid/Negative"
    }
   ]
  },
  {
   "title": "PRAVEGA Read Avg and Max Latencies (Milliseconds)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Reading_ms_AvgLatency"
    },
    {
     "expr": "SBK_PRAVEGA_Reading_ms_MaxLatency"
    }
   ]
  },
  {
   "title": "PRAVEGA Read Percentiles (Milli Seconds)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "SBK_PRAVEGA_Reading_ms_10" },
    { "expr": "SBK_PRAVEGA_Reading_ms_25" },
    { "expr": "SBK_PRAVEGA_Reading_ms_50" },
    { "expr": "SBK_PRAVEGA_Reading_ms_75" },
    { "expr": "SBK_PRAVEGA_Reading_ms_90" },
    { "expr": "SBK_PRAVEGA_Reading_ms_95" },
    { "expr": "SBK_PRAVEGA_Reading_ms_99" },
    { "expr": "SBK_PRAVEGA_Reading_ms_99_9" },
    { "expr": "SBK_PRAVEGA_Reading_ms_99_99" }
   ]
  },
  {
   "title": "PRAVEGA Read Avg and Max Latencies (Microseconds)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 62 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Reading_mcs_AvgLatency"
    },
    {
     "expr": "SBK_PRAVEGA_Reading_mcs_MaxLatency"
    }
   ]
  },
  {
   "title": "PRAVEGA Read Percentiles (Microseconds)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 62 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    { "expr": "SBK_PRAVEGA_Reading_mcs_10" },
    { "expr": "SBK_PRAVEGA_Reading_mcs_25" },
    { "expr": "SBK_PRAVEGA_Reading_mcs_50" },
    { "expr": "SBK_PRAVEGA_Reading_mcs_75" },
    { "expr": "SBK_PRAVEGA_Reading_mcs_90" },
    { "expr": "SBK_PRAVEGA_Reading_mcs_95" },
    { "expr": "SBK_PRAVEGA_Reading_mcs_99" },
    { "expr": "SBK_PRAVEGA_Reading_mcs_99_9" },
    { "expr": "SBK_PRAVEGA_Reading_mcs_99_99" }
   ]
  },
  {
   "title": "PRAVEGA Read Avg and Max Latencies (Nanoseconds)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Reading_ns_AvgLatency"
    },
    {
     "expr": "SBK_PRAVEGA_Reading_ns_MaxLatency"
    }
   ]
  },
  {
   "title": "PRAVEGA Read Percentiles (Nanoseconds)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 72 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "SBK_PRAVEGA_Reading_ns_10" },
    { "expr": "SBK_PRAVEGA_Reading_ns_25" },
    { "expr": "SBK_PRAVEGA_Reading_ns_50" },
    { "expr": "SBK_PRAVEGA_Reading_ns_75" },
    { "expr": "SBK_PRAVEGA_Reading_ns_90" },
    { "expr": "SBK_PRAVEGA_Reading_ns_95" },
    { "expr": "SBK_PRAVEGA_Reading_ns_99" },
    { "expr": "SBK_PRAVEGA_Reading_ns_99_9" },
    { "expr": "SBK_PRAVEGA_Reading_ns_99_99" }
   ]
  },
  {
   "title": "Write-Read Performance Benchmarking (End to End Latencies)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 }
  },
  {
   "title": "PRAVEGA Write-Read Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Write_Reading_MBPerSec"
    }
   ]
  },
  {
   "title": "PRAVEGA Write-Read Records/Sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 83 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Write_Reading_RecordsPerSec"
    }
   ]
  },
  {
   "title": "PRAVEGA Write-Read  Writers and Readers",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Write_Reading_Readers",
     "legendFormat": "Readers"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_Writers",
     "legendFormat": "Writers"
    }
   ]
  },
  {
   "title": "PRAVEGA Write-Read Bytes Total",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Write_Reading_Bytes_total"
    }
   ]
  },
  {
   "title": "PRAVEGA Write-Read  Discarded Latencies",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Write_Reading_LowerDiscardedLatencyRecords_total",
     "legendFormat": "Lower"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_HigherDiscardLatencyRecords_total",
     "legendFormat": "Higher"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_InvalidLatencyRecords_total",
     "legendFormat": "Invalid/Negative"
    }
   ]
  },
  {
   "title": "PRAVEGA Write-Read Avg and Max Latencies (Milliseconds)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 93 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Write_Reading_ms_AvgLatency"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_ms_MaxLatency"
    }
   ]
  },
  {
   "title": "PRAVEGA Write-Read Percentiles (Milliseconds)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Write_Reading_ms_10"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_ms_25"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_ms_50"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_ms_75"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_ms_90"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_ms_95"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_ms_99"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_ms_99_9"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_ms_99_99"
    }
   ]
  },
  {
   "title": "PRAVEGA Write-Read Avg and Max Latencies (Microseconds)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 103 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Write_Reading_mcs_AvgLatency"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_mcs_MaxLatency"
    }
   ]
  },
  {
   "title": "PRAVEGA Write-Read Percentiles (Microseconds)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 103 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Write_Reading_mcs_10"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_mcs_25"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_mcs_50"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_mcs_75"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_mcs_90"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_mcs_95"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_mcs_99"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_mcs_99_9"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_mcs_99_99"
    }
   ]
  },
  {
   "title": "PRAVEGA Write-Read Avg and Max Latencies (Nanoseconds)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Write_Reading_ns_AvgLatency"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_ns_MaxLatency"
    }
   ]
  },
  {
   "title": "PRAVEGA Write-Read Percentiles (Nanoseconds)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 113 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "SBK_PRAVEGA_Write_Reading_ns_10"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_ns_25"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_ns_50"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_ns_75"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_ns_90"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_ns_95"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_ns_99"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_ns_99_9"
    },
    {
     "expr": "SBK_PRAVEGA_Write_Reading_ns_99_99"
    }
   ]
  }
 ]
}