{
 "title": "SBK Sbktemplate Dashboard",
 "tags": [ "SBK" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "SBK Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Writers Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Writing_Connections", "legendFormat": "Active" },
    { "expr": "SBK_Writing_Max_Connections", "legendFormat": "Max" }
   ]
  },
  {
   "title": "Readers Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Reading_Connections", "legendFormat": "Active" },
    { "expr": "SBK_Reading_Max_Connections", "legendFormat": "Max" }
   ]
  },
  {
   "title": "Write-Readers Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Write_Reading_Connections", "legendFormat": "Active" },
    {
     "expr": "SBK_Write_Reading_Max_Connections",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Write Performance Benchmarking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "SBK Sbktemplate Write Throughput MB/s",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      {
       "expr": "SBK_Writing_MBPerSec{class=\"Sbktemplate\"}"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write Records/Sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "SBK_Writing_RecordsPerSec{class=\"Sbktemplate\"}"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write Avg and Max Latencies (Nanoseconds)",
     "type": "stat",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Writing_ns_AvgLatency{class=\"Sbktemplate\"}",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_Writing_ns_MaxLatency{class=\"Sbktemplate\"}",
       "legendFormat": "Max Latency"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write Percentiles (Nanoseconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "SBK_Writing_ns_10{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_ns_20{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_ns_25{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_ns_30{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_ns_40{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_ns_50{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_ns_60{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_ns_70{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_ns_75{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_ns_80{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_ns_90{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_ns_92_5{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_ns_95{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_ns_97_5{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_ns_99{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_ns_99_25{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_ns_99_5{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_ns_99_75{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_ns_99_9{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_ns_99_95{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_ns_99_99{class=\"Sbktemplate\"}"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Writers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Writing_Writers{class=\"Sbktemplate\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "SBK_Writing_Max_Writers{class=\"Sbktemplate\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write Throughput MB/s",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 11, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Writing_MBPerSec{class=\"Sbktemplate\"}"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write  Sliding Latency Coverage (SLC)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Writing_SLC_1{class=\"Sbktemplate\"}",
       "legendFormat": "SLC 1"
      },
      {
       "expr": "SBK_Writing_SLC_2{class=\"Sbktemplate\"}",
       "legendFormat": "SLC 2"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write Bytes Total",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Writing_Records_total{class=\"Sbktemplate\"}"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write Discarded Latencies",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 11, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Reading_LowerDiscardedLatencyRecords_total{class=\"Sbktemplate\"}",
       "legendFormat": "Lower"
      },
      {
       "expr": "SBK_Reading_HigherDiscardLatencyRecords_total{class=\"Sbktemplate\"}",
       "legendFormat": "Higher"
      },
      {
       "expr": "SBK_Reading_InvalidLatencyRecords_total{class=\"Sbktemplate\"}",
       "legendFormat": "Invalid/Negative"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write Avg and Max Latencies (Microseconds)",
     "type": "stat",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Writing_mcs_AvgLatency{class=\"Sbktemplate\"}",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_Writing_mcs_MaxLatency{class=\"Sbktemplate\"}",
       "legendFormat": "Max Latency"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write Percentiles (Microseconds)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "SBK_Writing_mcs_10{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_mcs_25{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_mcs_50{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_mcs_75{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_mcs_90{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_mcs_95{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_mcs_99{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_mcs_99_9{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_mcs_99_99{class=\"Sbktemplate\"}"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write Percentiles (Milliseconds)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 27 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "SBK_Writing_ms_10{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_ms_25{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_ms_50{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_ms_75{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_ms_90{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_ms_95{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_ms_99{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_ms_99_9{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Writing_ms_99_99{class=\"Sbktemplate\"}"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write Avg and Max Latencies (Milliseconds)",
     "type": "stat",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Writing_ms_AvgLatency{class=\"Sbktemplate\"}",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_Writing_ms_MaxLatency{class=\"Sbktemplate\"}",
       "legendFormat": "Max Latency"
      }
     ]
    }
   ]
  },
  {
   "title": "Read Performance Benchmarking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "SBK Sbktemplate Read Throughput MB/s",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      {
       "expr": "SBK_Reading_MBPerSec{class=\"Sbktemplate\"}"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Read Records/Sec",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "SBK_Reading_RecordsPerSec{class=\"Sbktemplate\"}"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Read Avg and Max Latencies (Nanoseconds)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Reading_ns_AvgLatency{class=\"Sbktemplate\"}",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_Reading_ns_MaxLatency{class=\"Sbktemplate\"}",
       "legendFormat": "Max Latency"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Read Percentiles (Nanoseconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "SBK_Reading_ns_10{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_ns_20{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_ns_25{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_ns_30{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_ns_40{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_ns_50{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_ns_60{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_ns_70{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_ns_75{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_ns_80{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_ns_90{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_ns_92_25{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_ns_95{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_ns_97_5{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_ns_99{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_ns_99_25{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_ns_99_5{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_ns_99_75{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_ns_99_9{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_ns_99_95{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_ns_99_99{class=\"Sbktemplate\"}"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Readers",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Reading_Readers{class=\"Sbktemplate\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "SBK_Reading_Max_Readers{class=\"Sbktemplate\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Read Throughput MB/s",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 11, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Reading_MBPerSec{class=\"Sbktemplate\"}"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Read  Sliding Latency Coverage (SLC)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Reading_SLC_1{class=\"Sbktemplate\"}",
       "legendFormat": "SLC 1"
      },
      {
       "expr": "SBK_Reading_SLC_2{class=\"Sbktemplate\"}",
       "legendFormat": "SLC 2"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Read Bytes Total",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Reading_Bytes_total{class=\"Sbktemplate\"}"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Read Discarded Latencies",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 11, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Reading_LowerDiscardedLatencyRecords_total{class=\"Sbktemplate\"}",
       "legendFormat": "Lower"
      },
      {
       "expr": "SBK_Reading_HigherDiscardLatencyRecords_total{class=\"Sbktemplate\"}",
       "legendFormat": "Higher"
      },
      {
       "expr": "SBK_Reading_InvalidLatencyRecords_total{class=\"Sbktemplate\"}",
       "legendFormat": "Invalid/Negative"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Read Avg and Max Latencies (Microseconds)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Reading_mcs_AvgLatency{class=\"Sbktemplate\"}",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_Reading_mcs_MaxLatency{class=\"Sbktemplate\"}",
       "legendFormat": "Max Latency"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Read Percentiles (Microseconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "SBK_Reading_mcs_10{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_mcs_25{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_mcs_50{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_mcs_75{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_mcs_90{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_mcs_95{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_mcs_99{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_mcs_99_9{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_mcs_99_99{class=\"Sbktemplate\"}"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Read Percentiles (Milli Seconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "SBK_Reading_ms_10{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_ms_25{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_ms_50{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_ms_75{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_ms_90{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_ms_95{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_ms_99{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_ms_99_9{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Reading_ms_99_99{class=\"Sbktemplate\"}"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Read Avg and Max Latencies (Milliseconds)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Reading_ms_AvgLatency{class=\"Sbktemplate\"}",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_Reading_ms_MaxLatency{class=\"Sbktemplate\"}",
       "legendFormat": "Max Latency"
      }
     ]
    }
   ]
  },
  {
   "title": "Write-Read Performance Benchmarking (End to End Latencies)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "SBK Sbktemplate Write-Read Throughput MB/s ",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      {
       "expr": "SBK_Write_Reading_MBPerSec{class=\"Sbktemplate\"}"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write-Read Records/Sec",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "SBK_Write_Reading_RecordsPerSec{class=\"Sbktemplate\"}"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write-Read Avg and Max Latencies (Nanoseconds)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Write_Reading_ns_AvgLatency{class=\"Sbktemplate\"}",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_Write_Reading_ns_MaxLatency{class=\"Sbktemplate\"}",
       "legendFormat": "Max Latency"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write-Read Percentiles (Nanoseconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "SBK_Write_Reading_ns_10{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_ns_20{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_ns_25{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_ns_30{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_ns_40{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_ns_50{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_ns_60{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_ns_70{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_ns_75{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_ns_80{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_ns_90{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_ns_92_5{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_ns_95{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_ns_97_5{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_ns_99{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_ns_99_25{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_ns_99_5{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_ns_99_75{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_ns_99_9{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_ns_99_95{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_ns_99_99{class=\"Sbktemplate\"}"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write-Read Bytes Total",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Write_Reading_Bytes_total{class=\"Sbktemplate\"}"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write-Read Throughput MB/s",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 11, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Write_Reading_MBPerSec{class=\"Sbktemplate\"}"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write-Read Sliding Latency Coverage (SLC)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Write_Reading_SLC_1{class=\"Sbktemplate\"}",
       "legendFormat": "SLC 1"
      },
      {
       "expr": "SBK_Write_Reading_SLC_2{class=\"Sbktemplate\"}",
       "legendFormat": "SLC 2"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write-Read  Writers and Readers",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Write_Reading_Readers{class=\"Sbktemplate\"}",
       "legendFormat": "Active Readers"
      },
      {
       "expr": "SBK_Write_Reading_Max_Readers{class=\"Sbktemplate\"}",
       "legendFormat": "Max Readers"
      },
      {
       "expr": "SBK_Write_Reading_Writers{class=\"Sbktemplate\"}",
       "legendFormat": "Active Writers"
      },
      {
       "expr": "SBK_Write_Reading_Max_Writers{class=\"Sbktemplate\"}",
       "legendFormat": "Max Writers"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write-Read  Discarded Latencies",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 11, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Write_Reading_LowerDiscardedLatencyRecords_total{class=\"Sbktemplate\"}",
       "legendFormat": "Lower"
      },
      {
       "expr": "SBK_Write_Reading_HigherDiscardLatencyRecords_total{class=\"Sbktemplate\"}",
       "legendFormat": "Higher"
      },
      {
       "expr": "SBK_Write_Reading_InvalidLatencyRecords_total{class=\"Sbktemplate\"}",
       "legendFormat": "Invalid/Negative"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write-Read Avg and Max Latencies (Microseconds)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Write_Reading_mcs_AvgLatency{class=\"Sbktemplate\"}",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_Write_Reading_mcs_MaxLatency{class=\"Sbktemplate\"}",
       "legendFormat": "Max Latency"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write-Read Percentiles (Microseconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "SBK_Write_Reading_mcs_10{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_mcs_25{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_mcs_50{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_mcs_75{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_mcs_90{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_mcs_95{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_mcs_99{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_mcs_99_9{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_mcs_99_99{class=\"Sbktemplate\"}"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write-Read Percentiles (Milliseconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 31 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "SBK_Write_Reading_ms_10{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_ms_25{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_ms_50{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_ms_75{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_ms_90{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_ms_95{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_ms_99{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_ms_99_9{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_Reading_ms_99_99{class=\"Sbktemplate\"}"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write-Read Avg and Max Latencies (Milliseconds)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Write_Reading_ms_AvgLatency{class=\"Sbktemplate\"}",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_Write_Reading_ms_MaxLatency{class=\"Sbktemplate\"}",
       "legendFormat": "Max Latency"
      }
     ]
    }
   ]
  },
  {
   "title": "Write-Only Read Benchmarking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "SBK Sbktemplate Write-Only Read Throughput MB/s ",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      {
       "expr": "SBK_Write_OnlyReading_MBPerSec{class=\"Sbktemplate\"}"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write-Only Read Records/Sec",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "SBK_Write_OnlyReading_RecordsPerSec{class=\"Sbktemplate\"}"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write-Only Read Avg and Max Latencies (Nanoseconds)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Write_OnlyReading_ns_AvgLatency{class=\"Sbktemplate\"}",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_Write_Reading_ns_MaxLatency{class=\"Sbktemplate\"}",
       "legendFormat": "Max Latency"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write-Only Read Percentiles (Nanoseconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "SBK_Write_OnlyReading_ns_10{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_ns_20{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_ns_25{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_ns_30{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_ns_40{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_ns_50{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_ns_60{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_ns_70{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_ns_75{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_ns_80{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_ns_90{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_ns_92_5{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_ns_95{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_ns_97_5{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_ns_99{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_ns_99_25{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_ns_99_5{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_ns_99_75{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_ns_99_9{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_ns_99_95{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_ns_99_99{class=\"Sbktemplate\"}"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write-Only Read Bytes Total",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Write_OnlyReading_Bytes_total{class=\"Sbktemplate\"}"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write-Only Read Throughput MB/s",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 11, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Write_OnlyReading_MBPerSec{class=\"Sbktemplate\"}"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write-Only Read Sliding Latency Coverage (SLC)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Write_OnlyReading_SLC_1{class=\"Sbktemplate\"}",
       "legendFormat": "SLC 1"
      },
      {
       "expr": "SBK_Write_OnlyReading_SLC_2{class=\"Sbktemplate\"}",
       "legendFormat": "SLC 2"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write-Only Read  Writers and Readers",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Write_OnlyReading_Readers{class=\"Sbktemplate\"}",
       "legendFormat": "Active Readers"
      },
      {
       "expr": "SBK_Write_OnlyReading_Max_Readers{class=\"Sbktemplate\"}",
       "legendFormat": "Max Readers"
      },
      {
       "expr": "SBK_Write_OnlyReading_Writers{class=\"Sbktemplate\"}",
       "legendFormat": "Active Writers"
      },
      {
       "expr": "SBK_Write_OnlyReading_Max_Writers{class=\"Sbktemplate\"}",
       "legendFormat": "Max Writers"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write-Only Read  Discarded Latencies",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 11, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Write_OnlyReading_LowerDiscardedLatencyRecords_total{class=\"Sbktemplate\"}",
       "legendFormat": "Lower"
      },
      {
       "expr": "SBK_Write_OnlyReading_HigherDiscardLatencyRecords_total{class=\"Sbktemplate\"}",
       "legendFormat": "Higher"
      },
      {
       "expr": "SBK_Write_OnlyReading_InvalidLatencyRecords_total{class=\"Sbktemplate\"}",
       "legendFormat": "Invalid/Negative"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write-Only Read Avg and Max Latencies (Microseconds)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Write_OnlyReading_mcs_AvgLatency{class=\"Sbktemplate\"}",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_Write_OnlyReading_mcs_MaxLatency{class=\"Sbktemplate\"}",
       "legendFormat": "Max Latency"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write-Only Read Percentiles (Microseconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "SBK_Write_OnlyReading_mcs_10{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_mcs_25{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_mcs_50{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_mcs_75{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_mcs_90{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_mcs_95{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_mcs_99{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_mcs_99_9{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_mcs_99_99{class=\"Sbktemplate\"}"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write-Only Read Percentiles (Milliseconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "SBK_Write_OnlyReading_ms_10{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_ms_25{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_ms_50{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_ms_75{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_ms_90{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_ms_95{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_ms_99{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_ms_99_9{class=\"Sbktemplate\"}"
      },
      {
       "expr": "SBK_Write_OnlyReading_ms_99_99{class=\"Sbktemplate\"}"
      }
     ]
    },
    {
     "title": "SBK Sbktemplate Write-Only Read Avg and Max Latencies (Milliseconds)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Write_OnlyReading_ms_AvgLatency{class=\"Sbktemplate\"}",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_Write_OnlyReading_ms_MaxLatency{class=\"Sbktemplate\"}",
       "legendFormat": "Max Latency"
      }
     ]
    }
   ]
  }
 ]
}