{
 "title": "SBK RABBITMQ Benchmark",
 "tags": [ "SBK" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "SBK Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Writers Connections",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_RABBITMQ_Writing_Connections",
       "legendFormat": "Active"
      },
      {
       "expr": "SBK_RABBITMQ_Writing_Max_Connections",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Readers Connections",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_RABBITMQ_Reading_Connections",
       "legendFormat": "Active"
      },
      {
       "expr": "SBK_RABBITMQ_Reading_Max_Connections",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Write-Readers Connections",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_RABBITMQ_Write_Reading_Connections",
       "legendFormat": "Active"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_Max_Connections",
       "legendFormat": "Max"
      }
     ]
    }
   ]
  },
  {
   "title": "Write Performance Benchmarking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "RABBITMQ Write Throughput MB/s",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      { "expr": "SBK_RABBITMQ_Writing_MBPerSec" }
     ]
    },
    {
     "title": "RABBITMQ Write Records/Sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "SBK_RABBITMQ_Writing_RecordsPerSec"
      }
     ]
    },
    {
     "title": "RABBITMQ Write Avg and Max Latencies (Nanoseconds)",
     "type": "stat",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_RABBITMQ_Writing_ns_AvgLatency",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_RABBITMQ_Writing_ns_MaxLatency",
       "legendFormat": "Max Latency"
      }
     ]
    },
    {
     "title": "RABBITMQ Write Percentiles (Nanoseconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      { "expr": "SBK_RABBITMQ_Writing_ns_10" },
      { "expr": "SBK_RABBITMQ_Writing_ns_25" },
      { "expr": "SBK_RABBITMQ_Writing_ns_50" },
      { "expr": "SBK_RABBITMQ_Writing_ns_75" },
      { "expr": "SBK_RABBITMQ_Writing_ns_90" },
      { "expr": "SBK_RABBITMQ_Writing_ns_95" },
      { "expr": "SBK_RABBITMQ_Writing_ns_99" },
      { "expr": "SBK_RABBITMQ_Writing_ns_99_9" },
      { "expr": "SBK_RABBITMQ_Writing_ns_99_99" }
     ]
    },
    {
     "title": "RABBITMQ Writers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_RABBITMQ_Writing_Writers", "legendFormat": "Active" },
      {
       "expr": "SBK_RABBITMQ_Writing_Max_Writers",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "RABBITMQ Write Throughput MB/s",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 11, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_RABBITMQ_Writing_MBPerSec" }
     ]
    },
    {
     "title": "RABBITMQ Write Percentiles (Milliseconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      { "expr": "SBK_RABBITMQ_Writing_ms_10" },
      { "expr": "SBK_RABBITMQ_Writing_ms_25" },
      { "expr": "SBK_RABBITMQ_Writing_ms_50" },
      { "expr": "SBK_RABBITMQ_Writing_ms_75" },
      { "expr": "SBK_RABBITMQ_Writing_ms_90" },
      { "expr": "SBK_RABBITMQ_Writing_ms_95" },
      { "expr": "SBK_RABBITMQ_Writing_ms_99" },
      { "expr": "SBK_RABBITMQ_Writing_ms_99_9" },
      { "expr": "SBK_RABBITMQ_Writing_ms_99_99" }
     ]
    },
    {
     "title": "RABBITMQ Write Bytes Total",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_RABBITMQ_Writing_Records_total"
      }
     ]
    },
    {
     "title": "RABBITMQ Write Discarded Latencies",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 11, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_RABBITMQ_Reading_LowerDiscardedLatencyRecords_total",
       "legendFormat": "Lower"
      },
      {
       "expr": "SBK_RABBITMQ_Reading_HigherDiscardLatencyRecords_total",
       "legendFormat": "Higher"
      },
      {
       "expr": "SBK_RABBITMQ_Reading_InvalidLatencyRecords_total",
       "legendFormat": "Invalid/Negative"
      }
     ]
    },
    {
     "title": "RABBITMQ Write Avg and Max Latencies (Microseconds)",
     "type": "stat",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_RABBITMQ_Writing_mcs_AvgLatency",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_RABBITMQ_Writing_mcs_MaxLatency",
       "legendFormat": "Max Latency"
      }
     ]
    },
    {
     "title": "RABBITMQ Write Percentiles (Microseconds)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      { "expr": "SBK_RABBITMQ_Writing_mcs_10" },
      { "expr": "SBK_RABBITMQ_Writing_mcs_25" },
      { "expr": "SBK_RABBITMQ_Writing_mcs_50" },
      { "expr": "SBK_RABBITMQ_Writing_mcs_75" },
      { "expr": "SBK_RABBITMQ_Writing_mcs_90" },
      { "expr": "SBK_RABBITMQ_Writing_mcs_95" },
      { "expr": "SBK_RABBITMQ_Writing_mcs_99" },
      { "expr": "SBK_RABBITMQ_Writing_mcs_99_9" },
      { "expr": "SBK_RABBITMQ_Writing_mcs_99_99" }
     ]
    },
    {
     "title": "RABBITMQ Write Avg and Max Latencies (Milliseconds)",
     "type": "stat",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_RABBITMQ_Writing_ms_AvgLatency",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_RABBITMQ_Writing_ms_MaxLatency",
       "legendFormat": "Max Latency"
      }
     ]
    }
   ]
  },
  {
   "title": "Read Performance Benchmarking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "RABBITMQ Read Throughput MB/s",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      { "expr": "SBK_RABBITMQ_Reading_MBPerSec" }
     ]
    },
    {
     "title": "RABBITMQ Read Records/Sec",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "SBK_RABBITMQ_Reading_RecordsPerSec"
      }
     ]
    },
    {
     "title": "RABBITMQ Read Avg and Max Latencies (Nanoseconds)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_RABBITMQ_Reading_ns_AvgLatency",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_RABBITMQ_Reading_ns_MaxLatency",
       "legendFormat": "Max Latency"
      }
     ]
    },
    {
     "title": "RABBITMQ Read Percentiles (Nanoseconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      { "expr": "SBK_RABBITMQ_Reading_ns_10" },
      { "expr": "SBK_RABBITMQ_Reading_ns_25" },
      { "expr": "SBK_RABBITMQ_Reading_ns_50" },
      { "expr": "SBK_RABBITMQ_Reading_ns_75" },
      { "expr": "SBK_RABBITMQ_Reading_ns_90" },
      { "expr": "SBK_RABBITMQ_Reading_ns_95" },
      { "expr": "SBK_RABBITMQ_Reading_ns_99" },
      { "expr": "SBK_RABBITMQ_Reading_ns_99_9" },
      { "expr": "SBK_RABBITMQ_Reading_ns_99_99" }
     ]
    },
    {
     "title": "RABBITMQ Readers",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_RABBITMQ_Reading_Readers", "legendFormat": "Active" },
      {
       "expr": "SBK_RABBITMQ_Reading_Max_Readers",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "RABBITMQ Read Throughput MB/s",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 11, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_RABBITMQ_Reading_MBPerSec" }
     ]
    },
    {
     "title": "RABBITMQ Read Percentiles (Milli Seconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      { "expr": "SBK_RABBITMQ_Reading_ms_10" },
      { "expr": "SBK_RABBITMQ_Reading_ms_25" },
      { "expr": "SBK_RABBITMQ_Reading_ms_50" },
      { "expr": "SBK_RABBITMQ_Reading_ms_75" },
      { "expr": "SBK_RABBITMQ_Reading_ms_90" },
      { "expr": "SBK_RABBITMQ_Reading_ms_95" },
      { "expr": "SBK_RABBITMQ_Reading_ms_99" },
      { "expr": "SBK_RABBITMQ_Reading_ms_99_9" },
      { "expr": "SBK_RABBITMQ_Reading_ms_99_99" }
     ]
    },
    {
     "title": "RABBITMQ Read Bytes Total",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_RABBITMQ_Reading_Bytes_total"
      }
     ]
    },
    {
     "title": "RABBITMQ Read Discarded Latencies",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 11, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_RABBITMQ_Reading_LowerDiscardedLatencyRecords_total",
       "legendFormat": "Lower"
      },
      {
       "expr": "SBK_RABBITMQ_Reading_HigherDiscardLatencyRecords_total",
       "legendFormat": "Higher"
      },
      {
       "expr": "SBK_RABBITMQ_Reading_InvalidLatencyRecords_total",
       "legendFormat": "Invalid/Negative"
      }
     ]
    },
    {
     "title": "RABBITMQ Read Avg and Max Latencies (Microseconds)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_RABBITMQ_Reading_mcs_AvgLatency",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_RABBITMQ_Reading_mcs_MaxLatency",
       "legendFormat": "Max Latency"
      }
     ]
    },
    {
     "title": "RABBITMQ Read Percentiles (Microseconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 33 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      { "expr": "SBK_RABBITMQ_Reading_mcs_10" },
      { "expr": "SBK_RABBITMQ_Reading_mcs_25" },
      { "expr": "SBK_RABBITMQ_Reading_mcs_50" },
      { "expr": "SBK_RABBITMQ_Reading_mcs_75" },
      { "expr": "SBK_RABBITMQ_Reading_mcs_90" },
      { "expr": "SBK_RABBITMQ_Reading_mcs_95" },
      { "expr": "SBK_RABBITMQ_Reading_mcs_99" },
      { "expr": "SBK_RABBITMQ_Reading_mcs_99_9" },
      { "expr": "SBK_RABBITMQ_Reading_mcs_99_99" }
     ]
    },
    {
     "title": "RABBITMQ Read Avg and Max Latencies (Milliseconds)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_RABBITMQ_Reading_ms_AvgLatency",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_RABBITMQ_Reading_ms_MaxLatency",
       "legendFormat": "Max Latency"
      }
     ]
    }
   ]
  },
  {
   "title": "Write-Read Performance Benchmarking (End to End Latencies)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "RABBITMQ Write-Read Throughput MB/s ",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      {
       "expr": "SBK_RABBITMQ_Write_Reading_MBPerSec"
      }
     ]
    },
    {
     "title": "RABBITMQ Write-Read Records/Sec",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "SBK_RABBITMQ_Write_Reading_RecordsPerSec"
      }
     ]
    },
    {
     "title": "RABBITMQ Write-Read Avg and Max Latencies (Nanoseconds)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_RABBITMQ_Write_Reading_ns_AvgLatency",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_ns_MaxLatency",
       "legendFormat": "Max Latency"
      }
     ]
    },
    {
     "title": "RABBITMQ Write-Read Percentiles (Nanoseconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "SBK_RABBITMQ_Write_Reading_ns_10"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_ns_25"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_ns_50"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_ns_75"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_ns_90"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_ns_95"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_ns_99"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_ns_99_9"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_ns_99_99"
      }
     ]
    },
    {
     "title": "RABBITMQ Write-Read Bytes Total",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_RABBITMQ_Write_Reading_Bytes_total"
      }
     ]
    },
    {
     "title": "RABBITMQ Write-Read Throughput MB/s",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 11, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_RABBITMQ_Write_Reading_MBPerSec"
      }
     ]
    },
    {
     "title": "RABBITMQ Write-Read Percentiles (Milliseconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "SBK_RABBITMQ_Write_Reading_ms_10"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_ms_25"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_ms_50"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_ms_75"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_ms_90"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_ms_95"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_ms_99"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_ms_99_9"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_ms_99_99"
      }
     ]
    },
    {
     "title": "RABBITMQ Write-Read  Writers and Readers",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_RABBITMQ_Write_Reading_Readers",
       "legendFormat": "Active Readers"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_Max_Readers",
       "legendFormat": "Max Readers"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_Writers",
       "legendFormat": "Active Writers"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_Max_Writers",
       "legendFormat": "Max Writers"
      }
     ]
    },
    {
     "title": "RABBITMQ Write-Read  Discarded Latencies",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 11, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_RABBITMQ_Write_Reading_LowerDiscardedLatencyRecords_total",
       "legendFormat": "Lower"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_HigherDiscardLatencyRecords_total",
       "legendFormat": "Higher"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_InvalidLatencyRecords_total",
       "legendFormat": "Invalid/Negative"
      }
     ]
    },
    {
     "title": "RABBITMQ Write-Read Avg and Max Latencies (Microseconds)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_RABBITMQ_Write_Reading_mcs_AvgLatency",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_mcs_MaxLatency",
       "legendFormat": "Max Latency"
      }
     ]
    },
    {
     "title": "RABBITMQ Write-Read Percentiles (Microseconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "SBK_RABBITMQ_Write_Reading_mcs_10"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_mcs_25"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_mcs_50"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_mcs_75"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_mcs_90"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_mcs_95"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_mcs_99"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_mcs_99_9"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_mcs_99_99"
      }
     ]
    },
    {
     "title": "RABBITMQ Write-Read Avg and Max Latencies (Milliseconds)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_RABBITMQ_Write_Reading_ms_AvgLatency",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_RABBITMQ_Write_Reading_ms_MaxLatency",
       "legendFormat": "Max Latency"
      }
     ]
    }
   ]
  }
 ]
}