{
 "title": "SBK Seaweeds3 Dashboard",
 "tags": [ "SBK" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "SBK Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Connections", "legendFormat": "Active" }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Max_Connections", "legendFormat": "Active" }
   ]
  },
  { "title": "SBK Readers and Writers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Active Readers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Readers", "legendFormat": "Active" }
   ]
  },
  {
   "title": "Max Readers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Max_Readers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Writers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Writers", "legendFormat": "Active" }
   ]
  },
  {
   "title": "Max Writers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Max_Writers", "legendFormat": "Active" }
   ]
  },
  { "title": "Write Performance Benchmarking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "SBK Seaweeds3 Write Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "SBK_Writing_MBPerSec{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_Request_Bytes_MBPerSec{class=\"Seaweeds3\"}"
    }
   ]
  },
  {
   "title": "SBK Seaweeds3 Write Records/Sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "SBK_Writing_RecordsPerSec{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_Request_RecordsPerSec{class=\"Seaweeds3\"}"
    }
   ]
  },
  {
   "title": "SBK Seaweeds3 Write Avg and Max Latencies (Nanoseconds)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Writing_ns_AvgLatency{class=\"Seaweeds3\"}",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_Writing_ns_MaxLatency{class=\"Seaweeds3\"}",
     "legendFormat": "Max Latency"
    }
   ]
  },
  {
   "title": "SBK Seaweeds3 Write Percentiles (Nanoseconds)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "SBK_Writing_ns_5{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Writing_ns_10{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Writing_ns_20{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Writing_ns_25{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Writing_ns_30{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Writing_ns_40{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Writing_ns_50{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Writing_ns_60{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Writing_ns_70{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Writing_ns_75{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Writing_ns_80{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Writing_ns_90{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Writing_ns_92_5{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Writing_ns_95{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Writing_ns_97_5{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Writing_ns_99{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Writing_ns_99_25{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Writing_ns_99_5{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Writing_ns_99_75{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Writing_ns_99_9{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Writing_ns_99_95{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Writing_ns_99_99{class=\"Seaweeds3\"}"
    }
   ]
  },
  {
   "title": "SBK Seaweeds3 Write Throughput MB/s",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Writing_MBPerSec{class=\"Seaweeds3\"}"
    }
   ]
  },
  {
   "title": "SBK Seaweeds3 Write  Sliding Latency Coverage (SLC)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Writing_SLC_1{class=\"Seaweeds3\"}",
     "legendFormat": "SLC 1"
    },
    {
     "expr": "SBK_Writing_SLC_2{class=\"Seaweeds3\"}",
     "legendFormat": "SLC 2"
    }
   ]
  },
  {
   "title": "SBK Seaweeds3 Write Bytes Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Writing_Bytes_total{class=\"Seaweeds3\"}",
     "legendFormat": "Write Bytes"
    },
    {
     "expr": "SBK_Write_Request_Bytes_total{class=\"Seaweeds3\"}",
     "legendFormat": "Write Request Bytes"
    }
   ]
  },
  {
   "title": "SBK Seaweeds3 Write Discarded Latencies",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Reading_LowerDiscardedLatencyRecords_total{class=\"Seaweeds3\"}",
     "legendFormat": "Lower"
    },
    {
     "expr": "SBK_Reading_HigherDiscardLatencyRecords_total{class=\"Seaweeds3\"}",
     "legendFormat": "Higher"
    },
    {
     "expr": "SBK_Reading_InvalidLatencyRecords_total{class=\"Seaweeds3\"}",
     "legendFormat": "Invalid/Negative"
    }
   ]
  },
  {
   "title": "Read Performance Benchmarking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "SBK Seaweeds3 Read Throughput MB/s",
     "type": "graph",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      {
       "expr": "SBK_Reading_MBPerSec{class=\"Seaweeds3\"}"
      },
      {
       "expr": "SBK_Read_Request_MBPerSec{class=\"Seaweeds3\"}"
      }
     ]
    },
    {
     "title": "SBK Seaweeds3 Read Records/Sec",
     "type": "graph",
     "gridPos": { "h": 13, "w": 8, "x": 8, "y": 37 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "SBK_Reading_RecordsPerSec{class=\"Seaweeds3\"}"
      },
      {
       "expr": "SBK_Read_Request_RecordsPerSec{class=\"Seaweeds3\"}"
      }
     ]
    },
    {
     "title": "SBK Seaweeds3 Read Avg and Max Latencies (Nanoseconds)",
     "type": "stat",
     "gridPos": { "h": 13, "w": 8, "x": 16, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Reading_ns_AvgLatency{class=\"Seaweeds3\"}",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_Reading_ns_MaxLatency{class=\"Seaweeds3\"}",
       "legendFormat": "Max Latency"
      }
     ]
    },
    {
     "title": "SBK Seaweeds3 Read Percentiles (Nanoseconds)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "SBK_Reading_ns_5{class=\"Seaweeds3\"}"
      },
      {
       "expr": "SBK_Reading_ns_10{class=\"Seaweeds3\"}"
      },
      {
       "expr": "SBK_Reading_ns_20{class=\"Seaweeds3\"}"
      },
      {
       "expr": "SBK_Reading_ns_25{class=\"Seaweeds3\"}"
      },
      {
       "expr": "SBK_Reading_ns_30{class=\"Seaweeds3\"}"
      },
      {
       "expr": "SBK_Reading_ns_40{class=\"Seaweeds3\"}"
      },
      {
       "expr": "SBK_Reading_ns_50{class=\"Seaweeds3\"}"
      },
      {
       "expr": "SBK_Reading_ns_60{class=\"Seaweeds3\"}"
      },
      {
       "expr": "SBK_Reading_ns_70{class=\"Seaweeds3\"}"
      },
      {
       "expr": "SBK_Reading_ns_75{class=\"Seaweeds3\"}"
      },
      {
       "expr": "SBK_Reading_ns_80{class=\"Seaweeds3\"}"
      },
      {
       "expr": "SBK_Reading_ns_90{class=\"Seaweeds3\"}"
      },
      {
       "expr": "SBK_Reading_ns_92_25{class=\"Seaweeds3\"}"
      },
      {
       "expr": "SBK_Reading_ns_95{class=\"Seaweeds3\"}"
      },
      {
       "expr": "SBK_Reading_ns_97_5{class=\"Seaweeds3\"}"
      },
      {
       "expr": "SBK_Reading_ns_99{class=\"Seaweeds3\"}"
      },
      {
       "expr": "SBK_Reading_ns_99_25{class=\"Seaweeds3\"}"
      },
      {
       "expr": "SBK_Reading_ns_99_5{class=\"Seaweeds3\"}"
      },
      {
       "expr": "SBK_Reading_ns_99_75{class=\"Seaweeds3\"}"
      },
      {
       "expr": "SBK_Reading_ns_99_9{class=\"Seaweeds3\"}"
      },
      {
       "expr": "SBK_Reading_ns_99_95{class=\"Seaweeds3\"}"
      },
      {
       "expr": "SBK_Reading_ns_99_99{class=\"Seaweeds3\"}"
      }
     ]
    },
    {
     "title": "SBK Seaweeds3 Read Throughput MB/s",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Reading_MBPerSec{class=\"Seaweeds3\"}"
      }
     ]
    },
    {
     "title": "SBK Seaweeds3 Read  Sliding Latency Coverage (SLC)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Reading_SLC_1{class=\"Seaweeds3\"}",
       "legendFormat": "SLC 1"
      },
      {
       "expr": "SBK_Reading_SLC_2{class=\"Seaweeds3\"}",
       "legendFormat": "SLC 2"
      }
     ]
    },
    {
     "title": "SBK Seaweeds3 Read Bytes Total",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Reading_Bytes_total{class=\"Seaweeds3\"}",
       "legendFormat": "Read Bytes"
      },
      {
       "expr": "SBK_Read_Request_Bytes_total{class=\"Seaweeds3\"}",
       "legendFormat": "Read Request Bytes"
      }
     ]
    },
    {
     "title": "SBK Seaweeds3 Read Discarded Latencies",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_Reading_LowerDiscardedLatencyRecords_total{class=\"Seaweeds3\"}",
       "legendFormat": "Lower"
      },
      {
       "expr": "SBK_Reading_HigherDiscardLatencyRecords_total{class=\"Seaweeds3\"}",
       "legendFormat": "Higher"
      },
      {
       "expr": "SBK_Reading_InvalidLatencyRecords_total{class=\"Seaweeds3\"}",
       "legendFormat": "Invalid/Negative"
      }
     ]
    }
   ]
  },
  {
   "title": "Write-Read Performance Benchmarking (End to End Latencies)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }
  },
  {
   "title": "SBK Seaweeds3 Write-Read Throughput MB/s ",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "SBK_Write_Reading_MBPerSec{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_Request_Bytes_MBPerSec{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Read_Request_Bytes_MBPerSec{class=\"Seaweeds3\"}"
    }
   ]
  },
  {
   "title": "SBK Seaweeds3 Write-Read Records/Sec",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "SBK_Write_Reading_RecordsPerSec{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_Request_RecordsPerSec{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Read_Request_RecordsPerSec{class=\"Seaweeds3\"}"
    }
   ]
  },
  {
   "title": "SBK Seaweeds3 Write-Read Avg and Max Latencies (Nanoseconds)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_Reading_ns_AvgLatency{class=\"Seaweeds3\"}",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_Write_Reading_ns_MaxLatency{class=\"Seaweeds3\"}",
     "legendFormat": "Max Latency"
    }
   ]
  },
  {
   "title": "SBK Seaweeds3 Write-Read Percentiles (Nanoseconds)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "SBK_Write_Reading_ns_5{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_10{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_20{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_25{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_30{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_40{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_50{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_60{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_70{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_75{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_80{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_90{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_92_5{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_95{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_97_5{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_99{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_99_25{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_99_5{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_99_75{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_99_9{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_99_95{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_99_99{class=\"Seaweeds3\"}"
    }
   ]
  },
  {
   "title": "SBK Seaweeds3 Write-Read Throughput MB/s",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_Reading_MBPerSec{class=\"Seaweeds3\"}"
    }
   ]
  },
  {
   "title": "SBK Seaweeds3 Write-Read Sliding Latency Coverage (SLC)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_Reading_SLC_1{class=\"Seaweeds3\"}",
     "legendFormat": "SLC 1"
    },
    {
     "expr": "SBK_Write_Reading_SLC_2{class=\"Seaweeds3\"}",
     "legendFormat": "SLC 2"
    }
   ]
  },
  {
   "title": "SBK Seaweeds3 Write Read Bytes Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_Reading_Bytes_total{class=\"Seaweeds3\"}",
     "legendFormat": "Write Reading Bytes"
    },
    {
     "expr": "SBK_Read_Request_Bytes_total{class=\"Seaweeds3\"}",
     "legendFormat": "Read Request Bytes"
    },
    {
     "expr": "SBK_Write_Request_Bytes_total{class=\"Seaweeds3\"}",
     "legendFormat": "Write Request Bytes"
    }
   ]
  },
  {
   "title": "SBK Seaweeds3 Write-Read  Discarded Latencies",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_Reading_LowerDiscardedLatencyRecords_total{class=\"Seaweeds3\"}",
     "legendFormat": "Lower"
    },
    {
     "expr": "SBK_Write_Reading_HigherDiscardLatencyRecords_total{class=\"Seaweeds3\"}",
     "legendFormat": "Higher"
    },
    {
     "expr": "SBK_Write_Reading_InvalidLatencyRecords_total{class=\"Seaweeds3\"}",
     "legendFormat": "Invalid/Negative"
    }
   ]
  },
  { "title": "Write-Only Read Benchmarking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "SBK Seaweeds3 Write-Only Read Throughput MB/s ",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_MBPerSec{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Read_Request_MBPerSec{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_Request_Bytes_MBPerSec{class=\"Seaweeds3\"}"
    }
   ]
  },
  {
   "title": "SBK Seaweeds3 Write-Only Read Records/Sec",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 63 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_RecordsPerSec{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Read_Request_RecordsPerSec{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_Request_RecordsPerSec{class=\"Seaweeds3\"}"
    }
   ]
  },
  {
   "title": "SBK Seaweeds3 Write-Only Read Avg and Max Latencies (Nanoseconds)",
   "type": "stat",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_ns_AvgLatency{class=\"Seaweeds3\"}",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_MaxLatency{class=\"Seaweeds3\"}",
     "legendFormat": "Max Latency"
    }
   ]
  },
  {
   "title": "SBK Seaweeds3 Write-Only Read Percentiles (Nanoseconds)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_ns_5{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_10{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_20{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_25{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_30{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_40{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_50{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_60{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_70{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_75{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_80{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_90{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_92_5{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_95{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_97_5{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_99{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_99_25{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_99_5{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_99_75{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_99_9{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_99_95{class=\"Seaweeds3\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_99_99{class=\"Seaweeds3\"}"
    }
   ]
  },
  {
   "title": "SBK Seaweeds3 Write-Only Read Throughput MB/s",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_MBPerSec{class=\"Seaweeds3\"}"
    }
   ]
  },
  {
   "title": "SBK Seaweeds3 Write-Only Read Sliding Latency Coverage (SLC)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_SLC_1{class=\"Seaweeds3\"}",
     "legendFormat": "SLC 1"
    },
    {
     "expr": "SBK_Write_OnlyReading_SLC_2{class=\"Seaweeds3\"}",
     "legendFormat": "SLC 2"
    }
   ]
  },
  {
   "title": "SBK Seaweeds3 Write-Only Read Bytes Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_Bytes_total{class=\"Seaweeds3\"}",
     "legendFormat": "Write Only Reading Bytes"
    },
    {
     "expr": "SBK_Read_Request_Bytes_total{class=\"Seaweeds3\"}",
     "legendFormat": "Read Request Bytes"
    },
    {
     "expr": "SBK_Write_Request_Bytes_total{class=\"Seaweeds3\"}",
     "legendFormat": "Write Request Bytes"
    }
   ]
  },
  {
   "title": "SBK Seaweeds3 Write-Only Read  Discarded Latencies",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_LowerDiscardedLatencyRecords_total{class=\"Seaweeds3\"}",
     "legendFormat": "Lower"
    },
    {
     "expr": "SBK_Write_OnlyReading_HigherDiscardLatencyRecords_total{class=\"Seaweeds3\"}",
     "legendFormat": "Higher"
    },
    {
     "expr": "SBK_Write_OnlyReading_InvalidLatencyRecords_total{class=\"Seaweeds3\"}",
     "legendFormat": "Invalid/Negative"
    }
   ]
  }
 ]
}