{
 "title": "SBK Minio Dashboard",
 "tags": [ "SBK" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "SBK Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Writers Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Writing_Connections", "legendFormat": "Active" },
    { "expr": "SBK_Writing_Max_Connections", "legendFormat": "Max" }
   ]
  },
  {
   "title": "Readers Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Reading_Connections", "legendFormat": "Active" },
    { "expr": "SBK_Reading_Max_Connections", "legendFormat": "Max" }
   ]
  },
  {
   "title": "Write-Readers Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Write_Reading_Connections", "legendFormat": "Active" },
    {
     "expr": "SBK_Write_Reading_Max_Connections",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "Write Performance Benchmarking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "SBK Minio Write Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "SBK_Writing_MBPerSec{class=\"Minio\"}"
    }
   ]
  },
  {
   "title": "SBK Minio Write Records/Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "SBK_Writing_RecordsPerSec{class=\"Minio\"}"
    }
   ]
  },
  {
   "title": "SBK Minio Write Avg and Max Latencies (Nanoseconds)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Writing_ns_AvgLatency{class=\"Minio\"}",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_Writing_ns_MaxLatency{class=\"Minio\"}",
     "legendFormat": "Max Latency"
    }
   ]
  },
  {
   "title": "SBK Minio Write Percentiles (Nanoseconds)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "SBK_Writing_ns_10{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_ns_20{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_ns_25{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_ns_30{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_ns_40{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_ns_50{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_ns_60{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_ns_70{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_ns_75{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_ns_80{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_ns_90{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_ns_92_5{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_ns_95{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_ns_97_5{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_ns_99{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_ns_99_25{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_ns_99_5{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_ns_99_75{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_ns_99_9{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_ns_99_95{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_ns_99_99{class=\"Minio\"}"
    }
   ]
  },
  {
   "title": "SBK Minio Writers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Writing_Writers{class=\"Minio\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "SBK_Writing_Max_Writers{class=\"Minio\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "SBK Minio Write Throughput MB/s",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Writing_MBPerSec{class=\"Minio\"}"
    }
   ]
  },
  {
   "title": "SBK Minio Write  Sliding Latency Coverage (SLC)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Writing_SLC_1{class=\"Minio\"}",
     "legendFormat": "SLC 1"
    },
    {
     "expr": "SBK_Writing_SLC_2{class=\"Minio\"}",
     "legendFormat": "SLC 2"
    }
   ]
  },
  {
   "title": "SBK Minio Write Bytes Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Writing_Records_total{class=\"Minio\"}"
    }
   ]
  },
  {
   "title": "SBK Minio Write Discarded Latencies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Reading_LowerDiscardedLatencyRecords_total{class=\"Minio\"}",
     "legendFormat": "Lower"
    },
    {
     "expr": "SBK_Reading_HigherDiscardLatencyRecords_total{class=\"Minio\"}",
     "legendFormat": "Higher"
    },
    {
     "expr": "SBK_Reading_InvalidLatencyRecords_total{class=\"Minio\"}",
     "legendFormat": "Invalid/Negative"
    }
   ]
  },
  {
   "title": "SBK Minio Write Avg and Max Latencies (Microseconds)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Writing_mcs_AvgLatency{class=\"Minio\"}",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_Writing_mcs_MaxLatency{class=\"Minio\"}",
     "legendFormat": "Max Latency"
    }
   ]
  },
  {
   "title": "SBK Minio Write Percentiles (Microseconds)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "SBK_Writing_mcs_10{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_mcs_25{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_mcs_50{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_mcs_75{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_mcs_90{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_mcs_95{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_mcs_99{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_mcs_99_9{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_mcs_99_99{class=\"Minio\"}"
    }
   ]
  },
  {
   "title": "SBK Minio Write Percentiles (Milliseconds)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "SBK_Writing_ms_10{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_ms_25{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_ms_50{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_ms_75{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_ms_90{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_ms_95{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_ms_99{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_ms_99_9{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Writing_ms_99_99{class=\"Minio\"}"
    }
   ]
  },
  {
   "title": "SBK Minio Write Avg and Max Latencies (Milliseconds)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Writing_ms_AvgLatency{class=\"Minio\"}",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_Writing_ms_MaxLatency{class=\"Minio\"}",
     "legendFormat": "Max Latency"
    }
   ]
  },
  { "title": "Read Performance Benchmarking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "SBK Minio Read Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "SBK_Reading_MBPerSec{class=\"Minio\"}"
    }
   ]
  },
  {
   "title": "SBK Minio Read Records/Sec",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "SBK_Reading_RecordsPerSec{class=\"Minio\"}"
    }
   ]
  },
  {
   "title": "SBK Minio Read Avg and Max Latencies (Nanoseconds)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Reading_ns_AvgLatency{class=\"Minio\"}",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_Reading_ns_MaxLatency{class=\"Minio\"}",
     "legendFormat": "Max Latency"
    }
   ]
  },
  {
   "title": "SBK Minio Read Percentiles (Nanoseconds)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "SBK_Reading_ns_10{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_ns_20{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_ns_25{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_ns_30{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_ns_40{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_ns_50{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_ns_60{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_ns_70{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_ns_75{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_ns_80{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_ns_90{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_ns_92_25{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_ns_95{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_ns_97_5{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_ns_99{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_ns_99_25{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_ns_99_5{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_ns_99_75{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_ns_99_9{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_ns_99_95{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_ns_99_99{class=\"Minio\"}"
    }
   ]
  },
  {
   "title": "SBK Minio Readers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Reading_Readers{class=\"Minio\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "SBK_Reading_Max_Readers{class=\"Minio\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "SBK Minio Read Throughput MB/s",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Reading_MBPerSec{class=\"Minio\"}"
    }
   ]
  },
  {
   "title": "SBK Minio Read  Sliding Latency Coverage (SLC)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Reading_SLC_1{class=\"Minio\"}",
     "legendFormat": "SLC 1"
    },
    {
     "expr": "SBK_Reading_SLC_2{class=\"Minio\"}",
     "legendFormat": "SLC 2"
    }
   ]
  },
  {
   "title": "SBK Minio Read Bytes Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Reading_Bytes_total{class=\"Minio\"}"
    }
   ]
  },
  {
   "title": "SBK Minio Read Discarded Latencies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Reading_LowerDiscardedLatencyRecords_total{class=\"Minio\"}",
     "legendFormat": "Lower"
    },
    {
     "expr": "SBK_Reading_HigherDiscardLatencyRecords_total{class=\"Minio\"}",
     "legendFormat": "Higher"
    },
    {
     "expr": "SBK_Reading_InvalidLatencyRecords_total{class=\"Minio\"}",
     "legendFormat": "Invalid/Negative"
    }
   ]
  },
  {
   "title": "SBK Minio Read Avg and Max Latencies (Microseconds)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Reading_mcs_AvgLatency{class=\"Minio\"}",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_Reading_mcs_MaxLatency{class=\"Minio\"}",
     "legendFormat": "Max Latency"
    }
   ]
  },
  {
   "title": "SBK Minio Read Percentiles (Microseconds)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "SBK_Reading_mcs_10{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_mcs_25{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_mcs_50{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_mcs_75{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_mcs_90{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_mcs_95{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_mcs_99{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_mcs_99_9{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_mcs_99_99{class=\"Minio\"}"
    }
   ]
  },
  {
   "title": "SBK Minio Read Percentiles (Milli Seconds)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 70 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "SBK_Reading_ms_10{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_ms_25{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_ms_50{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_ms_75{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_ms_90{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_ms_95{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_ms_99{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_ms_99_9{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Reading_ms_99_99{class=\"Minio\"}"
    }
   ]
  },
  {
   "title": "SBK Minio Read Avg and Max Latencies (Milliseconds)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Reading_ms_AvgLatency{class=\"Minio\"}",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_Reading_ms_MaxLatency{class=\"Minio\"}",
     "legendFormat": "Max Latency"
    }
   ]
  },
  {
   "title": "Write-Read Performance Benchmarking (End to End Latencies)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 }
  },
  {
   "title": "SBK Minio Write-Read Throughput MB/s ",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "SBK_Write_Reading_MBPerSec{class=\"Minio\"}"
    }
   ]
  },
  {
   "title": "SBK Minio Write-Read Records/Sec",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 93 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "SBK_Write_Reading_RecordsPerSec{class=\"Minio\"}"
    }
   ]
  },
  {
   "title": "SBK Minio Write-Read Avg and Max Latencies (Nanoseconds)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_Reading_ns_AvgLatency{class=\"Minio\"}",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_Write_Reading_ns_MaxLatency{class=\"Minio\"}",
     "legendFormat": "Max Latency"
    }
   ]
  },
  {
   "title": "SBK Minio Write-Read Percentiles (Nanoseconds)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "SBK_Write_Reading_ns_10{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_20{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_25{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_30{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_40{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_50{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_60{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_70{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_75{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_80{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_90{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_92_5{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_95{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_97_5{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_99{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_99_25{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_99_5{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_99_75{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_99_9{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_99_95{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_99_99{class=\"Minio\"}"
    }
   ]
  },
  {
   "title": "SBK Minio Write-Read Bytes Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_Reading_Bytes_total{class=\"Minio\"}"
    }
   ]
  },
  {
   "title": "SBK Minio Write-Read Throughput MB/s",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_Reading_MBPerSec{class=\"Minio\"}"
    }
   ]
  },
  {
   "title": "SBK Minio Write-Read Sliding Latency Coverage (SLC)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_Reading_SLC_1{class=\"Minio\"}",
     "legendFormat": "SLC 1"
    },
    {
     "expr": "SBK_Write_Reading_SLC_2{class=\"Minio\"}",
     "legendFormat": "SLC 2"
    }
   ]
  },
  {
   "title": "SBK Minio Write-Read  Writers and Readers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_Reading_Readers{class=\"Minio\"}",
     "legendFormat": "Active Readers"
    },
    {
     "expr": "SBK_Write_Reading_Max_Readers{class=\"Minio\"}",
     "legendFormat": "Max Readers"
    },
    {
     "expr": "SBK_Write_Reading_Writers{class=\"Minio\"}",
     "legendFormat": "Active Writers"
    },
    {
     "expr": "SBK_Write_Reading_Max_Writers{class=\"Minio\"}",
     "legendFormat": "Max Writers"
    }
   ]
  },
  {
   "title": "SBK Minio Write-Read  Discarded Latencies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_Reading_LowerDiscardedLatencyRecords_total{class=\"Minio\"}",
     "legendFormat": "Lower"
    },
    {
     "expr": "SBK_Write_Reading_HigherDiscardLatencyRecords_total{class=\"Minio\"}",
     "legendFormat": "Higher"
    },
    {
     "expr": "SBK_Write_Reading_InvalidLatencyRecords_total{class=\"Minio\"}",
     "legendFormat": "Invalid/Negative"
    }
   ]
  },
  {
   "title": "SBK Minio Write-Read Avg and Max Latencies (Microseconds)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_Reading_mcs_AvgLatency{class=\"Minio\"}",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_Write_Reading_mcs_MaxLatency{class=\"Minio\"}",
     "legendFormat": "Max Latency"
    }
   ]
  },
  {
   "title": "SBK Minio Write-Read Percentiles (Microseconds)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 115 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "SBK_Write_Reading_mcs_10{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_mcs_25{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_mcs_50{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_mcs_75{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_mcs_90{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_mcs_95{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_mcs_99{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_mcs_99_9{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_mcs_99_99{class=\"Minio\"}"
    }
   ]
  },
  {
   "title": "SBK Minio Write-Read Percentiles (Milliseconds)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 115 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "SBK_Write_Reading_ms_10{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_ms_25{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_ms_50{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_ms_75{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_ms_90{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_ms_95{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_ms_99{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_ms_99_9{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_Reading_ms_99_99{class=\"Minio\"}"
    }
   ]
  },
  {
   "title": "SBK Minio Write-Read Avg and Max Latencies (Milliseconds)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_Reading_ms_AvgLatency{class=\"Minio\"}",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_Write_Reading_ms_MaxLatency{class=\"Minio\"}",
     "legendFormat": "Max Latency"
    }
   ]
  },
  { "title": "Write-Only Read Benchmarking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 } },
  {
   "title": "SBK Minio Write-Only Read Throughput MB/s ",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_MBPerSec{class=\"Minio\"}"
    }
   ]
  },
  {
   "title": "SBK Minio Write-Only Read Records/Sec",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 138 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_RecordsPerSec{class=\"Minio\"}"
    }
   ]
  },
  {
   "title": "SBK Minio Write-Only Read Avg and Max Latencies (Nanoseconds)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_ns_AvgLatency{class=\"Minio\"}",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_MaxLatency{class=\"Minio\"}",
     "legendFormat": "Max Latency"
    }
   ]
  },
  {
   "title": "SBK Minio Write-Only Read Percentiles (Nanoseconds)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 149 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_ns_10{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_20{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_25{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_30{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_40{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_50{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_60{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_70{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_75{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_80{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_90{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_92_5{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_95{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_97_5{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_99{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_99_25{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_99_5{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_99_75{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_99_9{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_99_95{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_99_99{class=\"Minio\"}"
    }
   ]
  },
  {
   "title": "SBK Minio Write-Only Read Bytes Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_Bytes_total{class=\"Minio\"}"
    }
   ]
  },
  {
   "title": "SBK Minio Write-Only Read Throughput MB/s",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_MBPerSec{class=\"Minio\"}"
    }
   ]
  },
  {
   "title": "SBK Minio Write-Only Read Sliding Latency Coverage (SLC)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_SLC_1{class=\"Minio\"}",
     "legendFormat": "SLC 1"
    },
    {
     "expr": "SBK_Write_OnlyReading_SLC_2{class=\"Minio\"}",
     "legendFormat": "SLC 2"
    }
   ]
  },
  {
   "title": "SBK Minio Write-Only Read  Writers and Readers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_Readers{class=\"Minio\"}",
     "legendFormat": "Active Readers"
    },
    {
     "expr": "SBK_Write_OnlyReading_Max_Readers{class=\"Minio\"}",
     "legendFormat": "Max Readers"
    },
    {
     "expr": "SBK_Write_OnlyReading_Writers{class=\"Minio\"}",
     "legendFormat": "Active Writers"
    },
    {
     "expr": "SBK_Write_OnlyReading_Max_Writers{class=\"Minio\"}",
     "legendFormat": "Max Writers"
    }
   ]
  },
  {
   "title": "SBK Minio Write-Only Read  Discarded Latencies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_LowerDiscardedLatencyRecords_total{class=\"Minio\"}",
     "legendFormat": "Lower"
    },
    {
     "expr": "SBK_Write_OnlyReading_HigherDiscardLatencyRecords_total{class=\"Minio\"}",
     "legendFormat": "Higher"
    },
    {
     "expr": "SBK_Write_OnlyReading_InvalidLatencyRecords_total{class=\"Minio\"}",
     "legendFormat": "Invalid/Negative"
    }
   ]
  },
  {
   "title": "SBK Minio Write-Only Read Avg and Max Latencies (Microseconds)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_mcs_AvgLatency{class=\"Minio\"}",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_Write_OnlyReading_mcs_MaxLatency{class=\"Minio\"}",
     "legendFormat": "Max Latency"
    }
   ]
  },
  {
   "title": "SBK Minio Write-Only Read Percentiles (Microseconds)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 160 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_mcs_10{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_mcs_25{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_mcs_50{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_mcs_75{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_mcs_90{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_mcs_95{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_mcs_99{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_mcs_99_9{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_mcs_99_99{class=\"Minio\"}"
    }
   ]
  },
  {
   "title": "SBK Minio Write-Only Read Percentiles (Milliseconds)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 160 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_ms_10{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ms_25{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ms_50{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ms_75{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ms_90{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ms_95{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ms_99{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ms_99_9{class=\"Minio\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ms_99_99{class=\"Minio\"}"
    }
   ]
  },
  {
   "title": "SBK Minio Write-Only Read Avg and Max Latencies (Milliseconds)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_ms_AvgLatency{class=\"Minio\"}",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_Write_OnlyReading_ms_MaxLatency{class=\"Minio\"}",
     "legendFormat": "Max Latency"
    }
   ]
  }
 ]
}