{
 "title": "SBK CONCURRENTQ Benchmark",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CONCURRENTQ Write Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "SBK_CONCURRENTQ_Writing_MBPerSec"
    }
   ]
  },
  {
   "title": "CONCURRENTQ Write Records/Sec",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "SBK_CONCURRENTQ_Writing_RecordsPerSec"
    }
   ]
  },
  {
   "title": "CONCURRENTQ Write Avg and Max Latencies",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "SBK_CONCURRENTQ_Writing_ms_AvgLatency"
    },
    {
     "expr": "SBK_CONCURRENTQ_Writing_ms_MaxLatency"
    }
   ]
  },
  {
   "title": "CONCURRENTQ Write Percentiles",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "SBK_CONCURRENTQ_Writing_ms_10" },
    { "expr": "SBK_CONCURRENTQ_Writing_ms_25" },
    { "expr": "SBK_CONCURRENTQ_Writing_ms_50" },
    { "expr": "SBK_CONCURRENTQ_Writing_ms_75" },
    { "expr": "SBK_CONCURRENTQ_Writing_ms_90" },
    { "expr": "SBK_CONCURRENTQ_Writing_ms_95" },
    { "expr": "SBK_CONCURRENTQ_Writing_ms_99" },
    {
     "expr": "SBK_CONCURRENTQ_Writing_ms_99_9"
    },
    {
     "expr": "SBK_CONCURRENTQ_Writing_ms_99_99"
    }
   ]
  },
  {
   "title": "CONCURRENTQ Write Bytes Total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "SBK_CONCURRENTQ_Writing_Records_total"
    }
   ]
  },
  {
   "title": "CONCURRENTQ Write Discarded Latencies",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_CONCURRENTQ_Writing_LowerDiscardedLatencyRecords_total"
    },
    {
     "expr": "SBK_CONCURRENTQ_Writing_HigherDiscardLatencyRecords_total"
    }
   ]
  },
  {
   "title": "CONCURRENTQ Writers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_CONCURRENTQ_Writing_Writers"
    }
   ]
  },
  {
   "title": "CONCURRENTQ Read Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "SBK_CONCURRENTQ_Reading_MBPerSec"
    }
   ]
  },
  {
   "title": "CONCURRENTQ Read Records/Sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "SBK_CONCURRENTQ_Reading_RecordsPerSec"
    }
   ]
  },
  {
   "title": "CONCURRENTQ Read Avg and Max Latencies",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "SBK_CONCURRENTQ_Reading_ms_AvgLatency"
    },
    {
     "expr": "SBK_CONCURRENTQ_Reading_ms_MaxLatency"
    }
   ]
  },
  {
   "title": "CONCURRENTQ Read Percentiles",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "SBK_CONCURRENTQ_Reading_ms_10" },
    { "expr": "SBK_CONCURRENTQ_Reading_ms_25" },
    { "expr": "SBK_CONCURRENTQ_Reading_ms_50" },
    { "expr": "SBK_CONCURRENTQ_Reading_ms_75" },
    { "expr": "SBK_CONCURRENTQ_Reading_ms_90" },
    { "expr": "SBK_CONCURRENTQ_Reading_ms_95" },
    { "expr": "SBK_CONCURRENTQ_Reading_ms_99" },
    {
     "expr": "SBK_CONCURRENTQ_Reading_ms_99_9"
    },
    {
     "expr": "SBK_CONCURRENTQ_Reading_ms_99_99"
    }
   ]
  },
  {
   "title": "CONCURRENTQ Read Bytes Total",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "SBK_CONCURRENTQ_Reading_Bytes_total"
    }
   ]
  },
  {
   "title": "CONCURRENTQ Read Discarded Latencies",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_CONCURRENTQ_Reading_LowerDiscardedLatencyRecords_total"
    },
    {
     "expr": "SBK_CONCURRENTQ_Reading_HigherDiscardLatencyRecords_total"
    }
   ]
  },
  {
   "title": "CONCURRENTQ Readers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_CONCURRENTQ_Reading_Readers"
    }
   ]
  },
  {
   "title": "CONCURRENTQ Write-Read Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "SBK_CONCURRENTQ_Write_Reading_MBPerSec"
    }
   ]
  },
  {
   "title": "CONCURRENTQ Write-Read Records/Sec",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "SBK_CONCURRENTQ_Write_Reading_RecordsPerSec"
    }
   ]
  },
  {
   "title": "CONCURRENTQ Write-Read Avg and Max Latencies",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "SBK_CONCURRENTQ_Write_Reading_ms_AvgLatency"
    },
    {
     "expr": "SBK_CONCURRENTQ_Write_Reading_ms_MaxLatency"
    }
   ]
  },
  {
   "title": "CONCURRENTQ Write-Read Percentiles",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "SBK_CONCURRENTQ_Write_Reading_ms_10"
    },
    {
     "expr": "SBK_CONCURRENTQ_Write_Reading_ms_25"
    },
    {
     "expr": "SBK_CONCURRENTQ_Write_Reading_ms_50"
    },
    {
     "expr": "SBK_CONCURRENTQ_Write_Reading_ms_75"
    },
    {
     "expr": "SBK_CONCURRENTQ_Write_Reading_ms_90"
    },
    {
     "expr": "SBK_CONCURRENTQ_Write_Reading_ms_95"
    },
    {
     "expr": "SBK_CONCURRENTQ_Write_Reading_ms_99"
    },
    {
     "expr": "SBK_CONCURRENTQ_Write_Reading_ms_99_9"
    },
    {
     "expr": "SBK_CONCURRENTQ_Write_Reading_ms_99_99"
    }
   ]
  },
  {
   "title": "CONCURRENTQ Write-Read Bytes Total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "SBK_CONCURRENTQ_Write_Reading_Bytes_total"
    }
   ]
  },
  {
   "title": "CONCURRENTQ Write-Read  Discarded Latencies",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_CONCURRENTQ_Write_Reading_LowerDiscardedLatencyRecords_total"
    },
    {
     "expr": "SBK_CONCURRENTQ_Write_Reading_HigherDiscardLatencyRecords_total"
    }
   ]
  },
  {
   "title": "CONCURRENTQ Write-Read  Writers and Readers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_CONCURRENTQ_Write_Reading_Readers"
    },
    {
     "expr": "SBK_CONCURRENTQ_Write_Reading_Writers"
    }
   ]
  }
 ]
}