{
 "title": "SBK POSTGRESQL Benchmark",
 "tags": [ "SBK" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "SBK Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Writers Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_POSTGRESQL_Writing_Connections",
     "legendFormat": "Active"
    },
    {
     "expr": "SBK_POSTGRESQL_Writing_Max_Connections",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Readers Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_POSTGRESQL_Reading_Connections",
     "legendFormat": "Active"
    },
    {
     "expr": "SBK_POSTGRESQL_Reading_Max_Connections",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Write-Readers Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_Connections",
     "legendFormat": "Active"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_Max_Connections",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Write Performance Benchmarking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "POSTGRESQL Write Throughput MB/s",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      {
       "expr": "SBK_POSTGRESQL_Writing_MBPerSec"
      }
     ]
    },
    {
     "title": "POSTGRESQL Write Records/Sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "SBK_POSTGRESQL_Writing_RecordsPerSec"
      }
     ]
    },
    {
     "title": "POSTGRESQL Write Avg and Max Latencies (Nanoseconds)",
     "type": "stat",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_POSTGRESQL_Writing_ns_AvgLatency",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_POSTGRESQL_Writing_ns_MaxLatency",
       "legendFormat": "Max Latency"
      }
     ]
    },
    {
     "title": "POSTGRESQL Write Percentiles (Nanoseconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      { "expr": "SBK_POSTGRESQL_Writing_ns_10" },
      { "expr": "SBK_POSTGRESQL_Writing_ns_20" },
      { "expr": "SBK_POSTGRESQL_Writing_ns_25" },
      { "expr": "SBK_POSTGRESQL_Writing_ns_30" },
      { "expr": "SBK_POSTGRESQL_Writing_ns_40" },
      { "expr": "SBK_POSTGRESQL_Writing_ns_50" },
      { "expr": "SBK_POSTGRESQL_Writing_ns_60" },
      { "expr": "SBK_POSTGRESQL_Writing_ns_70" },
      { "expr": "SBK_POSTGRESQL_Writing_ns_75" },
      { "expr": "SBK_POSTGRESQL_Writing_ns_80" },
      { "expr": "SBK_POSTGRESQL_Writing_ns_90" },
      { "expr": "SBK_POSTGRESQL_Writing_ns_92_5" },
      { "expr": "SBK_POSTGRESQL_Writing_ns_95" },
      { "expr": "SBK_POSTGRESQL_Writing_ns_97_5" },
      { "expr": "SBK_POSTGRESQL_Writing_ns_99" },
      {
       "expr": "SBK_POSTGRESQL_Writing_ns_99_25"
      },
      { "expr": "SBK_POSTGRESQL_Writing_ns_99_5" },
      {
       "expr": "SBK_POSTGRESQL_Writing_ns_99_75"
      },
      { "expr": "SBK_POSTGRESQL_Writing_ns_99_9" },
      {
       "expr": "SBK_POSTGRESQL_Writing_ns_99_95"
      },
      {
       "expr": "SBK_POSTGRESQL_Writing_ns_99_99"
      }
     ]
    },
    {
     "title": "POSTGRESQL Writers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_POSTGRESQL_Writing_Writers", "legendFormat": "Active" },
      {
       "expr": "SBK_POSTGRESQL_Writing_Max_Writers",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "POSTGRESQL Write Throughput MB/s",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 11, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_POSTGRESQL_Writing_MBPerSec"
      }
     ]
    },
    {
     "title": "POSTGRESQL Write Percentiles (Milliseconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      { "expr": "SBK_POSTGRESQL_Writing_ms_10" },
      { "expr": "SBK_POSTGRESQL_Writing_ms_25" },
      { "expr": "SBK_POSTGRESQL_Writing_ms_50" },
      { "expr": "SBK_POSTGRESQL_Writing_ms_75" },
      { "expr": "SBK_POSTGRESQL_Writing_ms_90" },
      { "expr": "SBK_POSTGRESQL_Writing_ms_95" },
      { "expr": "SBK_POSTGRESQL_Writing_ms_99" },
      { "expr": "SBK_POSTGRESQL_Writing_ms_99_9" },
      {
       "expr": "SBK_POSTGRESQL_Writing_ms_99_99"
      }
     ]
    },
    {
     "title": "POSTGRESQL Write Bytes Total",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_POSTGRESQL_Writing_Records_total"
      }
     ]
    },
    {
     "title": "POSTGRESQL Write Discarded Latencies",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 11, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_POSTGRESQL_Reading_LowerDiscardedLatencyRecords_total",
       "legendFormat": "Lower"
      },
      {
       "expr": "SBK_POSTGRESQL_Reading_HigherDiscardLatencyRecords_total",
       "legendFormat": "Higher"
      },
      {
       "expr": "SBK_POSTGRESQL_Reading_InvalidLatencyRecords_total",
       "legendFormat": "Invalid/Negative"
      }
     ]
    },
    {
     "title": "POSTGRESQL Write Avg and Max Latencies (Microseconds)",
     "type": "stat",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_POSTGRESQL_Writing_mcs_AvgLatency",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_POSTGRESQL_Writing_mcs_MaxLatency",
       "legendFormat": "Max Latency"
      }
     ]
    },
    {
     "title": "POSTGRESQL Write Percentiles (Microseconds)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      { "expr": "SBK_POSTGRESQL_Writing_mcs_10" },
      { "expr": "SBK_POSTGRESQL_Writing_mcs_25" },
      { "expr": "SBK_POSTGRESQL_Writing_mcs_50" },
      { "expr": "SBK_POSTGRESQL_Writing_mcs_75" },
      { "expr": "SBK_POSTGRESQL_Writing_mcs_90" },
      { "expr": "SBK_POSTGRESQL_Writing_mcs_95" },
      { "expr": "SBK_POSTGRESQL_Writing_mcs_99" },
      {
       "expr": "SBK_POSTGRESQL_Writing_mcs_99_9"
      },
      {
       "expr": "SBK_POSTGRESQL_Writing_mcs_99_99"
      }
     ]
    },
    {
     "title": "POSTGRESQL Write Avg and Max Latencies (Milliseconds)",
     "type": "stat",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_POSTGRESQL_Writing_ms_AvgLatency",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_POSTGRESQL_Writing_ms_MaxLatency",
       "legendFormat": "Max Latency"
      }
     ]
    }
   ]
  },
  {
   "title": "Read Performance Benchmarking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "POSTGRESQL Read Throughput MB/s",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      {
       "expr": "SBK_POSTGRESQL_Reading_MBPerSec"
      }
     ]
    },
    {
     "title": "POSTGRESQL Read Records/Sec",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "SBK_POSTGRESQL_Reading_RecordsPerSec"
      }
     ]
    },
    {
     "title": "POSTGRESQL Read Avg and Max Latencies (Nanoseconds)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_POSTGRESQL_Reading_ns_AvgLatency",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_POSTGRESQL_Reading_ns_MaxLatency",
       "legendFormat": "Max Latency"
      }
     ]
    },
    {
     "title": "POSTGRESQL Read Percentiles (Nanoseconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      { "expr": "SBK_POSTGRESQL_Reading_ns_10" },
      { "expr": "SBK_POSTGRESQL_Reading_ns_20" },
      { "expr": "SBK_POSTGRESQL_Reading_ns_25" },
      { "expr": "SBK_POSTGRESQL_Reading_ns_30" },
      { "expr": "SBK_POSTGRESQL_Reading_ns_40" },
      { "expr": "SBK_POSTGRESQL_Reading_ns_50" },
      { "expr": "SBK_POSTGRESQL_Reading_ns_60" },
      { "expr": "SBK_POSTGRESQL_Reading_ns_70" },
      { "expr": "SBK_POSTGRESQL_Reading_ns_75" },
      { "expr": "SBK_POSTGRESQL_Reading_ns_80" },
      { "expr": "SBK_POSTGRESQL_Reading_ns_90" },
      {
       "expr": "SBK_POSTGRESQL_Reading_ns_92_25"
      },
      { "expr": "SBK_POSTGRESQL_Reading_ns_95" },
      { "expr": "SBK_POSTGRESQL_Reading_ns_97_5" },
      { "expr": "SBK_POSTGRESQL_Reading_ns_99" },
      {
       "expr": "SBK_POSTGRESQL_Reading_ns_99_25"
      },
      { "expr": "SBK_POSTGRESQL_Reading_ns_99_5" },
      {
       "expr": "SBK_POSTGRESQL_Reading_ns_99_75"
      },
      { "expr": "SBK_POSTGRESQL_Reading_ns_99_9" },
      {
       "expr": "SBK_POSTGRESQL_Reading_ns_99_95"
      },
      {
       "expr": "SBK_POSTGRESQL_Reading_ns_99_99"
      }
     ]
    },
    {
     "title": "POSTGRESQL Readers",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "SBK_POSTGRESQL_Reading_Readers", "legendFormat": "Active" },
      {
       "expr": "SBK_POSTGRESQL_Reading_Max_Readers",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "POSTGRESQL Read Throughput MB/s",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 11, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_POSTGRESQL_Reading_MBPerSec"
      }
     ]
    },
    {
     "title": "POSTGRESQL Read Percentiles (Milli Seconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      { "expr": "SBK_POSTGRESQL_Reading_ms_10" },
      { "expr": "SBK_POSTGRESQL_Reading_ms_25" },
      { "expr": "SBK_POSTGRESQL_Reading_ms_50" },
      { "expr": "SBK_POSTGRESQL_Reading_ms_75" },
      { "expr": "SBK_POSTGRESQL_Reading_ms_90" },
      { "expr": "SBK_POSTGRESQL_Reading_ms_95" },
      { "expr": "SBK_POSTGRESQL_Reading_ms_99" },
      { "expr": "SBK_POSTGRESQL_Reading_ms_99_9" },
      {
       "expr": "SBK_POSTGRESQL_Reading_ms_99_99"
      }
     ]
    },
    {
     "title": "POSTGRESQL Read Bytes Total",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_POSTGRESQL_Reading_Bytes_total"
      }
     ]
    },
    {
     "title": "POSTGRESQL Read Discarded Latencies",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 11, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_POSTGRESQL_Reading_LowerDiscardedLatencyRecords_total",
       "legendFormat": "Lower"
      },
      {
       "expr": "SBK_POSTGRESQL_Reading_HigherDiscardLatencyRecords_total",
       "legendFormat": "Higher"
      },
      {
       "expr": "SBK_POSTGRESQL_Reading_InvalidLatencyRecords_total",
       "legendFormat": "Invalid/Negative"
      }
     ]
    },
    {
     "title": "POSTGRESQL Read Avg and Max Latencies (Microseconds)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_POSTGRESQL_Reading_mcs_AvgLatency",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_POSTGRESQL_Reading_mcs_MaxLatency",
       "legendFormat": "Max Latency"
      }
     ]
    },
    {
     "title": "POSTGRESQL Read Percentiles (Microseconds)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      { "expr": "SBK_POSTGRESQL_Reading_mcs_10" },
      { "expr": "SBK_POSTGRESQL_Reading_mcs_25" },
      { "expr": "SBK_POSTGRESQL_Reading_mcs_50" },
      { "expr": "SBK_POSTGRESQL_Reading_mcs_75" },
      { "expr": "SBK_POSTGRESQL_Reading_mcs_90" },
      { "expr": "SBK_POSTGRESQL_Reading_mcs_95" },
      { "expr": "SBK_POSTGRESQL_Reading_mcs_99" },
      {
       "expr": "SBK_POSTGRESQL_Reading_mcs_99_9"
      },
      {
       "expr": "SBK_POSTGRESQL_Reading_mcs_99_99"
      }
     ]
    },
    {
     "title": "POSTGRESQL Read Avg and Max Latencies (Milliseconds)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "SBK_POSTGRESQL_Reading_ms_AvgLatency",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "SBK_POSTGRESQL_Reading_ms_MaxLatency",
       "legendFormat": "Max Latency"
      }
     ]
    }
   ]
  },
  {
   "title": "Write-Read Performance Benchmarking (End to End Latencies)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "POSTGRESQL Write-Read Throughput MB/s ",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_MBPerSec"
    }
   ]
  },
  {
   "title": "POSTGRESQL Write-Read Records/Sec",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_RecordsPerSec"
    }
   ]
  },
  {
   "title": "POSTGRESQL Write-Read Avg and Max Latencies (Nanoseconds)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ns_AvgLatency",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ns_MaxLatency",
     "legendFormat": "Max Latency"
    }
   ]
  },
  {
   "title": "POSTGRESQL Write-Read Percentiles (Nanoseconds)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ns_10"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ns_20"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ns_25"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ns_30"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ns_40"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ns_50"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ns_60"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ns_70"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ns_75"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ns_80"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ns_90"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ns_92_5"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ns_95"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ns_97_5"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ns_99"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ns_99_25"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ns_99_5"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ns_99_75"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ns_99_9"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ns_99_95"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ns_99_99"
    }
   ]
  },
  {
   "title": "POSTGRESQL Write-Read Bytes Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_Bytes_total"
    }
   ]
  },
  {
   "title": "POSTGRESQL Write-Read Throughput MB/s",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_MBPerSec"
    }
   ]
  },
  {
   "title": "POSTGRESQL Write-Read Percentiles (Milliseconds)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ms_10"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ms_25"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ms_50"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ms_75"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ms_90"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ms_95"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ms_99"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ms_99_9"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ms_99_99"
    }
   ]
  },
  {
   "title": "POSTGRESQL Write-Read  Writers and Readers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_Readers",
     "legendFormat": "Active Readers"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_Max_Readers",
     "legendFormat": "Max Readers"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_Writers",
     "legendFormat": "Active Writers"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_Max_Writers",
     "legendFormat": "Max Writers"
    }
   ]
  },
  {
   "title": "POSTGRESQL Write-Read  Discarded Latencies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_LowerDiscardedLatencyRecords_total",
     "legendFormat": "Lower"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_HigherDiscardLatencyRecords_total",
     "legendFormat": "Higher"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_InvalidLatencyRecords_total",
     "legendFormat": "Invalid/Negative"
    }
   ]
  },
  {
   "title": "POSTGRESQL Write-Read Avg and Max Latencies (Microseconds)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_mcs_AvgLatency",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_mcs_MaxLatency",
     "legendFormat": "Max Latency"
    }
   ]
  },
  {
   "title": "POSTGRESQL Write-Read Percentiles (Microseconds)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_mcs_10"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_mcs_25"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_mcs_50"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_mcs_75"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_mcs_90"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_mcs_95"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_mcs_99"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_mcs_99_9"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_mcs_99_99"
    }
   ]
  },
  {
   "title": "POSTGRESQL Write-Read Avg and Max Latencies (Milliseconds)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ms_AvgLatency",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_POSTGRESQL_Write_Reading_ms_MaxLatency",
     "legendFormat": "Max Latency"
    }
   ]
  }
 ]
}