{
 "title": "SBK Activemq Dashboard",
 "tags": [ "SBK" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "SBK Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Connections", "legendFormat": "Active" }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Max_Connections", "legendFormat": "Active" }
   ]
  },
  { "title": "SBK Readers and Writers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Active Readers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Readers", "legendFormat": "Active" }
   ]
  },
  {
   "title": "Max Readers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Max_Readers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Writers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Writers", "legendFormat": "Active" }
   ]
  },
  {
   "title": "Max Writers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "SBK_Max_Writers", "legendFormat": "Active" }
   ]
  },
  { "title": "Write Performance Benchmarking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "SBK Activemq Write Throughput MB/s",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "SBK_Writing_MBPerSec{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_Request_Bytes_MBPerSec{class=\"Activemq\", action=\"Writing\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Write Throughput MB/s",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "SBK_Writing_MBPerSec{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_Request_Bytes_MBPerSec{class=\"Activemq\", action=\"Writing\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Write Avg and Max Latencies (Nanoseconds)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Writing_ns_AvgLatency{class=\"Activemq\"}",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_Writing_ns_MaxLatency{class=\"Activemq\"}",
     "legendFormat": "Max Latency"
    }
   ]
  },
  {
   "title": "SBK Activemq Write Percentiles (Nanoseconds) 1",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "SBK_Writing_ns_5{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Writing_ns_10{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Writing_ns_20{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Writing_ns_25{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Writing_ns_30{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Writing_ns_40{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Writing_ns_50{class=\"Activemq\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Write Throughput MB/s",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Writing_MBPerSec{class=\"Activemq\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Write Percentiles (Nanoseconds) 2",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "SBK_Writing_ns_50{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Writing_ns_60{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Writing_ns_70{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Writing_ns_75{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Writing_ns_80{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Writing_ns_90{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Writing_ns_92_5{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Writing_ns_95{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Writing_ns_97_5{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Writing_ns_99{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Writing_ns_99_25{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Writing_ns_99_5{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Writing_ns_99_75{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Writing_ns_99_9{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Writing_ns_99_95{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Writing_ns_99_99{class=\"Activemq\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Write Response Pending Records",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "SBK_Write_Response_Pending_Records{class=\"Activemq\", action=\"Writing\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Write Response Pending Bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "SBK_Write_Response_Pending_Bytes{class=\"Activemq\", action=\"Writing\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Write  Sliding Latency Coverage (SLC)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Writing_SLC_1{class=\"Activemq\"}",
     "legendFormat": "SLC 1"
    },
    {
     "expr": "SBK_Writing_SLC_2{class=\"Activemq\"}",
     "legendFormat": "SLC 2"
    }
   ]
  },
  {
   "title": "SBK Activemq Write Bytes Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Writing_Bytes_total{class=\"Activemq\"}",
     "legendFormat": "Write Bytes"
    },
    {
     "expr": "SBK_Write_Request_Bytes_total{class=\"Activemq\", action=\"Writing\"}",
     "legendFormat": "Write Request Bytes"
    }
   ]
  },
  {
   "title": "SBK Activemq Write Discarded Latencies",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Reading_LowerDiscardedLatencyRecords_total{class=\"Activemq\"}",
     "legendFormat": "Lower"
    },
    {
     "expr": "SBK_Reading_HigherDiscardLatencyRecords_total{class=\"Activemq\"}",
     "legendFormat": "Higher"
    },
    {
     "expr": "SBK_Reading_InvalidLatencyRecords_total{class=\"Activemq\"}",
     "legendFormat": "Invalid/Negative"
    }
   ]
  },
  { "title": "Read Performance Benchmarking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "SBK Activemq Read Throughput MB/s",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "SBK_Reading_MBPerSec{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Read_Request_MBPerSec{class=\"Activemq\", action=\"Reading\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Read Records/Sec",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "SBK_Reading_RecordsPerSec{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Read_Request_RecordsPerSec{class=\"Activemq\", action=\"Reading\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Read Avg and Max Latencies (Nanoseconds)",
   "type": "stat",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Reading_ns_AvgLatency{class=\"Activemq\"}",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_Reading_ns_MaxLatency{class=\"Activemq\"}",
     "legendFormat": "Max Latency"
    }
   ]
  },
  {
   "title": "SBK Activemq Read Percentiles (Nanoseconds) 1",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "SBK_Reading_ns_5{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Reading_ns_10{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Reading_ns_20{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Reading_ns_25{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Reading_ns_30{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Reading_ns_40{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Reading_ns_50{class=\"Activemq\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Read Throughput MB/s",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Reading_MBPerSec{class=\"Activemq\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Read Percentiles (Nanoseconds) 2",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "SBK_Reading_ns_50{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Reading_ns_60{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Reading_ns_70{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Reading_ns_75{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Reading_ns_80{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Reading_ns_90{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Reading_ns_92_25{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Reading_ns_95{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Reading_ns_97_5{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Reading_ns_99{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Reading_ns_99_25{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Reading_ns_99_5{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Reading_ns_99_75{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Reading_ns_99_9{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Reading_ns_99_95{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Reading_ns_99_99{class=\"Activemq\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Read Response Pending Records",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "SBK_Read_Response_Pending_Records{class=\"Activemq\", action=\"Reading\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Read Response Pending Bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "SBK_Read_Response_Pending_Bytes{class=\"Activemq\", action=\"Reading\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Read Response Pending Bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "SBK_Read_Response_Pending_Bytes{class=\"Activemq\", action=\"Reading\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Read Bytes Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Reading_Bytes_total{class=\"Activemq\"}",
     "legendFormat": "Read Bytes"
    },
    {
     "expr": "SBK_Read_Request_Bytes_total{class=\"Activemq\", action=\"Reading\"}",
     "legendFormat": "Read Request Bytes"
    }
   ]
  },
  {
   "title": "SBK Activemq Read Discarded Latencies",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Reading_LowerDiscardedLatencyRecords_total{class=\"Activemq\"}",
     "legendFormat": "Lower"
    },
    {
     "expr": "SBK_Reading_HigherDiscardLatencyRecords_total{class=\"Activemq\"}",
     "legendFormat": "Higher"
    },
    {
     "expr": "SBK_Reading_InvalidLatencyRecords_total{class=\"Activemq\"}",
     "legendFormat": "Invalid/Negative"
    }
   ]
  },
  {
   "title": "Write-Read Performance Benchmarking (End to End Latencies)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 }
  },
  {
   "title": "SBK Activemq Write-Read Throughput MB/s ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "SBK_Write_Reading_MBPerSec{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_Request_Bytes_MBPerSec{class=\"Activemq\", action=\"Write_Reading\"}"
    },
    {
     "expr": "SBK_Read_Request_Bytes_MBPerSec{class=\"Activemq\", action=\"Write_Reading\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Write-Read Records/Sec",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "SBK_Write_Reading_RecordsPerSec{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_Request_RecordsPerSec{class=\"Activemq\", action=\"Write_Reading\"}"
    },
    {
     "expr": "SBK_Read_Request_RecordsPerSec{class=\"Activemq\", action=\"Write_Reading\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Write-Read Avg and Max Latencies (Nanoseconds)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_Reading_ns_AvgLatency{class=\"Activemq\"}",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_Write_Reading_ns_MaxLatency{class=\"Activemq\"}",
     "legendFormat": "Max Latency"
    }
   ]
  },
  {
   "title": "SBK Activemq Write-Read Percentiles (Nanoseconds) 1",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "SBK_Write_Reading_ns_5{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_10{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_20{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_25{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_30{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_40{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_50{class=\"Activemq\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Write-Read Throughput MB/s",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_Reading_MBPerSec{class=\"Activemq\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Write-Read Percentiles (Nanoseconds) 2",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "SBK_Write_Reading_ns_50{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_60{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_70{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_75{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_80{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_90{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_92_5{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_95{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_97_5{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_99{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_99_25{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_99_5{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_99_75{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_99_9{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_99_95{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_Reading_ns_99_99{class=\"Activemq\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Write Response Pending Records",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "SBK_Write_Response_Pending_Records{class=\"Activemq\", action=\"Write_Reading\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Write Response Pending Bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "SBK_Write_Response_Pending_Bytes{class=\"Activemq\", action=\"Write_Reading\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Read Response Pending Records",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "SBK_Read_Response_Pending_Records{class=\"Activemq\", action=\"Write_Reading\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Read Response Pending Bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "SBK_Read_Response_Pending_Bytes{class=\"Activemq\", action=\"Write_Reading\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Write Read Request Pending Records",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "SBK_Write_Read_Request_Pending_Records{class=\"Activemq\", action=\"Write_Reading\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Write Read Request Pending Bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "SBK_Write_Read_Request_Pending_Bytes{class=\"Activemq\", action=\"Write_Reading\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Write-Read Sliding Latency Coverage (SLC)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_Reading_SLC_1{class=\"Activemq\"}",
     "legendFormat": "SLC 1"
    },
    {
     "expr": "SBK_Write_Reading_SLC_2{class=\"Activemq\"}",
     "legendFormat": "SLC 2"
    }
   ]
  },
  {
   "title": "SBK Activemq Write-Read  Discarded Latencies",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_Reading_LowerDiscardedLatencyRecords_total{class=\"Activemq\"}",
     "legendFormat": "Lower"
    },
    {
     "expr": "SBK_Write_Reading_HigherDiscardLatencyRecords_total{class=\"Activemq\"}",
     "legendFormat": "Higher"
    },
    {
     "expr": "SBK_Write_Reading_InvalidLatencyRecords_total{class=\"Activemq\"}",
     "legendFormat": "Invalid/Negative"
    }
   ]
  },
  {
   "title": "SBK Activemq Write Read Bytes Total",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_Reading_Bytes_total{class=\"Activemq\"}",
     "legendFormat": "Write Reading Bytes"
    },
    {
     "expr": "SBK_Read_Request_Bytes_total{class=\"Activemq\", action=\"Write_Reading\"}",
     "legendFormat": "Read Request Bytes"
    },
    {
     "expr": "SBK_Write_Request_Bytes_total{class=\"Activemq\", action=\"Write_Reading\"}",
     "legendFormat": "Write Request Bytes"
    }
   ]
  },
  { "title": "Write-Only Read Benchmarking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 158 } },
  {
   "title": "SBK Activemq Write-Only Read Throughput MB/s ",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_MBPerSec{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Read_Request_MBPerSec{class=\"Activemq\", action=\"Write_OnlyReading\"}"
    },
    {
     "expr": "SBK_Write_Request_Bytes_MBPerSec{class=\"Activemq\", action=\"Write_OnlyReading\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Write-Only Read Records/Sec",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_RecordsPerSec{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Read_Request_RecordsPerSec{class=\"Activemq\",action=\"Write_OnlyReading\"}"
    },
    {
     "expr": "SBK_Write_Request_RecordsPerSec{class=\"Activemq\", action=\"Write_OnlyReading\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Write-Only Read Avg and Max Latencies (Nanoseconds)",
   "type": "stat",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_ns_AvgLatency{class=\"Activemq\"}",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_MaxLatency{class=\"Activemq\"}",
     "legendFormat": "Max Latency"
    }
   ]
  },
  {
   "title": "SBK Activemq Write-Only Read Percentiles (Nanoseconds) 1",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_ns_5{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_10{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_20{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_25{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_30{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_40{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_50{class=\"Activemq\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Write-Only Read Throughput MB/s",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_MBPerSec{class=\"Activemq\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Write-Only Read Percentiles (Nanoseconds) 2",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_ns_50{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_60{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_70{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_75{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_80{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_90{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_92_5{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_95{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_97_5{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_99{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_99_25{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_99_5{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_99_75{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_99_9{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_99_95{class=\"Activemq\"}"
    },
    {
     "expr": "SBK_Write_OnlyReading_ns_99_99{class=\"Activemq\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Write Response Pending Records",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "SBK_Write_Response_Pending_Records{class=\"Activemq\", action=\"Write_OnlyReading\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Write Response Pending Bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "SBK_Write_Response_Pending_Bytes{class=\"Activemq\", action=\"Write_OnlyReading\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Read Response Pending Records",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "SBK_Read_Response_Pending_Records{class=\"Activemq\", action=\"Write_OnlyReading\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Read Response Pending Bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "SBK_Read_Response_Pending_Bytes{class=\"Activemq\", action=\"Write_OnlyReading\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Write Read Request Pending Records",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "SBK_Write_Read_Request_Pending_Records{class=\"Activemq\", action=\"Write_OnlyReading\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Write Read Request Pending Bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "SBK_Write_Read_Request_Pending_Bytes{class=\"Activemq\", action=\"Write_OnlyReading\"}"
    }
   ]
  },
  {
   "title": "SBK Activemq Write-Only Read Sliding Latency Coverage (SLC)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 207 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_SLC_1{class=\"Activemq\"}",
     "legendFormat": "SLC 1"
    },
    {
     "expr": "SBK_Write_OnlyReading_SLC_2{class=\"Activemq\"}",
     "legendFormat": "SLC 2"
    }
   ]
  },
  {
   "title": "SBK Activemq Write-Only Read Bytes Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 207 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_Bytes_total{class=\"Activemq\"}",
     "legendFormat": "Write Only Reading Bytes"
    },
    {
     "expr": "SBK_Read_Request_Bytes_total{class=\"Activemq\", action=\"Write_OnlyReading\"}",
     "legendFormat": "Read Request Bytes"
    },
    {
     "expr": "SBK_Write_Request_Bytes_total{class=\"Activemq\", action=\"Write_OnlyReading\"}",
     "legendFormat": "Write Request Bytes"
    }
   ]
  },
  {
   "title": "SBK Activemq Write-Only Read  Discarded Latencies",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 207 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SBK_Write_OnlyReading_LowerDiscardedLatencyRecords_total{class=\"Activemq\"}",
     "legendFormat": "Lower"
    },
    {
     "expr": "SBK_Write_OnlyReading_HigherDiscardLatencyRecords_total{class=\"Activemq\"}",
     "legendFormat": "Higher"
    },
    {
     "expr": "SBK_Write_OnlyReading_InvalidLatencyRecords_total{class=\"Activemq\"}",
     "legendFormat": "Invalid/Negative"
    }
   ]
  }
 ]
}