plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    api project(":sbk-api")

    // Add your storage driver specific dependencies here
    // https://mvnrepository.com/artifact/org.apache.activemq/activemq-client
    implementation 'org.apache.activemq:activemq-client:5.17.0'
}
