kind: Job
apiVersion: batch/v1
metadata:
  name: sbk-rabbitmq-k8
spec:
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: sbk
          # SBK Image.
          image: kmgowda/sbk:10.6
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "2"
              memory: "1Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
          args: [
            "-class","rabbitmq",
            "-broker","$(RABBITMQ_BROKER)",
            "-topic","kmg-topic-1",
            "-writers","1",
            "-readers","1",
            "-size","10"
          ]
          env:
            - name: RABBITMQ_BROKER
              valueFrom:
                configMapKeyRef:
                  name: sbk-rabbitmq
                  key: broker
            - name: JAVA_OPTS
              value: "-Xmx1g -Xms1g"
          ports:
            - containerPort: 9718
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sbk-rabbitmq
data:
  broker: rabbitmq
