/**
 * Copyright (c) KMG. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 */

package io.sbk.driver.MinIO;

/**
 * Configuration for the MinIO / S3 driver.
 *
 * Mirrors the feature set of the Dell Storage Performance Tool (SPT)
 * S3 storage driver, so that SBK can perform comprehensive S3 benchmarks.
 */
public class MinIOConfig {

    // ----- Connection / credentials -----
    /** One S3 endpoint or a comma-separated endpoint list distributed across workers. */
    public String url;
    public String accessKey;
    public String secretKey;
    public String bucketName;
    public String region;
    public boolean reCreate;
    public boolean insecure;

    // ----- Workload operation -----
    /** Operation executed by writer workers. */
    public String writeOperation;
    /** Operation executed by reader workers. */
    public String readOperation;
    /** Weighted writer mix, for example put=80,copy=20. */
    public String writeMix;
    /** Weighted reader mix, for example get=90,stat=10. */
    public String readMix;
    /** Use MinioAsyncClient with bounded in-flight operations. */
    public boolean async;
    /** Maximum async operations in flight per SBK worker. */
    public int asyncDepth;
    /** Process-wide maximum in-flight operations; zero derives workers times depth. */
    public int asyncMaxInflight;
    /** Maximum estimated async buffer memory in MiB; zero disables the guard. */
    public long asyncMaxMemoryMb;

    // ----- Object naming / layout -----
    /** When true, use filesystem-style hierarchical object keys (e.g. "a/b/c-uuid"). */
    public boolean fsAccess;
    /** Optional key prefix for all generated objects. */
    public String prefix;
    /** Prefix used for destinations generated by copy operations. */
    public String copyPrefix;
    /** Offset used by ranged GET operations. */
    public long rangeOffset;
    /** Length used by ranged GET operations; 0 means the configured record size. */
    public long rangeLength;
    /** Maximum objects requested by each list benchmark operation. */
    public int listMaxKeys;
    /** Optional comma-separated LIST prefixes assigned across reader workers. */
    public String listPrefixes;
    /** Optional local object manifest used instead of an S3 startup listing. */
    public String objectFile;
    /** Maximum object references retained in the startup catalog. */
    public int catalogMaxObjects;
    /** Object size selection: fixed, uniform:min:max, sweep:min:max, or weighted:size=weight,... */
    public String objectSizeDistribution;
    /** Generated key selection: sequential, hashed, or random. */
    public String keyDistribution;
    /** Put each distributed partition under its own server-filterable prefix. */
    public boolean partitionByPrefix;

    // ----- Multipart upload (SPT: --part-size, --mpu-concurrent-parts) -----
    /** Part size in bytes; 0 disables multipart. SDK requires 5 MiB .. 5 GiB. */
    public long partSize;
    /** Max concurrent parts uploaded in parallel per object (0 = SDK default). */
    public int mpuConcurrentParts;

    // ----- S3 Checksum validation (SPT: --checksum) -----
    /** crc32, crc32c, sha1, sha256, crc64nvme. Empty/null disables. */
    public String checksumAlgorithm;

    // ----- Auth (SPT: --auth-version) -----
    /** Signature version. Only SigV4 is supported by the MinIO SDK. */
    public int authVersion;

    // ----- Object tagging (SPT: --tagging-*) -----
    public boolean taggingEnabled;
    /** Comma-separated `key=value` pairs (e.g. "env=prod,team=storage"). */
    public String taggingTags;

    // ----- Versioning (SPT: bucket versioning) -----
    public boolean versioningEnabled;

    // ----- Bucket operations -----
    /** Explicit comma-separated bucket targets used by bucket-delete/stat operations. */
    public String bucketTargets;
    /** Prefix used to generate bucket names for bucket-create operations. */
    public String bucketPrefix;
    /** Remove buckets generated by bucket-create when the benchmark closes. */
    public boolean cleanupCreatedBuckets;

    // ----- Data shaping (SPT: --object-data-compressibility, --object-data-dedupable) -----
    /** 0..100, target compressibility percentage. */
    public int dataCompressibility;
    /** When false, anti-dedup stamping is added every 4 KiB. */
    public boolean dataDedupable;
    /** Reproducible payload seed; zero chooses a runtime seed. */
    public long dataSeed;
    /** Validate consumed GET bytes against catalog/range expectations. */
    public boolean verifyReadSize;
    /** Total attempts for retryable SDK failures, including the first. */
    public int retryMaxAttempts;
    /** Fixed delay between retry attempts in milliseconds. */
    public long retryBackoffMs;
    /** Untimed bucket-existence requests used to warm connections before catalog discovery. */
    public int warmupRequests;
    /** Warmup operation: connection, put, get, or put-get. */
    public String warmupOperation;
    /** Collect completion, byte, retry, and failure totals by configured endpoint. */
    public boolean endpointMetrics;
    /** Total distributed partitions sharing the benchmark bucket. */
    public int partitionCount;
    /** Zero-based partition assigned to this process. */
    public int partitionIndex;
    /** Optional credential-free JSON run-manifest output path. */
    public String runManifest;

    // ----- Server-side encryption (SPT: SSE-S3) -----
    /** Enable server-side encryption with S3-managed keys (SSE-S3). */
    public boolean sseEnabled;

    // ----- HTTP client tuning -----
    /** Connect timeout in milliseconds (0 = SDK default). */
    public long connectTimeoutMs;
    /** Read/write timeout in milliseconds (0 = SDK default). */
    public long readTimeoutMs;
    /** Write timeout in milliseconds (0 = SDK default). */
    public long writeTimeoutMs;
    /** Maximum total asynchronous OkHttp requests (0 = derive from worker count/depth). */
    public int httpMaxRequests;
    /** Maximum asynchronous OkHttp requests per host (0 = derive from worker count/depth). */
    public int httpMaxRequestsPerHost;
    /** Maximum idle HTTP connections retained in the connection pool. */
    public int httpMaxIdleConnections;
    /** HTTP connection keep-alive duration in seconds. */
    public long httpKeepAliveSeconds;

    /**
     * Comma-separated {@code key=value} headers added to every S3 HTTP
     * request. Use this for backend-specific auth like Dell ECS /
     * ObjectScale: {@code -extra-headers "x-emc-namespace=myns"}.
     */
    public String extraHeaders;
}
