{
 "title": "SBK File Benchmark",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "File read Avg and Max latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_File_Reading_ms_AvgLatency" },
    { "expr": "SBK_File_Reading_ms_MaxLatency" }
   ]
  },
  {
   "title": "File Writing Records/Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_File_Writing_RecordsPerSec" }
   ]
  },
  {
   "title": "File Writing percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_File_Writing_ms_50th" },
    { "expr": "SBK_File_Writing_ms_75th" },
    { "expr": "SBK_File_Writing_ms_90th" },
    { "expr": "SBK_File_Writing_ms_99th" },
    { "expr": "SBK_File_Writing_ms_99_9th" },
    { "expr": "SBK_File_Writing_ms_99_99th" }
   ]
  },
  {
   "title": "File Reading Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_File_Reading_ms_50th" },
    { "expr": "SBK_File_Reading_ms_75th" },
    { "expr": "SBK_File_Reading_ms_90th" },
    { "expr": "SBK_File_Reading_ms_99th" },
    { "expr": "SBK_File_Reading_ms_99_9th" },
    { "expr": "SBK_File_Reading_ms_99_99th" }
   ]
  },
  {
   "title": "Writing Avg and Max latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_File_Writing_ms_AvgLatency" },
    { "expr": "SBK_File_Writing_ms_MaxLatency" }
   ]
  },
  {
   "title": "File Writers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_File_Writing_Writers" }
   ]
  },
  {
   "title": "File Read records/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_File_Reading_RecordsPerSec" }
   ]
  },
  {
   "title": "Write Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_File_Writing_MBPerSec" }
   ]
  },
  {
   "title": "File Read Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_File_Reading_MBPerSec" }
   ]
  },
  {
   "title": "File read bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_File_Reading_Bytes_total" }
   ]
  },
  {
   "title": "File Readers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_File_Reading_Readers" }
   ]
  },
  {
   "title": "Write Bytes Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_File_Writing_Records_total" }
   ]
  }
 ]
}