{
 "title": "SBK Pravega Benchmark",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pravega End to End latencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_Pravega_Write_Reading_50th" },
    { "expr": "SBK_Pravega_Write_Reading_75th" },
    { "expr": "SBK_Pravega_Write_Reading_90th" },
    { "expr": "SBK_Pravega_Write_Reading_99th" },
    { "expr": "SBK_Pravega_Reading_99_9th" },
    { "expr": "SBK_Pravega_Reading_99_99th" }
   ]
  },
  {
   "title": "Pravega readers Latencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_Pravega_Reading_50th" },
    { "expr": "SBK_Pravega_Reading_75th" },
    { "expr": "SBK_Pravega_Reading_90th" },
    { "expr": "SBK_Pravega_Reading_99th" },
    { "expr": "SBK_Pravega_Reading_99_9th" },
    { "expr": "SBK_Pravega_Reading_99_99th" }
   ]
  },
  {
   "title": "SBK_Pravega_Reading_RecordsPerSec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_Pravega_Reading_RecordsPerSec"
    }
   ]
  },
  {
   "title": "Pravega Avg and Max Read latencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_Pravega_Reading_AvgLatency" },
    { "expr": "SBK_Pravega_Reading_MaxLatency" }
   ]
  },
  {
   "title": "SBK_Pravega_Reading_Bytes_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_Pravega_Reading_Bytes_total"
    }
   ]
  },
  {
   "title": "Pravega Avg and Max Write latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_Pravega_Writing_AvgLatency" },
    { "expr": "SBK_Pravega_Writing_MaxLatency" }
   ]
  },
  {
   "title": "SBK_Pravega_Writing_Records_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_Pravega_Writing_Records_total"
    }
   ]
  },
  {
   "title": "SBK_Pravega_Writing_RecordsPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_Pravega_Writing_RecordsPerSec"
    }
   ]
  },
  {
   "title": "SBK_Pravega_Reading_MBPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_Pravega_Reading_MBPerSec" }
   ]
  },
  {
   "title": "Pravega Writers and Readers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_Pravega_Writing_Writers" },
    { "expr": "SBK_Pravega_Reading_Readers" }
   ]
  },
  {
   "title": "Pravega Writers Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_Pravega_Writing_MBPerSec" }
   ]
  },
  {
   "title": "Pravega Writer latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_Pravega_Writing_50th" },
    { "expr": "SBK_Pravega_Writing_75th" },
    { "expr": "SBK_Pravega_Writing_90th" },
    { "expr": "SBK_Pravega_Writing_99th" },
    { "expr": "SBK_Pravega_Writing_99_9th" },
    { "expr": "SBK_Pravega_Writing_99_99th" }
   ]
  }
 ]
}