{
 "title": "SBK Kafka Benchmark",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Kafka Readers Avg and Max latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_Kafka_Reading_AvgLatency" },
    { "expr": "SBK_Kafka_Reading_MaxLatency" }
   ]
  },
  {
   "title": "SBK_Kafka_Reading_RecordsPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_Kafka_Reading_RecordsPerSec"
    }
   ]
  },
  {
   "title": "Kafka Readers Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_Kafka_Reading_50th" },
    { "expr": "SBK_Kafka_Reading_75th" },
    { "expr": "SBK_Kafka_Reading_90th" },
    { "expr": "SBK_Kafka_Reading_99th" },
    { "expr": "SBK_Kafka_Reading_99_9th" },
    { "expr": "SBK_Kafka_Reading_99_99th" }
   ]
  },
  {
   "title": "SBK_Kafka_Reading_MBPerSec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_Kafka_Reading_MBPerSec" }
   ]
  },
  {
   "title": "Kafka Avg and Max latencies",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_Kafka_Writing_AvgLatency" },
    { "expr": "SBK_Kafka_Writing_MaxLatency" }
   ]
  },
  {
   "title": "Kafka Writers Latencies",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_Kafka_Writing_50th" },
    { "expr": "SBK_Kafka_Writing_75th" },
    { "expr": "SBK_Kafka_Writing_90th" },
    { "expr": "SBK_Kafka_Writing_99th" },
    { "expr": "SBK_Kafka_Writing_99_9th" },
    { "expr": "SBK_Kafka_Writing_99_99th" }
   ]
  },
  {
   "title": "SBK_Kafka_Writing_Bytes_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_Kafka_Writing_Bytes_total" }
   ]
  },
  {
   "title": "Kafka Writers and Readers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_Kafka_Writing_Writers" },
    { "expr": "SBK_Kafka_Reading_Readers" }
   ]
  },
  {
   "title": "SBK_Kafka_Writing_MBPerSec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_Kafka_Writing_MBPerSec" }
   ]
  },
  {
   "title": "Kafka End to End Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_Kafka_Write_Reading_50th" },
    { "expr": "SBK_Kafka_Write_Reading_75th" },
    { "expr": "SBK_Kafka_Write_Reading_90th" },
    { "expr": "SBK_Kafka_Write_Reading_99th" },
    { "expr": "SBK_Kafka_Write_Reading_99_9th" },
    {
     "expr": "SBK_Kafka_Write_Reading_99_99th"
    }
   ]
  }
 ]
}