{
 "title": "SBK Pulsar Benchmark",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pulsar End to End Latency percentiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_Pulsar_Write_Reading_50th" },
    { "expr": "SBK_Pulsar_Write_Reading_75th" },
    { "expr": "SBK_Pulsar_Write_Reading_90th" },
    { "expr": "SBK_Pulsar_Write_Reading_99th" },
    {
     "expr": "SBK_Pulsar_Write_Reading_99_9th"
    },
    {
     "expr": "SBK_Pulsar_Write_Reading_99_99th"
    }
   ]
  },
  {
   "title": "Pulsar Writer Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_Pulsar_Writing_Bytes_total" }
   ]
  },
  {
   "title": "Pulsar Writer Records/Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_Pulsar_Writing_RecordsPerSec"
    }
   ]
  },
  {
   "title": "Pulsar Reader Avg and Max latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_Pulsar_Reading_AvgLatency" },
    { "expr": "SBK_Pulsar_Reading_MaxLatency" }
   ]
  },
  {
   "title": "Pulsar Writers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_Pulsar_Writing_Writers" }
   ]
  },
  {
   "title": "Pulsar Writers Avg and Max Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_Pulsar_Writing_AvgLatency" },
    { "expr": "SBK_Pulsar_Writing_MaxLatency" }
   ]
  },
  {
   "title": "Pulsar Reading Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_Pulsar_Reading_50th" },
    { "expr": "SBK_Pulsar_Reading_75th" },
    { "expr": "SBK_Pulsar_Reading_90th" },
    { "expr": "SBK_Pulsar_Reading_99th" },
    { "expr": "SBK_Pulsar_Reading_99_9th" },
    { "expr": "SBK_Pulsar_Reading_99_99th" }
   ]
  },
  {
   "title": "Pulsar Read Records/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_Pulsar_Reading_RecordsPerSec"
    }
   ]
  },
  {
   "title": "Pulsar Read throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_Pulsar_Reading_MBPerSec" }
   ]
  },
  {
   "title": "Pulsar Readers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_Pulsar_Reading_Readers" }
   ]
  },
  {
   "title": "Pulsar Writing Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_Pulsar_Writing_50th" },
    { "expr": "SBK_Pulsar_Writing_75th" },
    { "expr": "SBK_Pulsar_Writing_90th" },
    { "expr": "SBK_Pulsar_Writing_99th" },
    { "expr": "SBK_Pulsar_Writing_99_9th" },
    { "expr": "SBK_Pulsar_Writing_99_99th" }
   ]
  },
  {
   "title": "Pulsar Write Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SBK_Pulsar_Writing_MBPerSec" }
   ]
  }
 ]
}