{
 "title": "SBK Concurrent Q Benchmark",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Concurrent Q  End to End Latencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_ConcurrentQ_Write_Reading_50th"
    },
    {
     "expr": "SBK_ConcurrentQ_Write_Reading_75th"
    },
    {
     "expr": "SBK_ConcurrentQ_Write_Reading_90th"
    },
    {
     "expr": "SBK_ConcurrentQ_Write_Reading_99th"
    },
    {
     "expr": "SBK_ConcurrentQ_Write_Reading_99_9th"
    },
    {
     "expr": "SBK_ConcurrentQ_Write_Reading_99_99th"
    }
   ]
  },
  {
   "title": "SBK_ConcurrentQ_Write_Reading_MBPerSec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_ConcurrentQ_Write_Reading_MBPerSec"
    }
   ]
  },
  {
   "title": "SBK_ConcurrentQ_Write_Reading_RecordsPerSec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_ConcurrentQ_Write_Reading_RecordsPerSec"
    }
   ]
  },
  {
   "title": "SBK_ConcurrentQ_Write_Reading_Records_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_ConcurrentQ_Write_Reading_Records_total"
    }
   ]
  },
  {
   "title": "SBK_ConcurrentQ_Write_Reading_Bytes_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_ConcurrentQ_Write_Reading_Bytes_total"
    }
   ]
  },
  {
   "title": "Concurrent Q Avg and Max latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_ConcurrentQ_Write_Reading_AvgLatency"
    },
    {
     "expr": "SBK_ConcurrentQ_Write_Reading_MaxLatency"
    }
   ]
  },
  {
   "title": "Concurrent Q Writers and Readers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SBK_ConcurrentQ_Write_Reading_Readers"
    },
    {
     "expr": "SBK_ConcurrentQ_Write_Reading_Writers"
    }
   ]
  }
 ]
}