/**
 * Copyright (c) KMG. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 */

package io.gem.api.impl;

import io.gem.agent.RemoteDeploymentContract;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Properties;
import java.util.Set;
import java.util.jar.Attributes;
import java.util.jar.JarFile;
import java.util.stream.Stream;

/** Gradle-generated, independently versioned runtime closure for one enabled storage driver. */
final class DriverRuntimeManifest {
    static final String DIRECTORY = "worker-runtime";
    private static final String FORMAT_VERSION = "1";
    private static final int SHA_256_HEX_LENGTH = 64;

    private final String driverName;
    private final String runtimeIdentity;
    private final List<Path> libraries;
    private final Path pathingJar;

    private DriverRuntimeManifest(String driverName, String runtimeIdentity, List<Path> libraries,
                                  Path pathingJar) {
        this.driverName = driverName;
        this.runtimeIdentity = runtimeIdentity;
        this.libraries = List.copyOf(libraries);
        this.pathingJar = pathingJar;
    }

    /**
     * Load and validate the runtime closure generated by the Gradle distribution build.
     *
     * @param sbkDirectory complete installed SBK distribution
     * @param selectedDriver resolved storage driver class name
     * @param sbkVersion expected SBK version
     * @return validated driver runtime manifest
     * @throws IOException when the manifest or one of its artifacts is absent or inconsistent
     */
    static DriverRuntimeManifest load(Path sbkDirectory, String selectedDriver, String sbkVersion)
            throws IOException {
        if (selectedDriver == null || selectedDriver.isBlank()) {
            throw new IOException("Driver-scoped runtime deployment requires a selected storage driver");
        }
        final Path runtimeDirectory = sbkDirectory.resolve(DIRECTORY);
        if (!Files.isDirectory(runtimeDirectory)) {
            throw new IOException("Driver runtime metadata is missing: " + runtimeDirectory
                    + ". Rebuild the distribution with './gradlew installDist'.");
        }
        final Path manifestPath = findManifest(runtimeDirectory, selectedDriver);
        final Properties properties = new Properties();
        try (InputStream input = Files.newInputStream(manifestPath)) {
            properties.load(input);
        }
        if (!FORMAT_VERSION.equals(properties.getProperty(RemoteDeploymentContract.FORMAT_VERSION_PROPERTY))) {
            throw new IOException("Unsupported driver runtime manifest format: " + manifestPath);
        }
        final String driverName = required(properties, "driver.name", manifestPath);
        if (!driverName.equalsIgnoreCase(selectedDriver)) {
            throw new IOException("Driver runtime manifest " + manifestPath + " selects " + driverName
                    + " instead of " + selectedDriver);
        }
        if (!sbkVersion.equals(required(properties, RemoteDeploymentContract.SBK_VERSION_PROPERTY, manifestPath))) {
            throw new IOException("Driver runtime manifest version does not match SBK " + sbkVersion + ": "
                    + manifestPath);
        }
        final String runtimeIdentity = required(properties, "runtime.sha256", manifestPath);
        if (runtimeIdentity.length() != SHA_256_HEX_LENGTH
                || !runtimeIdentity.chars().allMatch(DriverRuntimeManifest::isLowerHexadecimal)) {
            throw new IOException("Invalid driver runtime identity in " + manifestPath);
        }
        final List<String> libraryNames = Arrays.stream(required(properties, "runtime.files", manifestPath)
                        .split(","))
                .map(String::trim).filter(value -> !value.isEmpty()).toList();
        if (libraryNames.isEmpty() || new HashSet<>(libraryNames).size() != libraryNames.size()) {
            throw new IOException("Invalid driver runtime library list in " + manifestPath);
        }
        final Path libraryDirectory = sbkDirectory.resolve("lib");
        final List<Path> libraries = new ArrayList<>(libraryNames.size());
        for (String libraryName : libraryNames) {
            libraries.add(containedFile(libraryDirectory, libraryName));
        }
        for (Path library : libraries) {
            if (!Files.isRegularFile(library)) {
                throw new IOException("Driver runtime dependency is missing: " + library);
            }
        }
        final Path pathingJar = containedFile(runtimeDirectory,
                required(properties, "runtime.pathing", manifestPath));
        validatePathingJar(pathingJar, new HashSet<>(libraryNames));
        return new DriverRuntimeManifest(driverName, runtimeIdentity, libraries, pathingJar);
    }

    String driverName() {
        return driverName;
    }

    String runtimeIdentity() {
        return runtimeIdentity;
    }

    List<Path> libraries() {
        return libraries;
    }

    Path pathingJar() {
        return pathingJar;
    }

    private static Path findManifest(Path directory, String selectedDriver) throws IOException {
        try (Stream<Path> paths = Files.list(directory)) {
            final List<Path> matches = paths.filter(Files::isRegularFile)
                    .filter(path -> Objects.requireNonNull(path.getFileName()).toString().endsWith(".properties"))
                    .filter(path -> stripExtension(path).equalsIgnoreCase(selectedDriver)).toList();
            if (matches.size() != 1) {
                throw new IOException("Expected one driver runtime manifest for '" + selectedDriver + "' under "
                        + directory + ", found " + matches.size());
            }
            return matches.getFirst();
        }
    }

    private static String stripExtension(Path path) {
        final String name = Objects.requireNonNull(path.getFileName()).toString();
        return name.substring(0, name.length() - ".properties".length());
    }

    private static String required(Properties properties, String name, Path manifest) throws IOException {
        final String value = properties.getProperty(name, "").trim();
        if (value.isEmpty()) {
            throw new IOException("Missing " + name + " in " + manifest);
        }
        return value;
    }

    private static Path containedFile(Path directory, String fileName) throws IOException {
        final Path relative = Path.of(fileName);
        if (relative.isAbsolute() || relative.getNameCount() != 1
                || fileName.indexOf('/') >= 0 || fileName.indexOf('\\') >= 0) {
            throw new IOException("Driver runtime entry must be a filename: " + fileName);
        }
        final Path resolved = directory.resolve(relative).normalize();
        if (!resolved.startsWith(directory)) {
            throw new IOException("Driver runtime entry escapes its directory: " + fileName);
        }
        return resolved;
    }

    private static void validatePathingJar(Path pathingJar, Set<String> expectedLibraries) throws IOException {
        if (!Files.isRegularFile(pathingJar)) {
            throw new IOException("Driver runtime pathing JAR is missing: " + pathingJar);
        }
        try (JarFile jar = new JarFile(pathingJar.toFile())) {
            if (jar.getManifest() == null) {
                throw new IOException("Driver runtime pathing JAR has no manifest: " + pathingJar);
            }
            final String classPath = jar.getManifest().getMainAttributes().getValue(Attributes.Name.CLASS_PATH);
            final List<String> classPathEntries = classPath == null || classPath.isBlank() ? List.of()
                    : Arrays.asList(classPath.trim().split("\\s+"));
            final Set<String> actualLibraries = new HashSet<>(classPathEntries);
            if (actualLibraries.size() != classPathEntries.size()) {
                throw new IOException("Driver runtime pathing classpath contains duplicates: " + pathingJar);
            }
            if (!actualLibraries.equals(expectedLibraries)) {
                throw new IOException("Driver runtime pathing classpath does not match its manifest: " + pathingJar);
            }
        }
    }

    private static boolean isLowerHexadecimal(int value) {
        return value >= '0' && value <= '9' || value >= 'a' && value <= 'f';
    }
}
