plugins {
    id 'java'
}
apply plugin: "com.github.spotbugs"

apply from: "$rootDir/gradle/spotbugs.gradle"


repositories {
    mavenCentral()
}

dependencies {
    api project(":sbk-api")
    // https://mvnrepository.com/artifact/org.apache.derby/derby
    api 'org.apache.derby:derby:10.15.2.0'

    // https://mvnrepository.com/artifact/org.apache.derby/derbyclient
    api 'org.apache.derby:derbyclient:10.15.2.0'
    api 'org.apache.derby:derbynet:10.15.2.0'
    api 'org.apache.derby:derbytools:10.15.2.0'


    // https://mvnrepository.com/artifact/mysql/mysql-connector-java
    api 'mysql:mysql-connector-java:8.0.28'

    // https://mvnrepository.com/artifact/org.postgresql/postgresql
    api 'org.postgresql:postgresql:42.1.4'

    // https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc
    api 'com.microsoft.sqlserver:mssql-jdbc:8.2.2.jre8'

    // https://mvnrepository.com/artifact/org.xerial/sqlite-jdbc
    api 'org.xerial:sqlite-jdbc:3.36.0.3'

    // https://mvnrepository.com/artifact/org.mariadb.jdbc/mariadb-java-client
    api 'org.mariadb.jdbc:mariadb-java-client:2.7.1'

    /*
    // https://mvnrepository.com/artifact/org.apache.ignite/ignite-core
    api group: 'org.apache.ignite', name: 'ignite-core', version: '2.12.0'

    // https://mvnrepository.com/artifact/org.apache.ignite/ignite-spring
    api group: 'org.apache.ignite', name: 'ignite-spring', version: '2.12.0'
     */

    // https://mvnrepository.com/artifact/com.h2database/h2
    api 'com.h2database:h2:2.1.210'

}
